Feature - Diarios - Creación módulo Diarios
SinergiaTIC/SinergiaCRM pull request #104
Opened 2024-02-02 12:20 UTC by ainaraRT

Este nuevo módulo de **Diarios**, _stic_Journals_, incorpora la funcionalidad para facilitar el registro de la actividad diaria de los centros residenciales y, en general, de cualquier recurso o instalación que funcione con un sistema de turnos en que los profesionales necesiten comunicarse entre ellos en relación a los hechos ocurridos y/o dejar constancia.
Esta funcionalidad va destinada a entidades que trabajen con centros residenciales o que ofrezcan servicios que operen en un rango horario que exceda el horario de trabajo estándar de un profesional. En particular, está diseñado para aquellas organizaciones que necesitan gestionar y registrar de manera efectiva las actividades diarias, las tareas asignadas a los residentes, las incidencias y las amonestaciones.

### Relaciones
- **Diarios - Personas (N:M):** Pueden haber más de una persona vinculada a un mismo registro de diario.
- **Diarios - Centros (N:1)**: Cada Diario puede estar vinculado a un Centro.

**Pruebas**
- Comprobar que el módulo funciona correctamente.

2024-02-13 11:42 UTC, enricsinergia requested changes
Ver comentarios de código.

Adicional:
1.- Supongo que es porqué esperamos a Vistas personalizadas, pero ahora mismo hay un montón de campos obligatorios que no hacen el módlo usable (si escojo "Journal" debo rellenar los campos de las tareas y faltas obligatoriamente). Si el módulo debe salir antes de tener las vistas personalizadas (que permitirán mostrar / ocultar las pestañas), cómo mínimo los campos sí deberían variar de obligatoriedad según el tipo escogido.

2.- No sé si Centro debería ser obligatorio. Si está en la pantalla hay que rellenarlo y si no, probablemente es que no necesito el campo.

2024-02-13 11:42 UTC, enricsinergia commented on modules/stic_Journal/metadata/subpaneldefs.php
> +    'sort_order' => 'asc',
Mismo tema ordenación comentado en Contacts. Por defecto creo que ordenaría por fecha y descendiente.

2024-02-13 11:42 UTC, enricsinergia commented on modules/stic_Journal/vardefs.php
> +            'importable' => 'true',
Si no hay un motivo específico, creo que los atributos required e importable deberían ser iguales (aplica al resto de campos también)

2024-02-13 11:42 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> +$app_list_strings['stic_journal_types_list']['other'] = 'Otro';
Normalmente en las listas, se incluye como primera opción, la opción vacía para obligar al usuario a seleccionar una y no irnos con el valor que ha quedado por defecto. No sé si ha valorado este punto y ya está bien que estas listas tengan un valor pre-cargado o habría que añadirles la opción en blanco (que creo que es lo que hay que hacer)

2024-02-13 11:42 UTC, enricsinergia commented on modules/stic_Journal/metadata/subpaneldefs.php
> +        ),
No pondŕia la opción de crear persona en el subpanel

2024-02-13 11:42 UTC, enricsinergia requested changes
Ver comentarios de código.

Adicional:
1.- Supongo que es porqué esperamos a Vistas personalizadas, pero ahora mismo hay un montón de campos obligatorios que no hacen el módlo usable (si escojo "Journal" debo rellenar los campos de las tareas y faltas obligatoriamente). Si el módulo debe salir antes de tener las vistas personalizadas (que permitirán mostrar / ocultar las pestañas), cómo mínimo los campos sí deberían variar de obligatoriedad según el tipo escogido.

2.- No sé si Centro debería ser obligatorio. Si está en la pantalla hay que rellenarlo y si no, probablemente es que no necesito el campo.

2024-02-13 11:42 UTC, enricsinergia requested changes
Ver comentarios de código.

Adicional:
1.- Supongo que es porqué esperamos a Vistas personalizadas, pero ahora mismo hay un montón de campos obligatorios que no hacen el módlo usable (si escojo "Journal" debo rellenar los campos de las tareas y faltas obligatoriamente). Si el módulo debe salir antes de tener las vistas personalizadas (que permitirán mostrar / ocultar las pestañas), cómo mínimo los campos sí deberían variar de obligatoriedad según el tipo escogido.

2.- No sé si Centro debería ser obligatorio. Si está en la pantalla hay que rellenarlo y si no, probablemente es que no necesito el campo.

2024-02-13 12:11 UTC, ainaraRT commented
> Ver comentarios de código.
> 
> Adicional: 1.- Supongo que es porqué esperamos a Vistas personalizadas, pero ahora mismo hay un montón de campos obligatorios que no hacen el módlo usable (si escojo "Journal" debo rellenar los campos de las tareas y faltas obligatoriamente). Si el módulo debe salir antes de tener las vistas personalizadas (que permitirán mostrar / ocultar las pestañas), cómo mínimo los campos sí deberían variar de obligatoriedad según el tipo escogido.
> 
> 2.- No sé si Centro debería ser obligatorio. Si está en la pantalla hay que rellenarlo y si no, probablemente es que no necesito el campo.

1. Se está haciendo la implementación mediante jQuery, en cuanto termine, lo subo para revisarlo. Todos aquellos campos que estén en las otras pestañas y el registro sea diferente de "Tarea" o "Infracción", dejarán de ser obligatorios ya que no se muestra dichas pestañas.
2. ¿Se quiere que sea obligatorio?

2024-02-14 06:46 UTC, enricsinergia commented
> > Ver comentarios de código.
> > Adicional: 1.- Supongo que es porqué esperamos a Vistas personalizadas, pero ahora mismo hay un montón de campos obligatorios que no hacen el módlo usable (si escojo "Journal" debo rellenar los campos de las tareas y faltas obligatoriamente). Si el módulo debe salir antes de tener las vistas personalizadas (que permitirán mostrar / ocultar las pestañas), cómo mínimo los campos sí deberían variar de obligatoriedad según el tipo escogido.
> > 2.- No sé si Centro debería ser obligatorio. Si está en la pantalla hay que rellenarlo y si no, probablemente es que no necesito el campo.
> 
> 1. Se está haciendo la implementación mediante jQuery, en cuanto termine, lo subo para revisarlo. Todos aquellos campos que estén en las otras pestañas y el registro sea diferente a "Tarea" o "Infracción", dejarán de ser obligatorios ya que no se muestra dichas pestañas.
> 2. ¿Se quiere que sea obligatorio?

Entiendo que si es un campo específico de Tarea sólo debe ser obligatorio para Tareas, y lo mismo para Infracciones.

Sin embargomirando los paneles, creo que al unir en un único módulo las entradas de diario, las tareas y las infracciones cometimos algún error porqué veo que hay campos de faltas repetidos en Tareas e Infracciones.

Yo haría lo siguiente:
- Incluiría un nuevo tipo: "tarea correctiva" o "medida educativa" (depende de la sensibilidad de la entidad preferirán un literal u otro)
- En este nuevo tipo haría visibles las pestañas de Tarea e Infracción, haciendo obligatorios los campos de ambas (excepto el de cumplimiento, claro)
- Sacaría los campos de Falta de la pestaña de Tareas, aunque dejaría la descripción pero no para describir la falta si no la tarea (y que sea opcional).

Me hubiera gustado poder tener para estas medidas educativas 2 registros: uno con la falta y otro con la tarea, relacionados, pero las auto-relaciones sólo generan un extremo de la relación.

2024-02-15 15:12 UTC, enricsinergia requested changes
Tiene ya muy buena pinta!

Cambiaría una cosa: cuando el tipo de entrada no habilita la pestaña de tareas o infracción, haría que el campo descripción fuera obligatorio. Si no, podemos estar creando una entrada que no dice nada

2024-02-15 16:14 UTC, ManuSinergiaCRM requested changes
Además de los comentarios anteriores: 

El javascript no aplica en la vista de creación rápida de los subpaneles:
- En el de personas no se muestran los campos requeridos de las pestañas de tareas e infracciones
- En el de centros no se muestran las pestañas al cambiar el tipo

En la vista de Aditional Details:
- Los valores de Ámbito y Tarea se muestran con el valor interno acotado por los símbolos ^ ^

2024-02-15 16:31 UTC, ainaraRT commented
> Además de los comentarios anteriores:
> 
> El javascript no aplica en la vista de creación rápida de los subpaneles:
> 
> * En el de personas no se muestran los campos requeridos de las pestañas de tareas e infracciones
> * En el de centros no se muestran las pestañas al cambiar el tipo
> 
> En la vista de Aditional Details:
> 
> * Los valores de Ámbito y Tarea se muestran con el valor interno acotado por los símbolos ^ ^

Para el tema de los Additional Details: Hay un Issue sobre ello https://github.com/SinergiaTIC/SinergiaCRM/issues/80

2024-02-19 13:02 UTC, jalbaiges requested changes
Cadenas revisadas.

2024-02-19 17:09 UTC, enricsinergia commented on custom/Extension/modules/Contacts/Ext/Layoutdefs/SticLayoutdefs.php
> +    'sort_by' => 'name',
Veo que se h acambiado el orden a descendiente pero no el campo por el que se ordena. ¿Algun motivo específico para mantener ordenación por nombre y no por fecha?

2024-02-19 17:13 UTC, enricsinergia commented on custom/metadata/SticRelationshipsMetaData.php
> +        1 => array(
Parece que se ha substituído el índice anterior (journal_ida, contacts_idb) por este. Creo que sería bueno mantener los 2 índices.

2024-02-19 17:16 UTC, enricsinergia commented on modules/stic_Journal/metadata/subpaneldefs.php
> +    'sort_order' => 'desc',
Por defecto haría orden DESC (el que ya hay puesto) pero con el campo fecha (el nombre del diario incluye primero el nombre del centro, con lo que anula el efecto buscado ordenando descendiente)

2024-02-20 09:34 UTC, ManuSinergiaCRM reviewed
A falta de que funcione el subpanel de Diario en el módulo de Centros (ya me preaviso Ainara de que estaba pendiente), veo que funciona correctamente. 

Buen trabajo con la gestión de pestañas!! Por cierto, comprobado que poniendo paneles en vez de pestañas tb funciona :+1:

2024-02-20 14:16 UTC, jalbaiges submitted a review, later dismissed

2024-02-20 16:36 UTC, jalbaiges approved these changes

2024-02-20 16:45 UTC, enricsinergia requested changes
No lo había visto hasta ahora: cuando creas un registro nuevo, si dejas el nombre en blanco te pierde la fecha / hora que le pones y te pone la fecha hora actual, tanto en el nombre como en la fecha de la entrada

2024-02-21 12:08 UTC, ManuSinergiaCRM approved these changes
(A)probado

Faltaría que no se muestren las pestañas ocultas al guardar el registro y dar un error de validación. Esto se corregirá en este otro PR: https://github.com/SinergiaTIC/SinergiaCRM/issues/118

2024-02-22 08:28 UTC, enricsinergia approved these changes
(A)provado

2024-02-22 08:53 UTC, merged