Enhancement - Economía - Añadir acción de validación para avisar del próximo vencimiento de tarjetas
SinergiaTIC/SinergiaCRM pull request #111
Opened 2024-02-10 07:30 UTC by enricsinergia

- Closes #108 

## Description
Se añade una acción de validación al proceso mensual de revisión de datos económicos.
Esta acción revisa qué tarjetas tienen su caducidad en el mes (el proceso se ejecuta el día 1) y añade un listado al resultado de la validación para que el usaurio encargado pueda anticiparse a problemas en el momento del cobro y pedir a las personas / organizaciones que le faciliten nuevos datos o cambien a domiciliación.

## Motivation and Context
Actualmente, no hay ningún aviso de que las tarjetas están próximas a su vencimiento y lo que se produce es que en el momento de procesar la remesa de cobro de tarjetas se produce un error con aquellas que están caducadas, generándose de entrada un impago que hay que gestionar.

## How To Test This
1. Crear unos Compromiso sde pago periódico con tarjeta
2. En BBDD asignar un valor al campo _card_expiry_date_, formato AAMM, de manera que stengamos tarjetas ya caducadas, que caduquen en el mes y que caduquen en el futuro
3. Comprobar que la acción de validación se ha añadido a la tarea de validación económica mensual
4. Cambiar la planificación de dicha tarea para que se pueda ejecutar al momento
5. Forxar la ejecución del planificador invocando a SticCron
6. Acceder al resultado de las validaciones y ver que aprecen las tarjetas que deben aparecer

2024-02-16 12:43 UTC, ManuSinergiaCRM requested changes

2024-02-16 12:43 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        $resultInfo = $this->getLabel('RESULT_INFO'); // keep here
Meter esta línea dentro del while ya que si no todos los resultados de validación tienen la fecha de expiración del primer compromiso de pago tratado.

Esto es debido a que en la primera iteración la $resultInfo tiene la cadena: La tarjeta de este compromiso de pago recurrente está próxima a su vencimiento @expiring_date@.

pero en el resto de iteraciones @expiring_date@ tiene el valor sobreescrito por la primera iteración.

2024-02-16 12:43 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +            $PCBean = Beanfactory::getBean('stic_Payment_Commitments', $row['id']);
Esta variable no se usa

2024-02-16 12:43 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        global $app_list_strings;
Esta variable no se usa

2024-02-16 13:58 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        $resultInfo = $this->getLabel('RESULT_INFO'); // keep here
Hecho

2024-02-16 13:58 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +            $PCBean = Beanfactory::getBean('stic_Payment_Commitments', $row['id']);
Hecho

2024-02-16 13:58 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        global $app_list_strings;
Hecho

2024-02-19 09:28 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-02-19 11:16 UTC, jalbaiges requested changes
Cadenas revisadas.

2024-02-19 11:16 UTC, jalbaiges commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        }
Esto parecería no ser necesario según lo comentado anteriormente.

2024-02-19 11:16 UTC, jalbaiges commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        $minExpiration =str_pad($expirationYear, 2, '0', STR_PAD_LEFT) . str_pad($expirationMonth, 2, '0', STR_PAD_LEFT);
Viendo el nombre del setting y su descripción y viendo este fragmento de código, da la sensación que inicialmente se pretendía ofrecer al usuario la posibilidad de anticipar N meses la detección del vencimiento de las tarjetas. Sin embargo, viendo los posibles valores del setting se desprende que finalmente se optó por permitir elegir entre mes en curso y mes siguiente. Si es así, entonces este fragmento de código puede simplificarse, pues a lo sumo bastaría ver que si el mes actual es diciembre y el mes a analizar es el siguiente, entonces fecha de vencimiento = enero / año próximo. Si la intención es justo la contraria (permitir N meses) entonces debería modificarse la descripción del setting.

2024-02-21 10:34 UTC, enricsinergia commented on SticInstall/sql/ca/Settings.sql
> +('b9755f82-72c9-d361-10b7-5b40699f14c4', NOW(), NOW(), '1', '1', 0, '1', 'TPV', 'TPV_MESES_CADUCIDAD', '0', 'Indica els mesos d''antel·lació amb que avisar del venciment de targetes (0 - mes actual,
Translated

2024-02-21 10:34 UTC, enricsinergia commented on SticInstall/sql/ca/Settings.sql
> +('b9755f82-72c9-d361-10b7-5b40699f14c4', NOW(), NOW(), '1', '1', 0, '1', 'TPV', 'TPV_MESES_CADUCIDAD', '0', 'Indica el mes de venciment de les targetes a revisar (0 = Mes actual, 1 = Mes següent, -1
Eliminado. Como los setting no son un desplegable, se deja la descripción para que se vea que 0 es en elm es actual, 1 en el mes siguiente y así sucesivamente

2024-02-21 10:35 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
> +        $minExpiration =str_pad($expirationYear, 2, '0', STR_PAD_LEFT) . str_pad($expirationMonth, 2, '0', STR_PAD_LEFT);
Se ha mantenido este código (que era la intención) y se ha cambiado la descripción.

2024-02-21 12:27 UTC, ainaraRT submitted a review, later dismissed
(A)Probado

2024-02-21 12:56 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-02-21 14:46 UTC, ainaraRT submitted a review, later dismissed
(A)Probado

2024-02-21 19:03 UTC, jalbaiges approved these changes
Cadenas revisadas.

2024-02-22 08:54 UTC, AlbertoSTIC approved these changes
Aprobado

2024-02-22 08:54 UTC, merged