Feature - General - Registro y disponibilidad horaria
SinergiaTIC/SinergiaCRM pull request #114
Opened 2024-02-12 12:03 UTC by ManuSinergiaCRM

Requisitos: https://docs.google.com/document/d/15VpNY3A47yTTNnB_4796E2gAHfOfXe0de0kCqDXWeOI/edit

2024-05-16 09:32 UTC, enricsinergia commented
Algunas cosas detectadas en una primera revisión del funcional y de los módulos (falta revisar cácabar la parte de informes, revisar código, pruebas....)




1) Desde empleados, la generación periódica me pone las fechas en formato anglosajón aunque no es ese formato ni del sistema ni del ususario
2) Si se modifica el tipo de día en el calendario, se está actualizando el nombre para indicar el tipo pero no se tocan las horas del nombre a pesar que sí se tocan las horas (duration) del registro
2bis) Al hacer el cambio me ha marcado como festivo desde las 9 del día hasta la 9 del día siguiente. Debería ser de 0 a 0, como cuando se crea el registro desde 0.

3) Si incorporo un nuevo empleado, tengo que definirle el calendario desde 0... repetir los pasos para la creación de días laborables, festivos, etc. Sería muy recomendable poder "importar" o asignar un calendario ya definido y no tenerlo que hacer empleado a empleado. Quizás tener empleados "ficticios" para tener el calendario tipo (sin vacaciones y festivos adecuados) de cada centro

4) En la documentación:
	"Esta funcionalidad dependerá de si la entidad ha configurado que el empleado ficha en el CRM. En este apartado se cuenta de manera más detallada."
	El enlace de "apartado" está roto.

5) Ver el calendario de "dependientes". Sólo poderlo hacer a un nivel tiene limitaciones en organizaciones grandes. Tengo un gerente con 2 jefes de área, o el gerente o los jefes de área no podrán ver el calendario de disponibilidad.

6) Informes de SinergiaDA: Mientras no se trasladen bien los grupos de seguridad no serán posibles, ¿no?

7) ¿Cómo se ha previsto limitar la visualización de registros de marcage y de calendario? El gerente puede ver los registros de todos sus empleados, los jefes de sección pueden ver los suyos y de sus empleados pero no de los otros jefes de sección ni empleados de otras secciones....

8) No he encontrado como marcar qué empleados deben fichar. No veo los campos que se detallan en el funcional. Parece que están en los metadata pero no se han subido al repo los vardefs

9) Los campos de start date time y end date time de registro horario no están disponibles en edición inline (tal como parece razonable y está indicado en funcional)

10) En registro horario y Calendario laboral aparece "Assigned to" en lugar de "Employee" como parece indicar el funcional que debería ocurrir

11) En calendario laboral, los campos tipo, fechas inicio y fin, día de la semana no están disponibles en edición inline

12) En vista edición de Empleado me aparece "Create periodic sessions" en el campo TITLE.

13) El fichero de sql de Migrations me daba error desde DBeaver. Ejecutando las sentencias de una en una, parece funcionar.

2024-05-16 13:12 UTC, enricsinergia commented on SticUpdates/Migrations/en/20240402_feature_TimeTracker_WorkCalendar.sql
> +('56dca334-679c-266d-fd9a-660bcd6ed93e', 0, NOW(), NOW(), '1', '1', 'SinergiaCRM - Validación y actualización semanal de datos', 'function::validationActions', NOW(), NULL, '*::6::*::*::0', NULL, NUL
Los literales de este fichero deberían estar en inglés, como en el fichero de SticInstall.

2024-05-16 13:13 UTC, enricsinergia commented on SticUpdates/Migrations/en/20240402_feature_TimeTracker_WorkCalendar.sql
> +REPLACE INTO schedulers (id, deleted, date_entered, date_modified, created_by, modified_user_id, name, job, date_time_start, date_time_end, job_interval, time_from, time_to, last_run, status, catch_u
Damos de alta este scheduler como inactivo, sin embargo las tareas que van al diario se empezarán a ejecutar desde el primer día. ¿Seguro que queremos eso?

2024-05-16 13:16 UTC, enricsinergia commented on SticUpdates/Migrations/20240311_feature_TimeTrackerAndWorkCalendar.sql
> +ALTER TABLE users_cstm add COLUMN `stic_clock_c` bool  DEFAULT '0' NULL;
No sería necesario crear los campos manualmente, ¿no? El repair ya los debería crear, tal como pasa con el SticInstall

2024-05-16 13:36 UTC, enricsinergia commented on custom/Extension/modules/Users/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_USERS_STIC_TIME_TRACKER_FROM_STIC_TIME_TRACKER_TITLE'] = 'Registre horari';
Este literal parece de una relación que al final no se ha creado

2024-05-16 14:30 UTC, enricsinergia commented on modules/Users/metadata/editviewdefs.php
> +                    1 => array (
No me acaba de gustar que la disposición en detalle o edición sea distinta (ya sé que aparece un nuevo campo, pero ese campo no debería afectar cóom situamos estos checks)

2024-05-16 14:56 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> +$app_strings['LBL_CONFIRMATION_POPUP_BOX_CREATE'] = 'A time tracker record will be created with the following information:';
Los literales no aparecen correctamente en el pop-up cuando el idioma es inglés

2024-05-16 14:57 UTC, enricsinergia commented on modules/stic_Time_Tracker/metadata/subpanels/default.php
> +        array('widget_class' => 'SubPanelTopSelectButton', 'popup_module' => $module_name),
No pondría botón de seleccionar en el panel de time tracker. No parece tener mucho sentido.

2024-05-16 15:05 UTC, enricsinergia commented on modules/stic_Work_Calendar/Menu.php
> +if(ACLController::checkAccess('stic_Work_Calendar', 'list', true)){
Parece que el checkAccess debería ser con edit y no con list.
También situaría la opción debajo del list. En todos los módulos las acciones extra siempre estándebajo de import y la segunda opción siempre es el listado.

2024-05-16 15:08 UTC, jalbaiges commented on SticUpdates/Migrations/ca/20240402_feature_TimeTracker_WorkCalendar.sql
> +('7acc83f4-f72e-10d5-969c-660bcb36cb56', "Registre horari - Revisió del total d'hores treballades per empleat durant la setmana anterior", NOW(), NOW(), '1', '1', NULL, 0, '1', NULL, '7acc83f4-f72e-1
El nombre de esta acción parece que se simplificó a posteriori en los ficheros principales de Schedulers. Debería trasladarse el nombre definitivo a estos ficheros de migrations en todos los idiomas.

2024-05-16 15:18 UTC, enricsinergia commented on modules/stic_Time_Tracker/controller.php
> +        die();
Creo que deberíamos usar sugar_die() en lugar de die() para asegurarnos que se cierran conexiones, etc.

2024-05-16 15:32 UTC, enricsinergia commented on modules/stic_Time_Tracker/stic_Time_Tracker.php
> +            AND DATE(date_add(start_date, INTERVAL " . $timeZoneOffset . " HOUR)) = DATE(NOW())
Justo el día del cambio horario y si hay marcajes antes de la hora del cambio, podría fallar. ¿Por qué no usar CONVERT_TZ(start_date, '+00:00', <user_time_zone>)?

2024-05-16 15:51 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_HoursWorkedInPreviousWeek/CheckHoursWorkedInPreviousWeek.php
> +            WHERE swc.start_date BETWEEN DATE_SUB(UTC_TIMESTAMP(), INTERVAL 7 DAY) AND UTC_TIMESTAMP()
Si la ejecución no es a las 00:00, no cogerá bien los marcajes que pueda haber entre las 00:00 y la hora de ejecución de hace 7 días.

2024-05-17 04:30 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_HoursWorkedInPreviousWeek/CheckHoursWorkedInPreviousWeek.php
> +        $sql = "
Incluiría un comentario para indicar que esta query da registros duplicados pero que hay un proceso posterior que los elimina

2024-05-17 04:41 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_MainData/CheckTimeTrackerBeanData.php
> +                WHERE start_date BETWEEN DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY) AND UTC_TIMESTAMP()
Igual que en el caso anterior, si no se ejecuta a las 00:00 no coge exactamente el día anterior

2024-05-17 04:43 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/CheckWorkCalendarBeanData.php
> +                WHERE start_date BETWEEN DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY) AND UTC_TIMESTAMP()
Ídem, no cogemos exactamente el día anterior

2024-05-17 04:52 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +        if ($responsible->is_admin == '0' && isset($responsible->email1)) {
No tengo claro que si el responsable es administrador no deba recibir los mensajes de error de que unapersona supervisada no ha rellenado el control horario

2024-05-17 04:53 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +    if ($employee->is_admin == '0' || (isset($responsible) && $responsible->is_admin == '0'))
Si el empleado tiene permisos de administrador, no avisaremos a nadie de que no ha rellenado el control horario...

2024-05-17 04:56 UTC, enricsinergia commented on modules/stic_Work_Calendar/views/view.detail.php
> +        // If it is an all day type record
El comentario dice justo lo contrario de lo que hace. No acabo de entender por qué necesitamos esa conversión

2024-05-17 05:04 UTC, enricsinergia requested changes
Ver comentarios en el código.

En vista de calendario. Si cojo semana compartida, me muestra el calendario de otro usuario pero no los registros que ahí hay

Cada vez que creo un registro (manual) en el calendario laboral, estoy recibiendo aviso. Sin embargo la creación masiva no avisa. Creo que no debería avisar en ningún caso (o puede ser un caos de notificaciones).

La combo de usuario en control horario y calendario me muestra el código de usuario, en cambio en la creación periódica muestra el nombre y apellidos de usuario.

La creación masiva de calendario no me recoge bien las fechas y me ha creado registros en 1970.

2024-05-17 09:34 UTC, ManuSinergiaCRM commented on custom/Extension/modules/Users/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_USERS_STIC_TIME_TRACKER_FROM_STIC_TIME_TRACKER_TITLE'] = 'Registre horari';
Así es. Cadenas eliminadas

2024-05-17 09:34 UTC, ManuSinergiaCRM commented on modules/Users/metadata/editviewdefs.php
> +                    1 => array (
Modificada la posición para que sea más homogénea entre vistas de edición y detalle.

2024-05-17 09:35 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> +$app_strings['LBL_CONFIRMATION_POPUP_BOX_CREATE'] = 'A time tracker record will be created with the following information:';
Revisado y no consigo reproducirlo. Vuelve a probarlo y si vuelve a aparecer, lo vemos.

2024-05-17 09:35 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/metadata/subpanels/default.php
> +        array('widget_class' => 'SubPanelTopSelectButton', 'popup_module' => $module_name),
Hecho

2024-05-17 09:35 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/Menu.php
> +if(ACLController::checkAccess('stic_Work_Calendar', 'list', true)){
Cambios realizados

2024-05-17 09:35 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/controller.php
> +        die();
Cambiado

2024-05-17 10:32 UTC, AlbertoSTIC commented
> 3\. Si incorporo un nuevo empleado, tengo que definirle el calendario desde 0... repetir los pasos para la creación de días laborables, festivos, etc. Sería muy recomendable poder "importar" o asignar un calendario ya definido y no tenerlo que hacer empleado a empleado. Quizás tener empleados "ficticios" para tener el calendario tipo (sin vacaciones y festivos adecuados) de cada centro

@enricsinergia . Una de las propuestas era proporcionar nosotros, cada año, unas plantillas que definan el calendario "estandard" de cada región. De momento esto se dejó para fase 2. 
En todo caso, actualmente, para hacer lo que dices, es possible utilizar la funcionalida de Duplicar y actualizar masivamente, y de esta manera duplicar calendarios de manera "sencilla".

2024-05-17 11:12 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +        if ($responsible->is_admin == '0' && isset($responsible->email1)) {
El comportamiento por defecto del proceso de ejecución de las acciones de validación es que, en caso de detectar un error, se procede a informar a los administradores. 

Así, notificar al empleado y/o al responsable que tiene sentido en el caso de que no sean administradores ya que si no, les llegará información duplicada.

2024-05-17 11:14 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +    if ($employee->is_admin == '0' || (isset($responsible) && $responsible->is_admin == '0'))
A igual que el comentario anterior, como en caso de detectar un error, siempre se avisa a los administradores. En caso de ser admin el empleado o el responsable no se le envía el email por que le llegará con el comportamiento por defecto.

2024-05-17 11:19 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/views/view.detail.php
> +        // If it is an all day type record
El código oculta la hora de los campos de fecha y hora en caso de ser de tipo "todo el día". En edición lo hacemos con javascript ya que además asignamos valores. 

Para la vista de detalle se vió más fácil hacerlo en el controlador de vista, que también es como lo tenemos hecho en Reservas 

Por otro lado, he actualizado el comentario para que indique lo correcto.

2024-05-17 11:35 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_HoursWorkedInPreviousWeek/CheckHoursWorkedInPreviousWeek.php
> +        $sql = "
Añadido

2024-05-17 11:35 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> +$app_strings['LBL_CONFIRMATION_POPUP_BOX_NOW'] = 'Ahora ';
Eliminada la cadena ya que quedo obsoleta cuando en el cuadro de diálogo puse la fecha en vez del texto 'Ahora'.

2024-05-17 13:37 UTC, ManuSinergiaCRM commented on SticInstall/sql/ca/Settings.sql
> +('6ac2d1e7-ff90-61f0-85c2-66347f0d8311', NOW(), NOW(), '1', '1', 0, '1', 'TIME_TRACKER', 'UPPER_MARGIN_PERCENT', '20', "El marge superior de diferència que hi pot haver entre les hores que l'empleat
Renombrado a:

Prefijo: TIMETRACKER
Nombres: 
- TIMETRACKER_LOWER_MARGIN_PERCENT 
- TIMETRACKER_UPPER_MARGIN_PERCENT

2024-05-17 13:38 UTC, ManuSinergiaCRM commented on SticUpdates/Migrations/ca/20240402_feature_TimeTracker_WorkCalendar.sql
> +('7acc83f4-f72e-10d5-969c-660bcb36cb56', "Registre horari - Revisió del total d'hores treballades per empleat durant la setmana anterior", NOW(), NOW(), '1', '1', NULL, 0, '1', NULL, '7acc83f4-f72e-1
Nombre actualizado

2024-05-17 14:16 UTC, ManuSinergiaCRM commented on SticUpdates/Migrations/ca/20240402_feature_TimeTracker_WorkCalendar.sql
> +('7acc83f4-f72e-10d5-969c-660bcb36cb56', "Registre horari - Revisió del total d'hores treballades per empleat durant la setmana anterior", NOW(), NOW(), '1', '1', NULL, 0, '1', NULL, '7acc83f4-f72e-1
Hecho

2024-05-19 07:52 UTC, enricsinergia commented
> > 3. Si incorporo un nuevo empleado, tengo que definirle el calendario desde 0... repetir los pasos para la creación de días laborables, festivos, etc. Sería muy recomendable poder "importar" o asignar un calendario ya definido y no tenerlo que hacer empleado a empleado. Quizás tener empleados "ficticios" para tener el calendario tipo (sin vacaciones y festivos adecuados) de cada centro
> 
> @enricsinergia . Una de las propuestas era proporcionar nosotros, cada año, unas plantillas que definan el calendario "estandard" de cada región. De momento esto se dejó para fase 2. En todo caso, actualmente, para hacer lo que dices, es possible utilizar la funcionalidad de Duplicar y actualizar masivamente, y de esta manera duplicar calendarios de manera "sencilla".

@AlbertoSTIC : Ya he visto que iba por ahí. Por eso proponía tener empelados ficticios para cada calendario. El problema que hay con el módulo de Calendario es que tiene propiamente el calendario laboral (con festivos, etc) y las vacaciones, bajas y demás del empleado por lo que una vez empezado el año ya no se puede duplicar el calendario d eun trabajador para otro porqué puede incluir vaciones, bajas, permisos... No es un comentario tanto del código como de documentación donde se puede incluir dicha sugerencia para facilitar la labor en entidades donde haya bastantes empleados.

2024-05-19 07:57 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +        if ($responsible->is_admin == '0' && isset($responsible->email1)) {
Sibien es cierto que les llegaría información duplicada, el formato es bastante diferente, ¿no?
En el caso de los administradores, reciben aviso para que revisen el listado (donde puede haber un montón de errores con los que no tienen relación), mientras que el aviso a empleado/responsable avisa de un caso concreto.
Me imagino que yo tenga permisos de administrador y a la vez tenga un pequeño equipo. No recibo avisos de mi equipo que me llamen la atención y sólo recibo el listado con los errores de toda la organización.
Yo querría recibir los avisos como administrador (que son de un tipo) y los avisos como empleado o responsable (que me llaman la atención sobre un caso concreto), pero si decidís lo contrario, no soy nadie para contradeciros ;-)

2024-05-20 07:48 UTC, enricsinergia requested changes
Ver comentarios código

2024-05-20 11:02 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_MainData/CheckTimeTrackerBeanData.php
> +                WHERE start_date BETWEEN DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY) AND UTC_TIMESTAMP()
Lógica modificada para que coja todos los registros del día anterior, se ejecute a la hora que sea.

2024-05-20 11:02 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/CheckWorkCalendarBeanData.php
> +                WHERE start_date BETWEEN DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY) AND UTC_TIMESTAMP()
Lógica modificada para que coja todos los registros del día anterior, se ejecute a la hora que sea.

2024-05-20 11:07 UTC, ManuSinergiaCRM commented
> > > 3. Si incorporo un nuevo empleado, tengo que definirle el calendario desde 0... repetir los pasos para la creación de días laborables, festivos, etc. Sería muy recomendable poder "importar" o asignar un calendario ya definido y no tenerlo que hacer empleado a empleado. Quizás tener empleados "ficticios" para tener el calendario tipo (sin vacaciones y festivos adecuados) de cada centro
> > 
> > 
> > @enricsinergia . Una de las propuestas era proporcionar nosotros, cada año, unas plantillas que definan el calendario "estandard" de cada región. De momento esto se dejó para fase 2. En todo caso, actualmente, para hacer lo que dices, es possible utilizar la funcionalidad de Duplicar y actualizar masivamente, y de esta manera duplicar calendarios de manera "sencilla".
> 
> @AlbertoSTIC : Ya he visto que iba por ahí. Por eso proponía tener empelados ficticios para cada calendario. El problema que hay con el módulo de Calendario es que tiene propiamente el calendario laboral (con festivos, etc) y las vacaciones, bajas y demás del empleado por lo que una vez empezado el año ya no se puede duplicar el calendario d eun trabajador para otro porqué puede incluir vaciones, bajas, permisos... No es un comentario tanto del código como de documentación donde se puede incluir dicha sugerencia para facilitar la labor en entidades donde haya bastantes empleados.


Hablado con Enric y visto que el calendario laboral de un empleado puede tener modificaciones personales hechas por el usuario, se tendrá en cuenta para la documentación y se sugererirá a las entidades que valoren tener empleados ficticios para aquellos casos donde les facilite el proceso de carga de datos.

2024-05-20 11:07 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_HoursWorkedInPreviousWeek/CheckHoursWorkedInPreviousWeek.php
> +                    $lowerMarginPercent = stic_SettingsUtils::getSetting('LOWER_MARGIN_PERCENT2');
Realizado

2024-05-20 11:07 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_MainData/CheckTimeTrackerBeanData.php
> +        $sql = "SELECT id, name, start_date, end_date, assigned_user_id
Aunque por usuario no debería haber más de 2-3 registros al día, aplicada la sugerencia

2024-05-20 11:41 UTC, ManuSinergiaCRM commented on SticUpdates/Migrations/en/20240402_feature_TimeTracker_WorkCalendar.sql
> +('56dca334-679c-266d-fd9a-660bcd6ed93e', 0, NOW(), NOW(), '1', '1', 'SinergiaCRM - Validación y actualización semanal de datos', 'function::validationActions', NOW(), NULL, '*::6::*::*::0', NULL, NUL
Modificado

2024-05-20 11:49 UTC, ManuSinergiaCRM commented on SticUpdates/Migrations/20240311_feature_TimeTrackerAndWorkCalendar.sql
> +ALTER TABLE users_cstm add COLUMN `stic_clock_c` bool  DEFAULT '0' NULL;
Cierto, estaban ahí para cuando cargaba el fichero manualmente. 

He comentado ambas líneas.

2024-05-20 14:04 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/stic_Time_Tracker.php
> +            AND DATE(date_add(start_date, INTERVAL " . $timeZoneOffset . " HOUR)) = DATE(NOW())
Aceptada la propuesta de uso de CONVERT_TZ ya que aplica el offset correspondiente a la fecha recibida por parámetro, evitando errores en casos de uso como el que expone Enric

2024-05-20 14:42 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +        if ($responsible->is_admin == '0' && isset($responsible->email1)) {
Me parece una apreciación a tener en cuenta. Además, como Administrador pudiera no darle la misma importancia que como empleado o responsable.

Cambio realizado

2024-05-20 14:43 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/include/Mailing/Utils.php
> +    if ($employee->is_admin == '0' || (isset($responsible) && $responsible->is_admin == '0'))
A igual que en el comentario anterior, se acepta la propuesta ya que el email a Administradores es más genérico que el de empleado o responsable

2024-05-21 09:33 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/CheckWorkCalendarBeanData.php
> +        $tzone = $current_user->getPreference('timezone');
$tzone me está llegando a null

2024-05-21 09:34 UTC, enricsinergia commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/CheckWorkCalendarBeanData.php
> +                DATE(CONVERT_TZ(start_date, '+00:00', '" . $tzone ."')) BETWEEN DATE(DATE_SUB(CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '" . $tzone ."'), INTERVAL 1 DAY)) AND CONVERT_TZ(UTC_TIMESTAMP(),
Ha desaparecido un WHERE. También fíjate que la segunda fecha del between lleva hora todavía (falta el date())

2024-05-21 12:05 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/CheckWorkCalendarBeanData.php
> +                DATE(CONVERT_TZ(start_date, '+00:00', '" . $tzone ."')) BETWEEN DATE(DATE_SUB(CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '" . $tzone ."'), INTERVAL 1 DAY)) AND CONVERT_TZ(UTC_TIMESTAMP(),
Modificado

2024-05-21 12:06 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/CheckWorkCalendarBeanData.php
> +        $tzone = $current_user->getPreference('timezone');
No consigo reproducir este caso de uso. Lo vemos cuando puedas

2024-05-21 12:16 UTC, ManuSinergiaCRM commented on SticUpdates/Migrations/en/20240402_feature_TimeTracker_WorkCalendar.sql
> +REPLACE INTO schedulers (id, deleted, date_entered, date_modified, created_by, modified_user_id, name, job, date_time_start, date_time_end, job_interval, time_from, time_to, last_run, status, catch_u
Tratado en reunión: Como con el resto de planificadores, el planificador semanal también estará activo por defecto.

2024-05-27 09:30 UTC, enricsinergia requested changes
Ver comentarios en código

2024-05-27 09:30 UTC, enricsinergia commented on modules/stic_Work_Calendar/Utils.php
> +                $query = "SELECT * FROM stic_work_calendar
Si tengo el turno de noche no puedo pedir vacaciones. Arggg!
Tengo que trabajo el día 28 a partir de las 22.00 hasta las 06.00 del 29. 
Y tabajo del 30 a las 22.00 hasta el 31 a las 06.00.
No puedo poner un día de vacaciones el día 29 (ni 28 ni 30) porqué el turno del 28 acaba el 29.

2024-05-27 09:30 UTC, enricsinergia commented on modules/stic_Work_Calendar/Utils.php
> +        $query = "SELECT * FROM stic_work_calendar
De la misma forma que se mira que no haya un registro de vacaciones en el día que se pone uno de trabajo, quizás habría que verificar que no se definen jornadas de trabajo solapadas.

2024-05-27 10:43 UTC, AlbertoSTIC commented on modules/stic_Work_Calendar/Utils.php
> +                $query = "SELECT * FROM stic_work_calendar
El día de vacaciones se pedirá para el día de la Fecha de inicio de tu día laboral.

En principio, revisando el código, no he visto que haya incompatibilidad. O, si la hay, no debería haberla.

2024-05-27 12:06 UTC, enricsinergia commented on modules/stic_Work_Calendar/Utils.php
> +                $query = "SELECT * FROM stic_work_calendar
Ahora reviso el código, pero como mínimo a mi me salta error:
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/57436616/c6fd69ff-92f3-4de3-8551-115be0255b1d)
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/57436616/3abda04d-bedf-4b84-a71b-78ed569e718a)

2024-05-27 12:15 UTC, enricsinergia commented on modules/stic_Work_Calendar/Utils.php
> +                $query = "SELECT * FROM stic_work_calendar
La query mira que la fecha de inicio sea anterior a la fecha fin del día de vacaciones y que la fecha de fin sea posterior a la fecha de inicio del día de vacaciones. Es decir, que no haya ningún registro que se solape con las 24 horas del día de vacaciones. 
Lo que entiendo que sugiere @AlbertoSTIC , que creo que es el camino a seguir, es que lo que se debe mirar es que no haya ningún turno de trabajo que se inicie en el día de vacaciones.

2024-05-27 15:19 UTC, PaulaaSTIC requested changes

2024-05-27 15:19 UTC, PaulaaSTIC commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> +$app_list_strings['moduleList']['stic_Work_Calendar'] = 'Time availability';
Se ha quedado aquí el nombre antiguo.

2024-05-27 15:23 UTC, PaulaaSTIC requested changes
Si comenzamos un registro horario, aceptamos y no refrescamos más la página, al finalizar el fichaje, la hora de finalización será la misma que la hora en que se creó el registro, no se ha actualizado. Es necesario recargar la página antes de mostrar el diálogo de fin de fichaje para que la hora de cierre sea la hora actual.

2024-05-27 16:28 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_strings['LBL_CONFIRMATION_POPUP_BOX_CANCEL'] = 'Cancel';
Hecho

2024-05-27 16:29 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/menuButton/SticTimeTrackerButtonInMainMenu.js
> +            <button id="time-tracker-dialog-button-confirm" onclick="timeTrackerDialogConfirm(localStorage.date, document.getElementById('time-tracker-dialog-description').value)">${SUGAR.language.ge
Arreglado en este commit: https://github.com/SinergiaTIC/SinergiaCRM/pull/114/commits/a0dd8c0957e88f0fe570eed7abfeaf6378dd84ac

2024-05-27 16:33 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/views/view.edit.php
> +        echo '<script type="text/javascript">
Solucionado para la vista de detalle, de vista y de popup

2024-05-27 16:34 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/metadata/detailviewdefs.php
> +                0 => array(
Por ahora se implemento de igual manera que se muestra en sesiones.

Anotado como posible mejora en fases venideras

2024-05-27 16:35 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/Utils.js
> +function checkIfExistsOtherTypesIncompatibleRecords(startDate, endDate, type, assignedUserId)
Anotada como posible mejora

2024-05-27 16:39 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/Utils.php
> +        $query = "SELECT * FROM stic_work_calendar
Anotado como posible mejora

2024-05-27 16:41 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> +$app_list_strings['moduleList']['stic_Work_Calendar'] = 'Time availability';
Cambiado en inglés y catalán

2024-05-27 16:47 UTC, PaulaaSTIC requested changes

2024-05-27 16:47 UTC, PaulaaSTIC commented on SticUpdates/Migrations/20240311_feature_TimeTrackerAndWorkCalendar.sql
> +-- ALTER TABLE users_cstm add COLUMN `stic_clock_c` bool  DEFAULT '0' NULL;
Creo que estas líneas no deberían estar comentadas.

2024-05-28 05:48 UTC, enricsinergia commented on modules/stic_Time_Tracker/menuButton/SticTimeTrackerButtonInMainMenu.js
> +            <button id="time-tracker-dialog-button-confirm" onclick="timeTrackerDialogConfirm(localStorage.date, document.getElementById('time-tracker-dialog-description').value)">${SUGAR.language.ge
Me sigue sin recuperar el valor que ya había en el texto cuando le doy a cerrar el marcaje.

2024-05-28 07:23 UTC, ManuSinergiaCRM commented on SticUpdates/Migrations/20240311_feature_TimeTrackerAndWorkCalendar.sql
> +-- ALTER TABLE users_cstm add COLUMN `stic_clock_c` bool  DEFAULT '0' NULL;
Eliminadas

2024-05-28 07:24 UTC, ManuSinergiaCRM commented
> Si comenzamos un registro horario, aceptamos y no refrescamos más la página, al finalizar el fichaje, la hora de finalización será la misma que la hora en que se creó el registro, no se ha actualizado. Es necesario recargar la página antes de mostrar el diálogo de fin de fichaje para que la hora de cierre sea la hora actual.

Resuelto en este commit: https://github.com/SinergiaTIC/SinergiaCRM/pull/114/commits/5e0888e4d30c46f8506c89dc50749ce20de7c537

2024-05-28 07:27 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/Utils.php
> +                $query = "SELECT * FROM stic_work_calendar
Comprobaciones actualizadas para revisar que no exista algún registro incompatible en el mismo día que el indicado en la fecha de inicio del registro a guardar

2024-05-28 07:28 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/menuButton/SticTimeTrackerButtonInMainMenu.js
> +            <button id="time-tracker-dialog-button-confirm" onclick="timeTrackerDialogConfirm(localStorage.date, document.getElementById('time-tracker-dialog-description').value)">${SUGAR.language.ge
Lo vemos juntos que yo ya no consigo reproducirlo

2024-05-28 07:42 UTC, enricsinergia commented on modules/stic_Time_Tracker/menuButton/SticTimeTrackerButtonInMainMenu.js
> +            <button id="time-tracker-dialog-button-confirm" onclick="timeTrackerDialogConfirm(localStorage.date, document.getElementById('time-tracker-dialog-description').value)">${SUGAR.language.ge
Explicado. El comentario se añade al existente.

2024-05-28 08:27 UTC, enricsinergia commented on modules/stic_Work_Calendar/Utils.php
> +                $query = "SELECT * FROM stic_work_calendar
Parece que la nueva query funciona perfectamente.

2024-05-28 08:30 UTC, enricsinergia commented
Si en calendario laboral empiezo a entrar las horas y luego selecciono en tipo "laborable" me borra las horas que había entrado.

2024-05-28 08:46 UTC, PaulaaSTIC requested changes
La vista de lista de Registro Horario no tiene Detalles Adicionales; en Calendario Laboral sí están incluidos.

2024-05-28 10:01 UTC, ManuSinergiaCRM commented
> Si en calendario laboral empiezo a entrar las horas y luego selecciono en tipo "laborable" me borra las horas que había entrado.

Resuelto en este commit: https://github.com/SinergiaTIC/SinergiaCRM/pull/114/commits/9522b1bb6fe1f4a0e982732f6ce87adecd6ffaaf

2024-05-28 11:51 UTC, PaulaaSTIC requested changes
Cuando una actividad comienza antes de la hora de registro laboral, la barra de tiempo se pinta en medio de la actividad.
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/125350097/841c87be-2ae6-4884-b1f2-91aed60d8dc7)

2024-05-28 15:02 UTC, PaulaaSTIC commented
Si un usuario tiene un registro laboral, pero en el calendario no se marca la opción 'Calendario laboral - Mostrar registros', el calendario del usuario no se mostrará a menos que eliminemos el registro laboral o que creemos alguna otra actividad. Sin este desarrollo, los calendarios sin actividades se mostraban vacíos.

![Test_Calendar](https://github.com/SinergiaTIC/SinergiaCRM/assets/125350097/a6adfc58-3d06-458b-95bf-9fb161cb899a)

2024-05-28 16:05 UTC, ManuSinergiaCRM commented
> Si un usuario tiene un registro laboral, pero en el calendario no se marca la opción 'Calendario laboral - Mostrar registros', el calendario del usuario no se mostrará a menos que eliminemos el registro laboral o que creemos alguna otra actividad. Sin este desarrollo, los calendarios sin actividades se mostraban vacíos.
> 
> ![Test_Calendar](https://private-user-images.githubusercontent.com/125350097/334467004-a6adfc58-3d06-458b-95bf-9fb161cb899a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTI1MzgsIm5iZiI6MTcxNjkxMjIzOCwicGF0aCI6Ii8xMjUzNTAwOTcvMzM0NDY3MDA0LWE2YWRmYzU4LTNkMDYtNDU4Yi05NWJmLTlmYjE2MWNiODk5YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxNjAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZkZGUwMTFmMmNhYmMyZTJhNmNlODFlMTdlMGRjMDRlYWZlNGYxMTAwYWNiNDU1NDhhNjIxY2IyNTRkZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BKOAcrHWD_UKkc6hq-G0-UAs82MESJ3b94ej4agCLsY) [ ![Test_Calendar](https://private-user-images.githubusercontent.com/125350097/334467004-a6adfc58-3d06-458b-95bf-9fb161cb899a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTI1MzgsIm5iZiI6MTcxNjkxMjIzOCwicGF0aCI6Ii8xMjUzNTAwOTcvMzM0NDY3MDA0LWE2YWRmYzU4LTNkMDYtNDU4Yi05NWJmLTlmYjE2MWNiODk5YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxNjAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZkZGUwMTFmMmNhYmMyZTJhNmNlODFlMTdlMGRjMDRlYWZlNGYxMTAwYWNiNDU1NDhhNjIxY2IyNTRkZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BKOAcrHWD_UKkc6hq-G0-UAs82MESJ3b94ej4agCLsY) ](https://private-user-images.githubusercontent.com/125350097/334467004-a6adfc58-3d06-458b-95bf-9fb161cb899a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTI1MzgsIm5iZiI6MTcxNjkxMjIzOCwicGF0aCI6Ii8xMjUzNTAwOTcvMzM0NDY3MDA0LWE2YWRmYzU4LTNkMDYtNDU4Yi05NWJmLTlmYjE2MWNiODk5YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxNjAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZkZGUwMTFmMmNhYmMyZTJhNmNlODFlMTdlMGRjMDRlYWZlNGYxMTAwYWNiNDU1NDhhNjIxY2IyNTRkZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BKOAcrHWD_UKkc6hq-G0-UAs82MESJ3b94ej4agCLsY) [ ](https://private-user-images.githubusercontent.com/125350097/334467004-a6adfc58-3d06-458b-95bf-9fb161cb899a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTI1MzgsIm5iZiI6MTcxNjkxMjIzOCwicGF0aCI6Ii8xMjUzNTAwOTcvMzM0NDY3MDA0LWE2YWRmYzU4LTNkMDYtNDU4Yi05NWJmLTlmYjE2MWNiODk5YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxNjAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZkZGUwMTFmMmNhYmMyZTJhNmNlODFlMTdlMGRjMDRlYWZlNGYxMTAwYWNiNDU1NDhhNjIxY2IyNTRkZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BKOAcrHWD_UKkc6hq-G0-UAs82MESJ3b94ej4agCLsY)

Resuelto en este commit: https://github.com/SinergiaTIC/SinergiaCRM/pull/114/commits/b318c4294e4dfd8522944128ad4fff2992389b03

2024-05-28 16:51 UTC, jalbaiges requested changes
Cadenas revisadas con algunas sugerencias de cambios/mejoras. Volved a solicitarme revisión final cuando se hayan introducido las correcciones que se consideren.

Aprovecho para comentar que en la vista de detalle de Calendario laboral, cuando el tipo es de día completo, la fecha final que se muestra es la del día siguiente. Intuyo que puede estar relacionado con que la fecha de finalización efectiva en base de datos sea las 00:00:00 del día siguiente. De ser por esto, igual debería considerarse indicar las 23:59:59 del día en curso.

2024-05-28 16:51 UTC, jalbaiges commented on modules/stic_Work_Calendar/language/ca_ES.lang.php
> +  'LBL_END_DATE_EXCCEDS_24_HOURS' => "La diferència entre l'inici i la finalització ha de ser inferior a 24 hores.",
Error tipográfico: debería ser EXCEEDS.

2024-05-28 16:51 UTC, jalbaiges commented on modules/stic_Work_Calendar/language/gl_ES.lang.php
> +  'LBL_DESCENDING' => 'Descendente',
Este primer bloque de cadenas ya está disponible en gallego, se puede aplicar a los dos módulos.

2024-05-29 07:03 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_strings['LBL_CONFIRMATION_POPUP_BOX_CREATE'] = 'Es crearà un registre horari amb la informació següent:';
Hecho

2024-05-29 07:03 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> +$app_strings['LBL_CONFIRMATION_POPUP_BOX_ACCEPT'] = 'Ok';
Hecho

2024-05-29 07:03 UTC, ManuSinergiaCRM commented on modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/language/ca_ES.lang.php
> +    'EMPLOYEE_NO_ACTIVATE_TIME_TRACKER'=> "La funcionalitat de Registre horari no està activada a l'empleat: ",
Hecho

2024-05-29 07:03 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/language/ca_ES.lang.php
> +  'LBL_END_DATE_EXCCEDS_24_HOURS' => "La diferència entre l'inici i la finalització ha de ser inferior a 24 hores.",
Hecho

2024-05-29 07:03 UTC, ManuSinergiaCRM commented on modules/stic_Work_Calendar/language/gl_ES.lang.php
> +  'LBL_DESCENDING' => 'Descendente',
Hecho

2024-05-30 11:55 UTC, ManuSinergiaCRM commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_list_strings['stic_work_calendar_types_list']['punctual'] = 'Absència puntual';
Aceptada la propuesta y realizados los cambios

2024-05-30 11:56 UTC, ManuSinergiaCRM commented
> Aprovecho para comentar que en la vista de detalle de Calendario laboral, cuando el tipo es de día completo, la fecha final que se muestra es la del día siguiente. Intuyo que puede estar relacionado con que la fecha de finalización efectiva en base de datos sea las 00:00:00 del día siguiente. De ser por esto, igual debería considerarse indicar las 23:59:59 del día en curso.

Aplicada la solución implementada en Reservas

2024-05-30 14:42 UTC, jalbaiges approved these changes
Revisadas las cadenas. El desarrollo general tiene pinta que va a ser bien recibido. ;-)

2024-05-31 07:40 UTC, enricsinergia commented
Una tonteria muy menor:
Al reducir mucho la resolución (como en un móbil), la barra superior tapa el recuadro para fichar:
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/57436616/ab8f1bd1-4165-482f-9ab4-76313a002fba)

2024-05-31 07:51 UTC, enricsinergia commented
Otra tontería: cuando creas registro de control horario con el botón, te manda mail conforme tú mismo te has asignado un registro de tipo control horario

2024-05-31 07:55 UTC, enricsinergia commented
Más tonterías. 
En catalán tenemos puesto "Accepta" i "Cancela" (imperativo) mientras que en castellano tenemos "Aceptar" y "Cancelar" (infinitivo).
No tengo claro qué dice la guía de estilos STIC pero supongo que ambos deberían usar el mismo tiempo verbal.
@jalbaiges ?

2024-05-31 07:57 UTC, enricsinergia commented on custom/Extension/modules/Calendar/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_SETTINGS_SHARED_CALENDAR_SEPARATE_INFO'] = 'Si està opció està premuda, els esdeveniments de calendari laboral dels diferents usuaris seleccionats poden quedar solapats. Per visuali
Este literal es incorrecto.
Me gusta la aproximación en castellano, que traducida quedaría como "Amb aquesta opció activada els esdeveniments de calendari laboral dels diferents usuaris seleccionats poden quedar solapats. Per visualitzar la informació de Calendari laboral es recomana separar els calendaris dels diferents usuaris"

2024-05-31 08:05 UTC, ManuSinergiaCRM commented
> Una tonteria muy menor: Al reducir mucho la resolución (como en un móbil), la barra superior tapa el recuadro para fichar: ![image](https://private-user-images.githubusercontent.com/57436616/335486451-ab8f1bd1-4165-482f-9ab4-76313a002fba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDE1MjksIm5iZiI6MTcxNzE0MTIyOSwicGF0aCI6Ii81NzQzNjYxNi8zMzU0ODY0NTEtYWI4ZjFiZDEtNDE2NS00ODJmLTlhYjQtNzYzMTNhMDAyZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3NDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjOGY5ZDJmZDM1MTA4ZjM3OWY0MGM5MjNiY2ZhMjg3NTcyYzUwNmFhMTFhNDVmZjk5ZTU2ZWVmZWVmYTQ4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZFasyULrY1O8AhszDLXtyckYpcTo1FycJs013EaO-UU)


Corregido

2024-05-31 08:07 UTC, jalbaiges commented
> Más tonterías. En catalán tenemos puesto "Accepta" i "Cancela" (imperativo) mientras que en castellano tenemos "Aceptar" y "Cancelar" (infinitivo). No tengo claro qué dice la guía de estilos STIC pero supongo que ambos deberían usar el mismo tiempo verbal. @jalbaiges ?

Es correcto como está. En castellano las instrucciones al software se dan mediante el uso del infinitivo (Aceptar, Cancelar, Editar, Borrar, Guardar...) mientras que en catalán se dan mediante el imperativo (Accepta, Cancel·la, Edita, Esborra, Desa...). Igualmente, cuando el software se dirige al usuario en castellano lo hace mediante el "usted", que equivale a la tercera persona del singular (¿Desea...?), mientras que en catalán lo hace mediante el "vos", que equivale a la segunda del plural (Voleu...?).

2024-05-31 08:11 UTC, ManuSinergiaCRM commented
> Otra tontería: cuando creas registro de control horario con el botón, te manda mail conforme tú mismo te has asignado un registro de tipo control horario

Corregido

2024-05-31 08:16 UTC, jalbaiges commented on custom/Extension/modules/Calendar/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_SETTINGS_SHARED_CALENDAR_SEPARATE_INFO'] = 'Si està opció està premuda, els esdeveniments de calendari laboral dels diferents usuaris seleccionats poden quedar solapats. Per visuali
Por alguna razón se quedó la cadena sin revisar después de haber ajustado la versión en castellano. Ahora ya son coherentes las dos versiones.

2024-05-31 09:18 UTC, enricsinergia commented
3 en 1: 
- URL no funciona
- Me da un error con un registro del día 31 
- El registro es de tipo vacaciones y no debería darlo

2024-05-31 10:02 UTC, PaulaaSTIC requested changes
- Las vacaciones que se generan a través de "Crear registros periódicos" se muestran como del 29-1, mientras que si generas un registro único, se muestra como el día 27.
- El día 1, al generar el registro periódico, se considera que hasta las 9 está de vacaciones, pero aun así permite generar un registro laborable, y se solapan ambos colores.

![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/125350097/83a88bba-b51f-4259-a615-92ce5dafd338)

2024-05-31 10:24 UTC, ManuSinergiaCRM commented
> 3 en 1:
> 
> * URL no funciona del mail enviado al validar registro horario vs work calendar (enlaza un registro de calendario pero pone el módulo de time tracker)
> * Me da un error con un registro del día 31
> * El registro es de tipo vacaciones y no debería darlo

Corregido

2024-05-31 13:32 UTC, ManuSinergiaCRM commented
> * Las vacaciones que se generan a través de "Crear registros periódicos" se muestran como del 29-1, mientras que si generas un registro único, se muestra como el día 27.
> * El día 1, al generar el registro periódico, se considera que hasta las 9 está de vacaciones, pero aun así permite generar un registro laborable, y se solapan ambos colores.
> 
> ![image](https://private-user-images.githubusercontent.com/125350097/335535178-83a88bba-b51f-4259-a615-92ce5dafd338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjE2ODgsIm5iZiI6MTcxNzE2MTM4OCwicGF0aCI6Ii8xMjUzNTAwOTcvMzM1NTM1MTc4LTgzYTg4YmJhLWI1MWYtNDI1OS1hNjE1LTkyY2U1ZGFmZDMzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMzE2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODEzOGVkNWI0N2RmM2FiODA4ZjgwNjRmZDYyZWI1ZWI1OTAyYWM2MzNiMmI3MWNmNDQ0NTZiNTFjOTFlMzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.of6yQYHCkWPwrzmxYc-OwoaQNKvBFtuLcL6TceEWNPo)

Resuelto en este commit: https://github.com/SinergiaTIC/SinergiaCRM/pull/114/commits/9eb9e39372a018e7e841d3c0e77a03e4a74f948d

2024-05-31 14:45 UTC, jalbaiges approved these changes
No hay cambios en cadenas.

2024-06-03 07:47 UTC, enricsinergia approved these changes
(A)provado

2024-06-03 09:18 UTC, PaulaaSTIC requested changes
Al crear un registro periódico, se obliga a seleccionar una opción distinta de "Ninguno". Entiendo que la idea de crear registros periódicos es crear más de uno, pero no sé si entonces la opción tiene sentido si no vamos a poder marcarla.


![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/125350097/3e2b0fa8-e1d1-4213-a0a4-3155d245fa25)

2024-06-03 09:25 UTC, ManuSinergiaCRM commented
> Al crear un registro periódico, se obliga a seleccionar una opción distinta de "Ninguno". Entiendo que la idea de crear registros periódicos es crear más de uno, pero no sé si entonces la opción tiene sentido si no vamos a poder marcarla.
> 
> ![image](https://private-user-images.githubusercontent.com/125350097/336012352-3e2b0fa8-e1d1-4213-a0a4-3155d245fa25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDY4NDcsIm5iZiI6MTcxNzQwNjU0NywicGF0aCI6Ii8xMjUzNTAwOTcvMzM2MDEyMzUyLTNlMmIwZmE4LWUxZDEtNDIxMy1hMGE0LTMxNTVkMjQ1ZmEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwOTIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjUzMGU0NWJlMzJlOWQyOGZjZGIxNmFlMWI1ZGU2YjVjYjdjMmMxY2IzYWYxMDk3OGE4YTZlMDY2YjEyMWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RXziOLozUiySjDI2qrorxeXSzmLkE9N2jLFKlhodVf0)



Sucede lo mismo en otras partes del CRM: Al crear un registro de calendario laboral con el campo tipo, una relación con persona con el campo tipo de relación... 

Se deja en blanco para no indicar un valor por defecto que pueda inducir errores, y así, que sea el usuario el que rellene dicho campo con la opción que corresponda.

2024-06-03 10:04 UTC, PaulaaSTIC approved these changes
(A)probado

2024-06-04 08:19 UTC, merged