Enhancement/addingStatusKreporter
SinergiaTIC/SinergiaCRM pull request #128
Opened 2024-02-20 11:26 UTC by AlbertoSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-02-20 15:47 UTC, jalbaiges requested changes

2024-02-20 15:47 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/ca_ES.KReporterCore.php
> +$app_list_strings['kreportsegmentation'][''] = '';
Aunque no sea coherente con lo aplicado por parte de los desarrolladores originales en la lista asociada al campo Status, aplicaría el estándar SinergiaTIC: _stic_kreports_segmentation_list_ (o similar).

2024-02-20 16:13 UTC, AlbertoSTIC commented on custom/Extension/application/Ext/Language/ca_ES.KReporterCore.php
> +$app_list_strings['kreportsegmentation'][''] = '';
Hecho.

2024-02-20 16:36 UTC, jalbaiges approved these changes

2024-02-21 08:18 UTC, PaulaaSTIC approved these changes
(A)probado, visto en filtros, vista de lista y en el propio informe.

2024-02-21 10:43 UTC, ainaraRT approved these changes
(A)Probado

2024-02-21 16:29 UTC, merged