Hotfix - General - Comprobar si las variables están seteadas para evitar aviso de error
SinergiaTIC/SinergiaCRM pull request #13
Opened 2024-01-04 13:45 UTC by ManuSinergiaCRM

- Solves https://github.com/SinergiaTIC/SinergiaCRM/issues/12

Tal y como se indica en el issue, este PR resuelve que se compruebe si está seteada la variable que ha generado un aviso de error de tipo NOTICE

**Pruebas**

1. Configurar un nivel de error **E_NOTICE**. Para ello accedemos al fichero phpdocker/php-fpm/php-ini-overrides.ini del workkit y configuramos **error_reporting = 22527** en la línea 5.
2. Comprobar que en la página de inicio NO se muestra el error 2 indicado en el issue
3. Comprobar que al acceder al módulo de personas NO aparece el error 3 indicado en el issue
12. Importar un registro en cada uno de los módulos y comprobar que NO aparece ni el error 1 indicado en el issue ni los errores relacionados con el módulo.

2024-01-11 14:45 UTC, jordiSTIC commented on custom/modules/Accounts/SticLogicHooksCode.php
> +        if (isset($bean->stic_postal_mail_return_reason_c) && !empty($bean->stic_postal_mail_return_reason_c) && $bean->stic_postal_mail_return_reason_c != $bean->fetched_row['stic_postal_mail_return
Este caso no es exáctamente el mismo: antes entraba en el if si `$bean->stic_postal_mail_return_reason_c` se vaciaba y en la BD no estaba vacío

2024-01-11 14:53 UTC, jordiSTIC commented on include/entryPoint.php
> +        if (isset($_REQUEST['module']) && isset($xssException['module']) && $xssException['module'] == $_REQUEST['module'] && isset($skipAntiXSS) && $skipAntiXSS !== true ) {
no es necesaria la comprobación `isset($skipAntiXSS)` es una variable declarada en el mismo ámbito

2024-01-11 16:37 UTC, jordiSTIC requested changes
Ver comentario en fichero.
Pequeño cambio: No es necesario `isset($skipAntiXSS)` siempre estará declarada.
Por el resto: pruebas realizadas, ya no aparecen los errores comentados.

2024-01-12 16:39 UTC, jordiSTIC approved these changes
(A)Probado

2024-01-16 10:12 UTC, ainaraRT approved these changes
(A)Probado

2024-01-17 08:39 UTC, merged