Feature - Economía - Formularios Web - Integración pasarela CECA
SinergiaTIC/SinergiaCRM pull request #145
Opened 2024-02-28 11:36 UTC by juanSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-03-26 16:59 UTC, jalbaiges requested changes
Ver comentarios sobre nombres y descripciones de los parámetros de configuración.

2024-03-26 16:59 UTC, jalbaiges commented on SticInstall/sql/ca/Settings.sql
> +('572910d4-716b-457d-b66c-4fb54d8e39a5', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_RECAPTCHA_WEBKEY', '', 'Clau per al lloc web proporcionada per Google. Més informació a: https://wikisuite
Parecería razonable que los nombres de los nuevos parámetros de configuración se definieran por analogía con los del TPV de Redsys y, en cualquier caso, manteniendo el estándar: en inglés y con separación de palabras. Ejemplos: 
- TPVCECA_CURRENCY en lugar de TPVCECA_TIPOMONEDA
- TPVCECA_PASSWORD en lugar de TPVCECA_CLAVE_ENCRIPTACION
- TPVCECA_TERMINAL en lugar de TPVCECA_TERMINALID
- etc.

2024-03-27 11:19 UTC, juanSTIC commented on SticInstall/sql/ca/Settings.sql
> +('572910d4-716b-457d-b66c-4fb54d8e39a5', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_RECAPTCHA_WEBKEY', '', 'Clau per al lloc web proporcionada per Google. Més informació a: https://wikisuite
@jalbaiges,   Modificados los nombres de settings y adaptadas las descripciones.
Esta listo para validar en el siguiente fichero y después trasladar los cambios finales al resto de idiomas/ficheros https://github.com/SinergiaTIC/SinergiaCRM/blob/f041357170106b839c2aeb66efa5f2c6177f83af/SticInstall/sql/es/Settings.sql#L43-L49

2024-03-28 11:59 UTC, jalbaiges commented on SticInstall/sql/ca/Settings.sql
> +('572910d4-716b-457d-b66c-4fb54d8e39a5', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_RECAPTCHA_WEBKEY', '', 'Clau per al lloc web proporcionada per Google. Més informació a: https://wikisuite
Revisado el fichero. Los nombres de los settings ya eran correctos. Algunas descripciones se han ajustado para hacerlas coherentes con las del TPV Redsys.

2024-04-01 08:18 UTC, juanSTIC commented on SticInstall/sql/ca/Settings.sql
> +('572910d4-716b-457d-b66c-4fb54d8e39a5', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_RECAPTCHA_WEBKEY', '', 'Clau per al lloc web proporcionada per Google. Més informació a: https://wikisuite
Se han replicado los cambios a los demás ficheros de idioma.

2024-04-02 17:13 UTC, jalbaiges approved these changes
Cadenas revisadas.

2024-04-08 16:16 UTC, ManuSinergiaCRM requested changes
Revisado el código y la funcionalidad, y todo correcto :+1: 

Hago una propuesta para valorar ya que creo que daría claridad a las entidades nuevas, es decir, no lo desplegaría pero sí lo llevaría al código.. Y es que llamemos a las etiquetas del campo Método de Pago: 

- Tarjeta (vía Redsys)
- Tarjeta (vía CECA)

en vez de:

- Tarjeta 
- Tarjeta CECA

Nombro a @Jaume ya que creo que la propuesta la tendrá que validar también él.

2024-04-09 10:59 UTC, ainaraRT approved these changes
(A)Probado

2024-04-10 11:05 UTC, ainaraRT approved these changes
(A)Probado

2024-04-10 15:21 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-04-11 08:18 UTC, merged