Hotfix - General - No mostrar valor incorrecto de una listas desplegable en vista de lista
SinergiaTIC/SinergiaCRM pull request #15
Opened 2024-01-04 14:01 UTC by ManuSinergiaCRM

- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/14

Como si indica en el issue, en este PR se resuelve la incidencia implementando la opción 1 que se propone: Que el valor no se muestre en la vista de lista (se comporta igual que si no tuviera valor por tener un valor incorrecto).

Actualización
- Cuando se implementó esta solución no se atendió al comentario de Jaume por lo que se queda en espera de ver si seguimos con la opción 1 propuesta en el issue o cambiamos a la opción 2 

**Pruebas**

1. Crear más de una organización asignándole un valor en el campo **_Categoría_**  y **subcategoría**.
2. Acceder a la base de datos y cambiar el valor a uno o más de esos campos para que no se corresponda con ninguno de los índices de la lista asociada. 
3. Comprobar que los valores erróneos no se muestran en la vista de lista, en subpaneles y en el dashlet.

2024-07-19 08:26 UTC, enricsinergia submitted a review, later dismissed
Habría que revisar el PR, ya que las pruebas enumeradas indicanjusto lo contrario de lo que dice al final el issue y lo que se ha implementado.

Por otra parte, si no es complicado, estaría bien añadir un estilo tipo tachado o itálica o color a los valores que se recogen directamente de bbdd para hacer evidente que hay algo incorrecto

2024-07-19 10:49 UTC, AlbertoSTIC commented
> 
> Por otra parte, si no es complicado, estaría bien añadir un estilo tipo tachado o itálica o color a los valores que se recogen directamente de bbdd para hacer evidente que hay algo incorrecto

Esto último creo que sería complicado aplicarlo para todas las vistas disponibles. 
Si lo veis relevante, crearía un issue para tratarlo más adelante.

2024-07-19 16:54 UTC, ManuSinergiaCRM commented
> Habría que revisar el PR, ya que las pruebas enumeradas indicanjusto lo contrario de lo que dice al final el issue y lo que se ha implementado.
> 
> Por otra parte, si no es complicado, estaría bien añadir un estilo tipo tachado o itálica o color a los valores que se recogen directamente de bbdd para hacer evidente que hay algo incorrecto

Cambiado la descripción del PR

2024-07-19 16:56 UTC, ManuSinergiaCRM commented
> > Por otra parte, si no es complicado, estaría bien añadir un estilo tipo tachado o itálica o color a los valores que se recogen directamente de bbdd para hacer evidente que hay algo incorrecto
> 
> Esto último creo que sería complicado aplicarlo para todas las vistas disponibles. Si lo veis relevante, crearía un issue para tratarlo más adelante.

He investigado como hacerlo y lo único que he visto complicado es la vista de lista de campos Enum

He creado este PR: https://github.com/SinergiaTIC/SinergiaCRM/issues/308

2024-07-23 07:02 UTC, juanSTIC requested changes
En la vista popup, en un campo multienum, cuando un valor no coincide con ninguna clave se muestra la palabra _Array_
![image](https://github.com/user-attachments/assets/037f91f4-077f-4d58-99aa-6b51f69253fd)

2024-07-23 15:25 UTC, juanSTIC approved these changes
Visto y probado

2024-07-24 07:14 UTC, enricsinergia approved these changes
(A)provado

2024-07-24 07:23 UTC, merged