Improvement - Remesas - Ajuste de validaciones en generación de ficheros
SinergiaTIC/SinergiaCRM pull request #150
Opened 2024-03-04 16:35 UTC by juanSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-03-04 18:47 UTC, jalbaiges requested changes
Cadenas revisadas. A valorar el comentario sobre el tratamiento del nombre de la organización.

2024-03-04 18:47 UTC, jalbaiges commented on modules/stic_Remittances/GenerateSEPACreditTransfers.php
> +    if (strlen($directCreditsVars['GENERAL_ORGANIZATION_NAME']) > 70) {
A valorar si no sería más apropiado truncar directamente el valor disponible en lugar de generar un error (por ejemplo, en la generación del Modelo 182, donde el límite es aún más restrictivo, se hace así: https://github.com/SinergiaTIC/SinergiaCRM/blob/develop/modules/stic_Payments/GenerateModel182.php#L84). El dato se puede utilizar en otros contextos en los que el nombre podría ser usado sin truncar por ausencia de límite de caracteres y la entidad podría usar su nombre completo real en lugar de tener que acortarlo para acomodarlo a usos concretos. En caso de modificarse debería aplicarse también a la remesa de recibos y podría omitirse la necesidad de incorporar la cadena con el mensaje de error.

2024-03-05 07:56 UTC, juanSTIC commented on modules/stic_Remittances/GenerateSEPACreditTransfers.php
> +    if (strlen($directCreditsVars['GENERAL_ORGANIZATION_NAME']) > 70) {
> A valorar si no sería más apropiado truncar directamente el valor disponible en lugar de generar un error...

Se ha modificado el PR en el sentido de la propuesta una vez verificado que hay varias entidades usuarias de SinergiaCRM cuyo nombre excede los 60 caracteres y al menos una con más de 70 caracteres, lo que indica que probablemente esta situación se puede dar en el futuro.

2024-03-05 09:30 UTC, jalbaiges approved these changes

2024-03-07 06:40 UTC, enricsinergia requested changes
Además delpar de comentarios introducidos, veo que el · me lo traduce por M. No he sabido ver exactamente por qué sucede ni cómo debe traducirse realmente mirando las instrucciones de SEPA (https://s1.aebanca.es/wp-content/uploads/2019/07/folleto.-rdenes-en-formato-iso-20022-para-emisin-de-adeudos-directos-sepa-esquema-bsico-versin-noviembre-2019.pdf)

2024-03-07 06:40 UTC, enricsinergia commented on modules/stic_Remittances/GenerateSEPACreditTransfers.php
> +    $directCreditsVars['GENERAL_ORGANIZATION_NAME'] = substr($directCreditsVars['GENERAL_ORGANIZATION_NAME'],0,70);
Debería usarse mb_substr para tratar correctamente los caracteres que pueden estar en el setting y que son caracteres especiales áé....
En la línea 220 ya se hace un mb_substr y un cleantext de este campo. Si se hace el tratamiento aquí, no debería repetirse ahí.

2024-03-07 06:40 UTC, enricsinergia commented on modules/stic_Remittances/GenerateSEPACreditTransfers.php
> +                ->setRemittanceInformation(SticUtils::cleanText(trim(substr($finalConcept, 0, 140))));
Igual que con el nombre de la organización, utilizar mb_substr

2024-03-07 08:07 UTC, juanSTIC commented on modules/stic_Remittances/GenerateSEPACreditTransfers.php
> +    $directCreditsVars['GENERAL_ORGANIZATION_NAME'] = substr($directCreditsVars['GENERAL_ORGANIZATION_NAME'],0,70);
Se ha establecido en esta línea el tratamiento completo (clean, mb_substr y trim) y se ha quitado de las otras en que aparecía

2024-03-07 12:26 UTC, juanSTIC commented on modules/stic_Remittances/GenerateSEPACreditTransfers.php
> +                ->setRemittanceInformation(SticUtils::cleanText(trim(substr($finalConcept, 0, 140))));
cambiado

2024-03-07 12:46 UTC, juanSTIC commented
> Además delpar de comentarios introducidos, veo que el · me lo traduce por M

La conversión se hace en la función cleanText. No se modifica en este PR ya que la fucnión se usa en otros contexto clave como la generación del M182, y por ahora no se está haciendo uso del caracter `·` en producción (que se tenga constancia)

Sobre este punto se ha creado el issue https://github.com/SinergiaTIC/SinergiaCRM/issues/154

2024-03-07 15:04 UTC, enricsinergia approved these changes
(A)provado

2024-03-20 12:47 UTC, ainaraRT approved these changes
(A)Probado

2024-03-21 06:46 UTC, merged