Enhancements - General - Mostrar el nombre del registro en el tooltip de registros recientes y favoritos
SinergiaTIC/SinergiaCRM pull request #151
Opened 2024-03-05 10:03 UTC by juanSTIC

2024-03-05 10:44 UTC, ainaraRT commented
No sé si se quiere que también se muestre el módulo, a parte del nombre. Pero si no se pone encima del nombre, sigue apareciendo el módulo
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/95768967/ecc67bf1-0d03-4c47-99b5-d2f8bcf0a87e)

2024-03-05 11:12 UTC, ainaraRT requested changes
Comentario
> No sé si se quiere que también se muestre el módulo, a parte del nombre. Pero si no se pone encima del nombre, sigue apareciendo el módulo ![image](https://private-user-images.githubusercontent.com/95768967/310084927-ecc67bf1-0d03-4c47-99b5-d2f8bcf0a87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc0MzYsIm5iZiI6MTcwOTYzNzEzNiwicGF0aCI6Ii85NTc2ODk2Ny8zMTAwODQ5MjctZWNjNjdiZjEtMGQwMy00YzQ3LTk5YjUtZDJmOGJjZjBhODdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMjUxMWI2MzI3NGUzMTE3Y2U2MjVhODY1ZWM4N2Y3ZDdhZTEyZDBiNDhhMzkzYzRlNzk4ZTU0MDNhN2U4YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oELIO1oL9Vt1DmmtCy8nftloqRfpsesFUJ0ZMkATrk8)
> 
> Por otra parte, el nombre del elemento se muestra correctamente.

2024-03-07 15:19 UTC, juanSTIC commented
> No sé si se quiere que también se muestre el módulo, a parte del nombre. Pero si no se pone encima del nombre, sigue apareciendo el módulo

La idea es al ponerse encima del icono se muestre el nombre del módulo, y al ponerse encima del texto se muestre el nombre completo del registro.
Lo que sí he corregido, es que, en favoritos, el nombre del módulo se mostraba sin traducir, y ahora ya se muestra traducido.

2024-03-07 16:01 UTC, ainaraRT submitted a review, later dismissed
(A)Probado

2024-03-18 09:05 UTC, PaulaaSTIC approved these changes
(A)probado

2024-03-20 10:52 UTC, ainaraRT approved these changes
(A)Probado

2024-03-21 06:45 UTC, merged

2025-01-08 15:26 UTC, juanSTIC commented
Creado Issue en SA https://github.com/salesagility/SuiteCRM/issues/10606