Training Work Experience and Skills
SinergiaTIC/SinergiaCRM pull request #158
Opened 2024-03-08 17:11 UTC by PaulaaSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-03-18 10:44 UTC, enricsinergia requested changes
Ver comentarios

2024-03-18 10:44 UTC, enricsinergia commented on modules/stic_Work_Experience/metadata/subpanels/default.php
> +        ),
Tanto aquí como en los otros módulos del paquete, no sé si tiene sentido poder "seleccionar" una experiencia, formación o habilidad o sólo tiene sentido el botón de Crear. Si seleccionamos una experiencia de otra persona, la estamos cambiando de persona, la otra persona la pierde y nombre y persona no cuadrarán.

2024-03-18 10:44 UTC, enricsinergia commented on modules/stic_Work_Experience/metadata/listviewdefs.php
> +        'width' => '32%',
La suma de los width con default true supera el 100%

2024-03-18 10:44 UTC, enricsinergia commented on modules/stic_Work_Experience/metadata/searchdefs.php
> +        'basic_search' => array(
El orden de los campos no debería coincidir con la vista de lista? (convención STIC)

2024-03-18 10:44 UTC, enricsinergia commented on modules/stic_Work_Experience/vardefs.php
> +        'name' => array(
Lo mismo que para los otros módulos: required no sería necesario, no required en importación.... y quizás quitarlo de la vista de edición.

2024-03-18 11:38 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_list_strings['stic_skills_language_certificates_list']['catalan_cifalc'] = 'CIFALC - Comissió Interuniversitària de Formació i Acreditació Lingüístiques de Catalunya';
Las listas de certificados deberían tener opción en blanco.

2024-03-18 11:46 UTC, enricsinergia commented
En los addition details de Skills también están fallando los literales de nivel oral y escrito.

2024-03-18 12:07 UTC, enricsinergia commented
Y una última cosa (por el momento). No he podido añadir los módulos a la lista de la búsqueda global: no me aparecen ni como habilitados ni deshabilitados.

2024-03-18 15:33 UTC, PaulaaSTIC commented on modules/stic_Training/Utils.js
> +/* AUX FUNCTIONS */
Esto lo pensamos en el módulo de Ayudas y lo descartamos por si la ayuda era superior al total. Hay becas que cubren un poco más para gastos de material o transporte..

2024-03-18 18:19 UTC, jalbaiges requested changes

2024-03-19 08:41 UTC, PaulaaSTIC commented on modules/stic_Training/vardefs.php
> +        'grant_amount' => array(
Es por llamarse `total_amount`....lo he cambiado a `total` y ahora ambos tienen el mismo tamaño.

2024-03-19 17:10 UTC, PaulaaSTIC commented on modules/stic_Work_Experience/language/en_us.lang.php
> +  'LBL_ASSIGNED_TO_ID' => 'Assigned User Id',
Corregido

2024-03-19 17:15 UTC, PaulaaSTIC commented on custom/Extension/modules/Accounts/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_STIC_TRAINING_ACCOUNTS_FROM_STIC_TRAINING_TITLE'] = 'Formació';
¿Podría ser: "Formaciones impartidas por la organización"?

2024-03-19 17:19 UTC, PaulaaSTIC commented on modules/stic_Training/language/ca_ES.lang.php
> +  'LBL_ACCOUNT' => 'Organització',
Eliminadas

2024-03-19 17:33 UTC, PaulaaSTIC commented on modules/stic_Training/language/ca_ES.lang.php
> +  'LBL_ACCOUNT' => 'Organització',
Eliminadas

2024-03-20 11:00 UTC, javierquilez approved these changes
Realizadas las pruebas indicadas, no se observa ninguna incidencia.

2024-03-20 12:03 UTC, enricsinergia commented on modules/stic_Skills/language/es_ES.lang.php
> +    'LBL_ORAL ' => 'Nivel oral',
Me siguen apareciendo los literales en inglés aunque seleccione castellano o catalán.

2024-03-20 12:12 UTC, enricsinergia commented on modules/stic_Skills/stic_Skills.php
> +               $this->skill;
Sigue sin llenarse el campo skill al seleccionar un idioma, ni se usa el idioma para construir el nombre.
Además me he encontrado que ahora dejaba el nombre vacío. Poniendo el cálculo delnombre delante del parent:save() sí que lo guarda.

2024-03-20 12:32 UTC, enricsinergia commented on modules/stic_Training/metadata/additionalDetails.php
> +        $fields["TOTAL_AMOUNT"] = number_format($fields["TOTAL_AMOUNT"], 2);
Ahora no los formateamos ;-)

Se pueden formatear con format_number($number, $current_user); si no estoy equivocado (current_user debe definirse como global).

2024-03-20 12:33 UTC, enricsinergia commented on modules/stic_Training/Utils.js
> +/* AUX FUNCTIONS */
ok

2024-03-20 12:42 UTC, jalbaiges requested changes
Cadenas revisadas. Dejo un comentario doble relativo al campo _total_.

2024-03-20 12:42 UTC, jalbaiges commented on modules/stic_Training/vardefs.php
> +            'vname' => 'LBL_TEST',
Más allá del tema del nombre del campo que ya se ha indicado en otro comentario, la etiqueta debería encajar con el nombre que finalmente se decida y eso debería reflejarse también en los ficheros de idioma.

2024-03-20 12:42 UTC, jalbaiges commented on modules/stic_Skills/language/es_ES.lang.php
> +    'LBL_ORAL ' => 'Nivel oral',
Los LBL_ de estas cadenas tenían un espacio al final (se puede ver en la "captura de código" previa) que probablemente eran la causa de este funcionamiento anómalo. Pasaba en ca, es y gl, solo en inglés estaban ok, de ahí que se remitiera a ese idioma. Corregido.

2024-03-20 15:48 UTC, jalbaiges submitted a review, later dismissed

2024-03-21 06:51 UTC, enricsinergia approved these changes
(A)provado

2024-03-21 06:53 UTC, AlbertoSTIC approved these changes
Aprobado

2024-03-21 06:53 UTC, AlbertoSTIC approved these changes
Aprobado

2024-03-21 07:05 UTC, AlbertoSTIC approved these changes
Aprobado

2024-03-21 07:37 UTC, enricsinergia approved these changes
(A)provado

2024-03-21 08:00 UTC, merged