Enhancement - Eventos / Sesiones - Añadir campos de Sesión en la generación de sesiones periódicas
SinergiaTIC/SinergiaCRM pull request #16
Opened 2024-01-05 08:24 UTC by AlbertoSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-01-05 12:57 UTC, jalbaiges approved these changes
Cadenas revisadas.

2024-01-08 14:45 UTC, ManuSinergiaCRM requested changes
Ver comentarios

2024-01-08 14:45 UTC, ManuSinergiaCRM commented on modules/stic_Events/tpls/SessionWizard.tpl
> +			$('#activity_type').selectize();
El campo activity_type_row no está cargando la funcionalidad de selectize. Tras añadir el sufijo "_row" hay que hacer algo más ya que una vez cargada la funcionalidad, el campo no se visualiza correctamente

2024-01-08 14:45 UTC, ManuSinergiaCRM commented on modules/stic_Events/tpls/SessionWizard.tpl
> +					$('#session_name').val('');
Añadir el sufijo _row a los dieferentes campos para que se resetee el valor al deshabilitar que se muestren los campos de sesiones

2024-01-15 16:31 UTC, AlbertoSTIC commented on modules/stic_Events/tpls/SessionWizard.tpl
> +			$('#activity_type').selectize();
A mí si que me funciona correctamente. el elemento con el sufijo "_row" es el contenedor que contiene "etiqueta + campo". El campo a selectizar tiene id "activity_type". Así que, en principio, como está ahora es correcto.

2024-01-15 16:32 UTC, AlbertoSTIC commented on modules/stic_Events/tpls/SessionWizard.tpl
> +					$('#session_name').val('');
Los campos no tienen el sufijo "_row", eso son los contenedores. En mis pruebas actualmente el campo se vacía correctamente. Quizás te falta vaciar la caché del navegador.

2024-01-15 17:09 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-01-17 16:55 UTC, ainaraRT approved these changes
(A)Probado

2024-01-18 09:03 UTC, merged