Feature - General - Permitir personalizar las consultas de verificación de duplicados
SinergiaTIC/SinergiaCRM pull request #164
Opened 2024-03-12 19:07 UTC by jordiSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-03-15 08:32 UTC, enricsinergia requested changes
Primera revisió de codi parcial.

2024-03-15 08:32 UTC, enricsinergia commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +class ContactsDuplicateQueries{
Enlloc de ContactsDuplicateQueries, mentre no estigui al core de SuiteCRM els hi diria sticContactsDuplicateQueries i afegiria el stic als fitxers. Motiu: que es vegi que són nostres, com amb els fitxers de logic hooks, etc.

2024-03-15 08:32 UTC, enricsinergia commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +                return customContactsDuplicateQueries::getDuplicateQuery($focus, $prefix);
Hauria de ser $bean.

2024-03-15 08:32 UTC, enricsinergia commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +            $query .= " (contacts.first_name LIKE '". $firstName . "%' AND contacts.last_name = '". $lastName ."')";
Jo aprofitaria que la personalitzem per fer que el last_name també tingués un LIKE i un % com el first_name.

2024-03-15 08:32 UTC, enricsinergia commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +            $query .= " contacts.last_name = '". $lastName ."'";
ídem línia 61

2024-03-15 08:32 UTC, enricsinergia commented on custom/modules/Leads/LeadsDuplicateQueries.php
> +class LeadsDuplicateQueries{
Mateixos comentaris que per Contacts

2024-03-15 08:32 UTC, enricsinergia commented on modules/Accounts/AccountFormBase.php
> +                $query = AccountsDuplicateQueries::getDuplicateQuery($focus, $prefix);
Trobo a faltar el fitxer custom, cercant Accounts per identification_number

2024-03-15 08:32 UTC, enricsinergia commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +                return customContactsDuplicateQueries::getShowDuplicateQuery($focus, $prefix);
Aquest $focus i $prefix, d'on surt?

2024-03-15 11:28 UTC, jordiSTIC commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +class ContactsDuplicateQueries{
Canviat el nom dels fitxers i les classes: `sticContactsDuplicateQueries` i `customsticContactsDuplicateQueries` per exemple

2024-03-15 11:28 UTC, jordiSTIC commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +                return customContactsDuplicateQueries::getDuplicateQuery($focus, $prefix);
Corregit :+1:

2024-03-15 11:29 UTC, jordiSTIC commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +            $query .= " (contacts.first_name LIKE '". $firstName . "%' AND contacts.last_name = '". $lastName ."')";
Afegit % al last_name, tant de Contacts com de Leads

2024-03-15 11:29 UTC, jordiSTIC commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +            $query .= " contacts.last_name = '". $lastName ."'";
Afegit % al last_name, tant de Contacts com de Leads

2024-03-15 11:30 UTC, jordiSTIC commented on custom/modules/Leads/LeadsDuplicateQueries.php
> +class LeadsDuplicateQueries{
Realitzades les modificacions tant a Contacts com Leads. Corregides les consultes amb errors a Leads

2024-03-15 11:31 UTC, jordiSTIC commented on custom/modules/Contacts/ContactsDuplicateQueries.php
> +                return customContactsDuplicateQueries::getShowDuplicateQuery($focus, $prefix);
Corregit

2024-03-15 12:54 UTC, enricsinergia approved these changes
(A)provado

2024-03-20 12:40 UTC, ManuSinergiaCRM requested changes
Ver comentarios de la revisión

2024-03-20 12:40 UTC, ManuSinergiaCRM commented on modules/Opportunities/OpportunityFormBase.php
> +        if(file_exists("custom/modules/Opportunities/sticOpportunitiesDuplicateQueries.php")) {
La funcionalidad de búsqueda de duplicados al crear una oportunidad no está aplicando. En modo debug y en ninguno de los casos que he probado, incluyendo el caso de duplicar una oportunidad ya existente, se para en este código ni se muestra nada relacionado en la interfaz. 

Propongo no aplicar esta mejora a este módulo y como mucho crear un issue.

2024-03-20 12:40 UTC, ManuSinergiaCRM commented on modules/Prospects/ProspectFormBase.php
> +        if(file_exists("custom/modules/Prospects/sticProspectsDuplicateQueries.php")) {
La funcionalidad de búsqueda de duplicados al crear un registro no está aplicando. En modo debug y en ninguno de los casos que he probado, incluyendo el caso de duplicar un registro ya existente, se para en este código ni se muestra nada relacionado en la interfaz. 

Propongo no aplicar esta mejora a este módulo y como mucho crear un issue.

2024-03-20 12:53 UTC, jordiSTIC commented on custom/modules/Accounts/sticAccountsDuplicateQueries.php
> +        if(file_exists("custom/modules/Leads/customAccountsDuplicateQueries.php")) {
Corregido

2024-03-20 12:54 UTC, jordiSTIC commented on custom/modules/Accounts/sticAccountsDuplicateQueries.php
> +            require_once("custom/modules/Leads/customAccountsDuplicateQueries.php");
Corregido

2024-03-20 12:55 UTC, jordiSTIC commented on modules/Opportunities/OpportunityFormBase.php
> +        if(file_exists("custom/modules/Opportunities/sticOpportunitiesDuplicateQueries.php")) {
Se han eliminado las adaptaciones de los módulos Opportunities y Prospects

2024-03-20 12:56 UTC, jordiSTIC commented on modules/Prospects/ProspectFormBase.php
> +        if(file_exists("custom/modules/Prospects/sticProspectsDuplicateQueries.php")) {
Se han eliminado las adaptaciones de los módulos Opportunities y Prospects

2024-03-20 13:05 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-03-20 14:31 UTC, enricsinergia approved these changes
(A)provado

2024-03-21 06:46 UTC, merged