Feature - SMS - Integración inicial del plugin de Seven para el envío de SMS
SinergiaTIC/SinergiaCRM pull request #182
Opened 2024-04-02 05:51 UTC by enricsinergia

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-09-02 07:22 UTC, PaulaaSTIC requested changes

2024-09-04 10:36 UTC, AlbertoSTIC commented on custom/Extension/modules/Contacts/Ext/Vardefs/SticVardefs.php
> +$dictionary['Contact']['fields']['seven_compose_sms']['inline_edit'] = '0';
Ídem

2024-09-04 10:36 UTC, AlbertoSTIC commented on custom/Extension/modules/Employees/Ext/Vardefs/SticVardefs.php
> +$dictionary['Employee']['fields']['seven_compose_sms']['inline_edit'] = '0';
Ídem

2024-09-04 10:36 UTC, AlbertoSTIC commented on custom/Extension/modules/Leads/Ext/Vardefs/SticVardefs.php
> +$dictionary['Lead']['fields']['seven_compose_sms']['inline_edit'] = '0';
Ídem

2024-09-04 10:37 UTC, AlbertoSTIC commented on custom/include/generic/SugarWidgets/SugarWidgetSubPanelEditMessagesButton.php
Limpiamos el fichero del código que no se utilice.

2024-09-04 10:40 UTC, AlbertoSTIC commented on custom/modules/EmailTemplates/DetailView.php
> +echo "<script type='text/javascript' language='JavaScript' src='custom/modules/EmailTemplates/SticUtils.js'> </script>";
Mejor añadimos cualquier fichero JS con la función getVersionedScript().

2024-09-04 10:41 UTC, AlbertoSTIC commented on modules/Accounts/views/view.detail.php
> +
Si no tiene otra modificación este fichero, quitamos esta línea.

2024-09-04 10:42 UTC, AlbertoSTIC commented on modules/Employees/views/view.detail.php
Ídem. Si no modificamos el fichero, quitamos las modificaciones de línea y formatos.

2024-09-04 10:45 UTC, AlbertoSTIC commented on modules/stic_Messages/include/ComposeView/ComposeView.php
> +class ComposeView extends EditView
La clase EditView está deprecated. ¿No serviría utilizar la clase EditView2?

2024-09-04 10:50 UTC, AlbertoSTIC commented on modules/stic_Messages/controller.php
> +    public function action_Save() {
Cuando se ejecuta esta función? Hay que tener en cuenta que las acciones Save no se ejecutan en todos los contextos. Por ejemplo, no se ejecuta en un LH o con la API. Para ese caso se utiliza la función save() del bean.

2024-09-04 10:52 UTC, AlbertoSTIC requested changes
Ver comentarios.

También faltaría la licencia de SinergiaCRM en algunos ficheros y añadir el trozo de la licencia de SinergiaCRM en los ficheros modificados que tienen la licencia de SugarCRM-SuiteCRM.

2024-09-07 15:50 UTC, enricsinergia commented on modules/stic_Messages/controller.php
> +    public function action_Save() {
Está función está sobre-escrita para el caso de los mass updates, en este caso el envío masivo de SMS desde una vista de lista.

2024-09-09 05:11 UTC, enricsinergia commented on SticInclude/functionUtils.php
> +<?php
Función movida a Utils.php dentro de stic_Messages.
El tema de las licencias, está como punto pendiente para realizar al final.

2024-09-09 05:14 UTC, enricsinergia commented on SticUpdates/Migrations/ca/20240730_feature_sms.sql
> +INSERT INTO `stic_settings` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `deleted`, `assigned_user_id`, `type`, `name`, `value`, `description`) VALUES
Cambiado

2024-09-09 05:15 UTC, enricsinergia commented on custom/Extension/modules/AOW_Actions/Ext/Language/ca_ES.sevenlang.php
> +<?php
Eliminados. Estaba pendiente todoel cambio de la nueva acción de Flujos de Trabajo.

2024-09-09 05:17 UTC, enricsinergia commented on custom/Extension/modules/Accounts/Ext/Vardefs/SticVardefs.php
> +$dictionary['Account']['fields']['seven_compose_sms']['inline_edit'] = '0';
Eliminado. He añadido una tarea para repasar todas las apariciones de "SEVEN".

2024-09-09 05:17 UTC, enricsinergia commented on custom/Extension/modules/Contacts/Ext/Vardefs/SticVardefs.php
> +$dictionary['Contact']['fields']['seven_compose_sms']['inline_edit'] = '0';
ídem ;-)

2024-09-09 05:18 UTC, enricsinergia commented on custom/Extension/modules/Employees/Ext/Vardefs/SticVardefs.php
> +$dictionary['Employee']['fields']['seven_compose_sms']['inline_edit'] = '0';
Elininado.

2024-09-09 05:18 UTC, enricsinergia commented on custom/Extension/modules/Leads/Ext/Vardefs/SticVardefs.php
> +$dictionary['Lead']['fields']['seven_compose_sms']['inline_edit'] = '0';
Eliminado

2024-09-09 05:21 UTC, enricsinergia commented on custom/include/generic/SugarWidgets/SugarWidgetSubPanelEditMessagesButton.php
Hay frangementos de código comentados pendientes de limpiar al final. Normalmente corresponden a código procedente del código base utilizado que se ha cambiado por otra forma de hacer. No se ha eliinado todavía por si hay que revertir los cambios.

2024-09-09 05:24 UTC, enricsinergia commented on custom/modules/EmailTemplates/DetailView.php
> +echo "<script type='text/javascript' language='JavaScript' src='custom/modules/EmailTemplates/SticUtils.js'> </script>";
Cambiado

2024-09-09 05:25 UTC, enricsinergia commented on modules/Accounts/views/view.detail.php
> +
Hecho

2024-09-09 08:18 UTC, enricsinergia commented on modules/Employees/views/view.detail.php
Hecho

2024-09-09 08:22 UTC, enricsinergia commented on modules/stic_Messages/include/ComposeView/ComposeView.php
> +class ComposeView extends EditView
De hecho ya se está usando. Es un error del inteliphense. Si te fijas, el require ya coge la EditView2, lo que pasa es que se define igualemnte una clase llamada EditView (no existe una clase EditView2).

2024-09-27 11:34 UTC, AlbertoSTIC requested changes
Ver comentarios.

2024-09-27 11:34 UTC, AlbertoSTIC commented on custom/Extension/modules/AOW_Actions/Ext/Actions/createMessage.php
¿CreateMessage o SendMessage?

2024-09-27 11:34 UTC, AlbertoSTIC commented on custom/Extension/modules/AOW_Actions/Ext/Language/ca_ES.sticlang.php
El nombre de fichero es incorrecto. ca_ES.SticLang.php

2024-09-27 11:34 UTC, AlbertoSTIC commented on custom/modules/Accounts/views/view.detail.php
> +    use Checkstic_Messages;
Entiendo que las "trait" se utilizan para darle más características a la clase que los usa. En este sentido, yo creo que la función "echoIsMessagesModuleActive" no es una caracteristica del objeto "ViewDetail".
Por otro lado, creo que el nombre de la función tampoco encaja con lo que hace. Ya que no solo comprueba si el módulo está activo o no, sino otros temas aún más importantes.
Yo le daría una vuelta a este tema. Tenemos otros módulos que también muestran botones en Accounts y en otros (como por ejemplo los botones PDF, Incorpora) y estaría bien establecer un estandar para poder aplicarlo en todos los casos donde toque. 
Si nos parece que con lo que hacemos con Incorpora no nos convence, revisemos lo que ya hace SuiteCRM o hagamos una propuesta consistente.

2024-09-27 11:34 UTC, AlbertoSTIC commented on custom/modules/Accounts/views/view.list.php
> +    use Checkstic_Messages;
Ídem.

2024-09-27 11:34 UTC, AlbertoSTIC commented on custom/modules/EmailTemplates/SticUtils.js
> +debugger;
debugger

2024-09-27 11:34 UTC, AlbertoSTIC commented on modules/Employees/views/view.detail.php
> +
No es necesaria.

2024-09-27 11:34 UTC, AlbertoSTIC commented on modules/stic_Messages/controller.php
> +        }
Entiendo que este código no es necesario.

2024-09-27 11:34 UTC, AlbertoSTIC commented on modules/stic_Messages/Helpers/SevenSmsHelper.php
> +    public function getActive(): bool {
Si las funciones de set, get, apiCall, solo se utilizan en esta clase, se podrían poner a privadas.

2024-09-27 11:34 UTC, AlbertoSTIC requested changes
Ver comentarios.

2024-09-27 13:58 UTC, enricsinergia reviewed
> ¿CreateMessage o SendMessage? 

Puedes crear un mensaje y dejarlo como Draft

2024-09-27 14:01 UTC, enricsinergia commented on custom/Extension/modules/AOW_Actions/Ext/Actions/createMessage.php
Puedes crear un mensaje en draft, de ahí que no le llamase Send.

2024-09-27 14:03 UTC, enricsinergia commented on custom/Extension/modules/AOW_Actions/Ext/Language/ca_ES.sticlang.php
Corregido

2024-09-27 14:14 UTC, enricsinergia commented on custom/modules/Accounts/views/view.detail.php
> +    use Checkstic_Messages;
Cuando creé el trait, estaba usando alguna variable de la clase para poder hacer lo que hace, y por eso necesitaba que fuera un trait y no podía ser una función de Utils. Tal como está ahora, puede incorporarse a Utils y denominarla algo como "includeMessagesJS".
Respecto a lo que hace Incorpora y los botones que se muestran en otros módulos, no he visto que pueda ocultarse la opción de sincronización con Incorpora, cómo sí queremos que suceda con el caso de los mensajes: si el módulo de mensajes no está activo no queremos que la acción aparezca. Por eso no podemos incluirlo directamente en el js de los módulos como se hace con Incorpora u otros módulos. 
Otra diferencia clave con Incorpora es que añadimos el icono al lado de cada teléfono, lo cual obliga a insertar un código JS en esos casos....que también sólo queremos que aparezca el icono si hay módulo de mensajes activo.

2024-09-27 14:17 UTC, enricsinergia commented on custom/modules/EmailTemplates/SticUtils.js
> +debugger;
Eliminados

2024-09-27 14:32 UTC, enricsinergia commented on modules/Employees/views/view.detail.php
> +
Fichero revertido.

2024-10-03 13:42 UTC, enricsinergia commented on modules/stic_Messages/controller.php
> +        }
Eliminado

2024-10-03 13:44 UTC, enricsinergia commented on modules/stic_Messages/Helpers/SevenSmsHelper.php
> +    public function getActive(): bool {
Cambiado

2024-10-15 09:07 UTC, AlbertoSTIC commented on custom/modules/Accounts/views/view.detail.php
> +    use Checkstic_Messages;
Lo añadiría al Utils.php entonces.

2024-10-18 04:53 UTC, enricsinergia commented on custom/modules/Accounts/views/view.detail.php
> +    use Checkstic_Messages;
Hecho

2024-10-25 10:40 UTC, AlbertoSTIC requested changes

2024-10-25 10:40 UTC, AlbertoSTIC commented on SticInclude/js/Utils.js
> +  } else if ($(".detail-view").length == 1 || $("form[name=DetailView]").length == 1) {
¿En que casos se ha detectado que se debería ampliar la condición para la vista de detalle? Estas condiciones se llevan utilizando así desde hace tiempo en diferentes procesos y no hasta ahora no ha sido necesario.

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/Extension/modules/AOW_Actions/Ext/Actions/createMessage.php
Diría de seguir el mismo patrón que la acción de Emails, que se llama "sendEmail".
Si se quiere crear un mensaje en draft, se puede hacer desde la acción de crear registro.

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Accounts/views/view.detail.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
¿Ya no es necesario?

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Accounts/views/view.list.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Contacts/views/view.detail.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Contacts/views/view.list.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Employees/views/view.detail.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Employees/views/view.list.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Leads/views/view.detail.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on custom/modules/Leads/views/view.list.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-25 10:40 UTC, AlbertoSTIC commented on modules/stic_Messages/Utils.php
Faltarían comentarios en las funciones que son susceptibles de ser usadas en procesos externos.

2024-10-25 10:41 UTC, AlbertoSTIC requested changes
Revisado el código

2024-10-30 16:55 UTC, enricsinergia commented on SticInclude/js/Utils.js
> +  } else if ($(".detail-view").length == 1 || $("form[name=DetailView]").length == 1) {
Si no me equivoco es en EmailTemplates. La vista detail se construye sin tpl y no sigue el estándar habitual.

2024-10-31 05:57 UTC, enricsinergia commented on custom/modules/Accounts/views/view.detail.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
La acción ya ha sido renombrada. Igualmente mantengo la opción de cambiar el estado y que no sea Sent, ya que creando el registro con la acción de "Crear registro" no tienes el mismo juego de destinatarios que te permite la acción específica.

En cuanto al Checstic_Messages ya está eliminada toda traza. Me quedaron colgados estos require y ya se corrigió hace unos días.

2024-10-31 05:57 UTC, enricsinergia commented on custom/modules/Accounts/views/view.list.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-31 05:57 UTC, enricsinergia commented on custom/modules/Contacts/views/view.detail.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-31 05:58 UTC, enricsinergia commented on custom/modules/Contacts/views/view.list.php
> +require_once 'modules/stic_Messages/Checkstic_Messages.php';
Ídem

2024-10-31 06:24 UTC, enricsinergia commented on modules/stic_Messages/Utils.php
Hecho

2024-11-05 13:20 UTC, PaulaaSTIC requested changes
Validando, he visto algunos comentarios sobre las distintas pruebas a realizar:

3. Aunque el módulo esté inhabilitado, aparece el icono, pero no la opción en la vista de detalle ni en la lista; solo se muestra el icono.

7.Dentro de la ventana de mensaje, al seleccionar una plantilla de email, pueden aparecer etiquetas sin convertir. Quizá se podrían filtrar las plantillas para mostrar solo las de SMS.

10. Con un FdT, se puede cambiar el estado de un SMS. Además, me sucede lo siguiente: si cambio un SMS de "Enviado" a "Error" por medio de un FdT, aunque luego intente enviarlo en la vista de lista de Mensajes, el estado no se actualiza y se queda en "Error".

12. En los FdT, la opción de elegir "para quién" en el campo de teléfono no funciona. Tampoco se puede seleccionar una plantilla de SMS (aparece como plantilla de email, pero sale en blanco). Los emails sí funcionan.

2024-11-11 11:49 UTC, enricsinergia commented
> Validando, he visto algunos comentarios sobre las distintas pruebas a realizar:
> 
> 3. Aunque el módulo esté inhabilitado, aparece el icono, pero no la opción en la vista de detalle ni en la lista; solo se muestra el icono.
Resuelto

> 
> 7.Dentro de la ventana de mensaje, al seleccionar una plantilla de email, pueden aparecer etiquetas sin convertir. Quizá se podrían filtrar las plantillas para mostrar solo las de SMS.
Añadido filtro en la ventana de pop-up.

> 
> 10. Con un FdT, se puede cambiar el estado de un SMS. Además, me sucede lo siguiente: si cambio un SMS de "Enviado" a "Error" por medio de un FdT, aunque luego intente enviarlo en la vista de lista de Mensajes, el estado no se actualiza y se queda en "Error".
No me ha pasado. Puede ser que cuando hacías el retry también se te estuviera lanzando el FdT que cambia el estado y por eso siguiera como en error?


> 11. En los FdT, la opción de elegir "para quién" en el campo de teléfono no funciona. Tampoco se puede seleccionar una plantilla de SMS (aparece como plantilla de email, pero sale en blanco). Los emails sí funcionan.
Resuelto. Se había renombrado la acción del FdT y la invocación del fichero JS todavía tenía el nombre viejo.

2025-06-10 13:48 UTC, AlbertoSTIC requested changes
Revisar comentarios

2025-06-10 13:48 UTC, AlbertoSTIC commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> +$app_list_strings['stic_messages_type_list']['SevenSmsHelper'] = 'SMS';
¿El nombre interno de la lista con mayúsculas o mejor con "_"?

2025-06-10 13:48 UTC, AlbertoSTIC commented on custom/Extension/modules/AOW_Actions/Ext/Actions/sendMessage.php
Ya que es un ficheros stic en custom, lo llamamos SticActions.php o SticAowActions.php, o algo parecido.

2025-06-10 13:48 UTC, AlbertoSTIC commented on custom/Extension/modules/AOW_Actions/Ext/Language/ca_ES.Sticlang.php
> +];
Las etiquetas en los ficheros de Extension, y potencialmente en otros lugares, siempre las declaramos una a una. 
Si lo hacemos de esta manera, estaremos sobreescribiendo la variable $mod_string que pueda estar definida en otro lugar.

2025-06-10 13:48 UTC, AlbertoSTIC commented on custom/modules/AOW_Actions/actions/actionSendMessage.php
> +    public function edit_display($line, SugarBean $bean = null, $params = array())
¿Puede ser que la declaración de parámetro con SugarBean está deprecada? VScode me lo muestra como tal.

2025-06-10 13:48 UTC, AlbertoSTIC commented on modules/stic_Messages/Helpers/SevenSmsHelper.php
> +        curl_close($curl);
Para valorar: 
¿A parte de gestionar los posibles errores de esta petición con la variable $response que se devuelve, no se debería también comprobar los errores en la petición de curl? 

He buscado en el resto de código de SuiteCRM y parece que en algunos casos se utilizan las funciones curl_errno() o curl_error(), pero no en todos los casos.

2025-06-10 13:48 UTC, AlbertoSTIC commented on SticRepair.php
Este fichero no es necesario.

2025-06-10 13:53 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> +$app_list_strings['stic_messages_type_list']['SevenSmsHelper'] = 'SMS';
En este caso es porqué cada tipo de mensaje que se añade, lleva el nombre de la clase responsable en el campo clave, es decir, no es un valor cualquiera si no el nombre de la clase que implementa la interficie para el envío de SMS.

2025-06-10 13:59 UTC, enricsinergia commented on custom/Extension/modules/AOW_Actions/Ext/Language/ca_ES.Sticlang.php
> +];
Cambiado.

2025-06-10 14:03 UTC, enricsinergia commented on custom/modules/AOW_Actions/actions/actionSendMessage.php
> +    public function edit_display($line, SugarBean $bean = null, $params = array())
Faltaba el ? delante del tipo para indicar que puede ser null, no necesario hasta PHP 8

2025-06-10 14:10 UTC, enricsinergia commented on SticRepair.php
Eliminado

2025-06-11 09:56 UTC, jalbaiges commented on SticInstall/sql/ca/Settings.sql
> +('c8d720bd-2c7b-47a6-98ce-9664529559ca', NOW(), NOW(), '1', '1', 0, '1', 'MESSAGES', 'MESSAGES_SENDER', '', 'Nom que apareixerà com a remitent en els missatges enviats.'),
¿Los parámetros de tipo MESSAGES aplican específicamente al envío de SMS o tendrán otras aplicaciones?

2025-06-12 13:59 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_strings['LBL_SUBPANEL_NEW_MESSAGE_TITLE'] = 'Nou Missatge';
¿Seguro que estas cadenas tienen que ir en el fichero global y no en el del módulo donde apliquen (aunque sea en más de uno)?

2025-06-12 21:19 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> -$app_list_strings['record_type_display_notes']['stic_Group_Opportunities'] = 'Granted accounts';
Esta línea parece haber sido borrada indebidamente.

2025-06-12 21:19 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> -$app_list_strings['parent_type_display_notifications']['Opportunities'] = 'Opportunities';
Esta línea parece haber sido borrada indebidamente.

2025-06-12 21:19 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> -$app_list_strings['vat_list']['21'] = '21%';
Esta línea parece haber sido borrada indebidamente.

2025-06-12 21:31 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> -$app_list_strings['record_type_display_notes']['Contacts'] = 'Personas';
Esta línea parece haber sido borrada indebidamente.

2025-06-12 21:31 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> -$app_list_strings['record_type_display']['stic_Group_Opportunities'] = 'Organizaciones subvencionadas';
Esta línea parece haber sido borrada indebidamente.

2025-06-12 21:35 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/gl_ES.SticLang.php
> -$app_list_strings['record_type_display']['stic_Group_Opportunities'] = 'Organizaciones subvencionadas';
Esta línea parece haber sido borrada indebidamente.

2025-06-12 21:35 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/gl_ES.SticLang.php
> -$app_list_strings['record_type_display_notes']['Contacts'] = 'Persoas';
Esta línea parece haber sido borrada indebidamente.

2025-07-01 09:35 UTC, enricsinergia commented on SticInstall/sql/ca/Settings.sql
> +('c8d720bd-2c7b-47a6-98ce-9664529559ca', NOW(), NOW(), '1', '1', 0, '1', 'MESSAGES', 'MESSAGES_SENDER', '', 'Nom que apareixerà com a remitent en els missatges enviats.'),
Aplican a cualquier método que se añada para enviar mensajes. La idea es aprovechar estos mensajes para poder enviar también a través de Whatsapp. También se prevé que alguna entidad pueda decidir no usar el proveedor de SMS escogido y crearse su propio "helper" para enviar SMS. Por ello se han separado los parámetros que afectan a toda la operativa de mensajes y los que son específicos de Seven.

2025-07-01 09:38 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> -$app_list_strings['record_type_display_notes']['stic_Group_Opportunities'] = 'Granted accounts';
Corregido

2025-07-01 09:39 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> -$app_list_strings['parent_type_display_notifications']['Opportunities'] = 'Opportunities';
Corregido

2025-07-01 09:39 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/en_us.SticLang.php
> -$app_list_strings['vat_list']['21'] = '21%';
Corregido

2025-07-01 09:41 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> -$app_list_strings['record_type_display']['stic_Group_Opportunities'] = 'Organizaciones subvencionadas';
corregido

2025-07-01 09:41 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/gl_ES.SticLang.php
> -$app_list_strings['record_type_display']['stic_Group_Opportunities'] = 'Organizaciones subvencionadas';
corregido

2025-07-01 10:17 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/es_ES.SticLang.php
> -$app_list_strings['record_type_display_notes']['Contacts'] = 'Personas';
corregido

2025-07-01 10:22 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_strings['LBL_SUBPANEL_NEW_MESSAGE_TITLE'] = 'Nou Missatge';
Estos literales se usan en un nuevo Widget creado para ofrecer la creación de mensajes desde los subpaneles de Personas, Organizaciones, etc. Al utilizarse en un widget y éste no entender de módulos, los literales deben estar en el genérico.

2025-07-01 10:31 UTC, enricsinergia commented on custom/Extension/application/Ext/Language/gl_ES.SticLang.php
> -$app_list_strings['record_type_display_notes']['Contacts'] = 'Persoas';
corregido

2025-07-01 11:45 UTC, jalbaiges submitted a review, later dismissed
Ver repregunta en el contexto de los settings.

2025-07-01 11:45 UTC, jalbaiges commented on SticInstall/sql/ca/Settings.sql
> +('c8d720bd-2c7b-47a6-98ce-9664529559ca', NOW(), NOW(), '1', '1', 0, '1', 'MESSAGES', 'MESSAGES_SENDER', '', 'Nom que apareixerà com a remitent en els missatges enviats.'),
Entonces, por ejemplo, ¿el parámetro MESSAGES_LIMIT no debería estar vinculado al proveedor o al mecanismo de envío en lugar de ser genérico? Es probable que los límites que pueda establecer Whatsapp no coincidan con los de Seven, sin ir más lejos.

2025-07-31 08:28 UTC, enricsinergia commented
@jalbaiges 
Respecto la repregunta https://github.com/SinergiaTIC/SinergiaCRM/pull/182#discussion_r2177260084 i pregunta original https://github.com/SinergiaTIC/SinergiaCRM/pull/182#issuecomment-3139026081

El límite se aplica en la propia vista de lista, dónde todavía no se conoce el proveedor de envío. Es un límite "artificial" para evitar que se use la acción masiva para lo que debería usarse una campaña (Mecanismo desarrollado en otro PR paralelo).
A pesar de ser un envío "masivo", se hacen uno a uno, ya que el texto del mensaje puede estar personalizado para el destinatario, con lo que no se usan mecanismos masivos del proveedor

2025-08-05 10:33 UTC, PaulaaSTIC requested changes
Algunos comentarios en el código

2025-08-05 10:33 UTC, PaulaaSTIC commented on modules/stic_Messages/Dashlets/stic_TrainingDashlet/stic_MessagesDashlet.php
> +<?php
Cambiar el nombre de la carpeta

2025-08-05 10:33 UTC, PaulaaSTIC commented on modules/stic_Messages/metadata/additionalDetails.php
> +function additionalDetailsstic_Messages($fields, SugarBean $bean = null, $params = array())
Cambiar por: `function additionalDetailsstic_Messages($fields, ?SugarBean $bean = null, $params = array())`

2025-08-05 10:33 UTC, PaulaaSTIC commented on modules/stic_Messages/metadata/additionalDetails.php
> +        $fields['GRANT_AMOUNT'] = empty($fields['GRANT_AMOUNT'])? $fields['GRANT_AMOUNT'] : format_number($fields['GRANT_AMOUNT'], $current_user);
Creo que esto sobra, estos elementos no existen en este `$fields`.

2025-08-05 15:59 UTC, PaulaaSTIC commented on modules/stic_Messages/views/view.compose.php
> +	    $this->bean->parent_id = $_REQUEST['relatedId'];
Desde actualización masiva se produce un `Warning: Undefined array key "relatedId"` quizá podriamos sustituir la línea por  `$this->bean->parent_id = $_REQUEST['relatedId'] ??  $_REQUEST['ids'] ; `

2025-08-27 09:35 UTC, enricsinergia commented on modules/stic_Messages/Dashlets/stic_TrainingDashlet/stic_MessagesDashlet.php
> +<?php
Hecho

2025-08-27 09:35 UTC, enricsinergia commented on modules/stic_Messages/metadata/additionalDetails.php
> +function additionalDetailsstic_Messages($fields, SugarBean $bean = null, $params = array())
Hecho

2025-08-27 09:35 UTC, enricsinergia commented on modules/stic_Messages/metadata/additionalDetails.php
> +        $fields['GRANT_AMOUNT'] = empty($fields['GRANT_AMOUNT'])? $fields['GRANT_AMOUNT'] : format_number($fields['GRANT_AMOUNT'], $current_user);
Eliminados

2025-08-27 09:37 UTC, enricsinergia commented on modules/stic_Messages/views/view.compose.php
> +	    $this->bean->parent_id = $_REQUEST['relatedId'];
He preferido dejarlo como $this->bean->parent_id = $_REQUEST['relatedId'] ?? null; ya que tener ahí una lista de ids no me gusta. Sí se ha añadido el ?? para evitar el warning.

2025-08-28 12:10 UTC, PaulaaSTIC commented on modules/stic_Messages/views/view.compose.php
> +	    $this->bean->parent_id = $_REQUEST['relatedId'];
Desde la vista de edición de un nuevo mensaje se produce el mismo `Warning: Undefined array key "relatedModule" in /application/sinergiacrm/modules/stic_Messages/views/view.compose.php on line 71`

2025-09-26 20:49 UTC, jalbaiges commented on modules/stic_Messages/language/ca_ES.lang.php
> +  'LBL_MASS_RETRY_MESSAGE_BUTTON_TITTLE' => "Realitza l'enviament",
La etiqueta LBL_MASS_RETRY_MESSAGE_BUTTON_TITTLE ha sido cambiada recientemente y ahora contiene el valor _Realizar envío_, que parece un tanto forzado pudiendo decir _Enviar_. Salvo que exista alguna razón para usar esta perífrasis, sugeriría simplificarla.

2025-09-29 13:54 UTC, jordiSTIC submitted a review, later dismissed
Probado y revisado.
Muy buen trabajo.

Diseño robusto y ampliable a futuras integraciones con otros sistemas de mensajería móvil 👌

2025-09-30 07:14 UTC, jordiSTIC submitted a review, later dismissed
(A)Probado

2025-09-30 20:47 UTC, AlbertoSTIC approved these changes
Aprobado

2025-10-01 07:50 UTC, merged