Enhancement - General - Permitir selección de estilo del sidebar
SinergiaTIC/SinergiaCRM pull request #193
Opened 2024-04-11 08:12 UTC by PaulaaSTIC

## Description

## Motivation and Context

## How To Test This

2024-04-18 18:05 UTC, jalbaiges requested changes
Ver comentarios.

2024-04-18 18:05 UTC, jalbaiges commented on SticInstall/sql/ca/Settings.sql
> +('a649b1ca-4ada-e40f-5e47-660fc8e8d7cb', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_CUSTOM_SIDEBAR_COLOR', '1', 'Permet canviar el color del subtema de SinergiaCRM.\r\n0 -  Subtema clar\r\n1
Si insertamos la fila en este punto para que todos los parámetros del mismo tipo queden juntos, entonces lo suyo sería llevarse los cuatro de tipo GENERAL de este bloque (3 de reCaptcha y el Sidebar color) a la parte superior del fichero, donde ya hay otros de este mismo tipo.

2024-04-18 18:05 UTC, jalbaiges commented on SticInstall/sql/en/Settings.sql
> +('a649b1ca-4ada-e40f-5e47-660fc8e8d7cb', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_CUSTOM_SIDEBAR_COLOR', '1', 'Sets the sidebar color.\r\n0 -  Light subtheme\r\n1 - Dark subtheme.\r\nOnce
En los idiomas CA y ES se hace referencia al subtema. En inglés, a la barra lateral. Debería unificarse en un u otro sentido.

2024-04-19 08:31 UTC, PaulaaSTIC commented on SticUpdates/Migrations/en/20240412_feature_SticCustomSidebarColor.sql
Sí, pero en el último despliegue, al realizar pruebas, surgieron problemas debido a una configuración que faltaba en algunas de nuestras instancias que están en inglés. Así que, comentamos la idea de empezar a incluirlos.

2024-04-19 08:31 UTC, PaulaaSTIC commented on SticInstall/sql/en/Settings.sql
> +('a649b1ca-4ada-e40f-5e47-660fc8e8d7cb', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_CUSTOM_SIDEBAR_COLOR', '1', 'Sets the sidebar color.\r\n0 -  Light subtheme\r\n1 - Dark subtheme.\r\nOnce
Cambiado el ingés a subtema.

2024-04-19 08:35 UTC, PaulaaSTIC commented on SticInstall/sql/ca/Settings.sql
> +('a649b1ca-4ada-e40f-5e47-660fc8e8d7cb', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_CUSTOM_SIDEBAR_COLOR', '1', 'Permet canviar el color del subtema de SinergiaCRM.\r\n0 -  Subtema clar\r\n1
He movido los parámetros. Ahora, GENERAL_CUSTOM_SIDEBAR_COLOR estará a continuación de GENERAL_CUSTOM_THEME_COLOR, seguido por los parámetros de GENERAL_RECAPTCHA.

2024-04-19 09:27 UTC, jalbaiges requested changes
Cadenas revisadas. Sugiero un cambio en el nombre del parámetro.

2024-04-19 09:27 UTC, jalbaiges commented on SticInstall/sql/ca/Settings.sql
> +('a649b1ca-4ada-e40f-5e47-660fc8e8d7cb', NOW(), NOW(), '1', '1', 0, '1', 'GENERAL', 'GENERAL_CUSTOM_SIDEBAR_COLOR', '1', 'Indica el mode del subtema de SinergiaCRM:\r\n0 -  Subtema clar\r\n1 - Subtem
Como apunte final, cambiaría el nombre del setting a GENERAL_CUSTOM_SUBTHEME_MODE.

2024-04-19 12:10 UTC, jalbaiges submitted a review, later dismissed

2024-05-06 12:23 UTC, jordiSTIC requested changes
Pequeña solicitud de modificación en los scripts de Update.
Observaciones (no necesariamente errores): 
1. Al modificar por edición inline el valor de la configuración `GENERAL_CUSTOM_SUBTHEME_MODE`, en lugar del valor modificado, se muestra el texto: 
```
* End SticCustom subtheme base color change to #aac5bd
* Setting SticCustom subtheme to all users. Done.
* Writing SticCustom as default subtheme in config_override.php. Done.0
```
Este texto corresponde a la salida (`echo`) que  realiza `SticCustomScss.php`.
El mismo comportamiento se produce al cambiar el valor de la configuración `GENERAL_CUSTOM_THEME_COLOR`

2. Si se modifica el nombre de la configuración, no se restaura el tema oscuro (por defecto). Lo mismo sucede con `GENERAL_CUSTOM_THEME_COLOR`

2024-05-06 14:56 UTC, PaulaaSTIC commented on SticUpdates/Migrations/ca/20240412_feature_SticCustomSidebarColor.sql
Modificado, ya están igual ambos scripts

2024-05-06 15:15 UTC, jordiSTIC approved these changes
(A)Probado
Cambios verificados

2024-05-06 16:29 UTC, juanSTIC requested changes
Ver comentarios

2024-05-06 16:29 UTC, juanSTIC commented on SticInclude/SticCustomScss.php
Hay un funcionamiento que no veo claro. Si se activa el modo claro sin haber cambiado el color base de SinergiaCRM, no cambia la barra lateral, debido a que el código entra en el if de la linea 20 y finaliza la ejecución antes de salir, por loq ue no puede activarse el subtema tema claro con el subtema stic
Quitando el return que hay al final del bloque esto ya no sucede, pero habría que evaluar si tiene otras consecuencias.

2024-05-07 10:17 UTC, juanSTIC approved these changes
Visto y probado

2024-05-07 12:35 UTC, jordiSTIC approved these changes
(A)Probado

2024-05-08 07:14 UTC, merged