Enhancement/multiLevelMenu
SinergiaTIC/SinergiaCRM pull request #208
Opened 2024-04-24 07:07 UTC by juanSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-07-17 13:01 UTC, AlbertoSTIC commented on custom/modules/Studio/SticAdvancedMenuController.php
> +        require_once 'SticUpdates/Scripts/ConvertSuiteCRMMenuToAdvancedMenu.php';
Los ficheros de SticUpdate no estarán en Producción. Si necesitamos alguna función específica la deberíamos pasar a otro lugar. 
De todas maneras, si se puede, en el momento de pasar de legacy a avanzado, evitaría el borrar la configuración que ya se tenga de avanzado.

2024-07-17 13:04 UTC, AlbertoSTIC commented on custom/modules/Studio/TabGroups/SticAdvancedMenuEdit.scss
> +/**
¿No tendría más sentido añadir este fichero en themes?

2024-07-19 07:09 UTC, juanSTIC commented on config.php
> +    'stic-advanced-menu-all' => '1',
corregido

2024-07-19 07:13 UTC, juanSTIC commented on config.php
> + *
¿a que modificaciones te refieres? Que yo pueda ver solo está añadido las variables al final...

2024-07-19 07:15 UTC, juanSTIC commented on custom/include/tabConfig.php
> +<?php
se había colado, eliminado

2024-07-19 08:01 UTC, juanSTIC commented on custom/modules/Studio/SticAdvancedMenuController.php
> +        require_once 'SticUpdates/Scripts/ConvertSuiteCRMMenuToAdvancedMenu.php';
Movida la lógica de SticUpdate al controller del menu avanzado, pero se mantiene el Script para la instalación, de manera que activa el nuevo menu y desactiva los iconos.

2024-07-19 11:53 UTC, juanSTIC commented on custom/modules/Studio/TabGroups/SticAdvancedMenuEdit.scss
> +/**
Pienso que como este fichero aplica exclusivamente a la página de configuración del menu, tanto el scss, como el css pueden permanecer junto al resto de ficheros de la funcionalidad, como si de un módulo se tratara...

2024-07-19 11:57 UTC, juanSTIC commented
> * Activar los menús avanzados para todo el mundo durante la actualización
> * No activar por defecto los iconos en la actualización, pero si en las nuevas instancias
> * Quitar el botón para volver atrás al modo clásico. En este caso, dejaría el código comentado para poder trasladárselo a SA.

Hecho

2024-08-28 11:19 UTC, jalbaiges requested changes
Primera revisión provisional de las cadenas hecha. Aprovechando la revisión de las cadenas, comentarios a valorar: 

1. En el fichero _custom/modules/Studio/TabGroups/SticAdvancedMenuEdit.js_ está hardcodeada la cadena _Restore the default SinergiaCRM menu?_, que, en consecuencia, aparece siempre en inglés. Ignoro si hay más, no lo he revisado en profundidad.

2. La descripción de la opción en el menú de administración indica _Configuración del menu de SinergiaCRM (avanzado o antiguo)_. Sin embargo, aparentemente la posibilidad de alternar entre versiones finalmente no se ha habilitado. Si efectivamente es así, la descripción no debería hacer referencia a esa posibilidad.

3. Al recorrer el árbol del menú aparecen sombreados en azul que no encajan demasiado con la estética del CRM. 

![image](https://github.com/user-attachments/assets/6959d1e5-d676-4456-b7b5-0be50d8ca360)

4. Construir el menú arrastrando módulos de un lado para otro resulta intuitivo, pero no acaba de quedar claro qué módulos están disponibles. Por un lado, aparentemente solo se puede operar con los módulos que previamente han sido habilitados en la opción de admin que sirve a tal efecto (inciso: lo cual es distinto del comportamiento actual) pero por el otro, si un módulo incluido en el menú es inhabilitado "por el otro lado", sigue apareciendo en la configuración y se puede trasladar entre pestañas. Solo si se pone como oculto y se guarda desaparece del interfaz. Aunque no sea grave, parece un tanto inconsistente.

5. La etiqueta "Módulos ocultos" no parece muy precisa. Realmente se refiere a módulos que están habilitados y que se muestran en TODO, pero que no han sido incluidos en el menú de forma específica. Si el comportamiento es el esperado, cabría modificar la etiqueta.

6. De los dos puntos anteriores se desprende la necesidad de afinar el funcionamiento y/o ampliar la información de ayuda. Se podría incorporar más info, por ejemplo, donde se ubica la frase inicial de "Arrastrar...", que parece demasiado sintética como resumen de lo que puede hacerse.

7. La maquetación de la vista de configuración podría "respetar el estándar" y, en cualquier caso, ganar aire entre los diferentes elementos, aparecen un tanto amontonados.

![image](https://github.com/user-attachments/assets/fca39cd0-d2d1-4886-8968-5950c8c7cdbf)

![image](https://github.com/user-attachments/assets/af0fb548-8428-4a5a-ae00-887c8f39ef1d)

8. Los botones del menú se parecen mucho a los botones generales pero al mismo tiempo tienen diferencias relevantes (bordes, negrita, espacio entre texto y borde). O los "clonamos" (creo que apostaría por eso) o los hacemos muy diferentes. En línea con lo anterior, darle aire al árbol.

9. El icono de opción desplegada parece tener algo "sucio" en el vértice inferior del triángulo.

![image](https://github.com/user-attachments/assets/a4b4b545-d82f-4400-9544-d96a8c4f8d1b)

2024-09-02 06:38 UTC, juanSTIC commented
> * En el fichero _custom/modules/Studio/TabGroups/SticAdvancedMenuEdit.js_ está hardcodeada la cadena _Restore the default SinergiaCRM menu?_, que, en consecuencia, aparece siempre en inglés. Ignoro si hay más, no lo he revisado en profundidad.

Hecho https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/5612fbd8b479a2330b6c90d2b4860ee3abe3f27d

2024-09-02 06:46 UTC, juanSTIC commented
> 2\. La descripción de la opción en el menú de administración indica _Configuración del menu de SinergiaCRM (avanzado o antiguo)_. Sin embargo, aparentemente la posibilidad de alternar entre versiones finalmente no se ha habilitado. Si efectivamente es así, la descripción no debería hacer referencia a esa posibilidad.

Se ha quitado el texto "(avanzado o antiguo)" https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/a32a67dc6b13fec11db3069fc6215c8022b8b4b2

2024-09-02 07:13 UTC, juanSTIC commented
> 3\. Al recorrer el árbol del menú aparecen sombreados en azul que no encajan demasiado con la estética del CRM.
> 
> ![image](https://private-user-images.githubusercontent.com/45965117/362235693-6959d1e5-d676-4456-b7b5-0be50d8ca360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTk1NTQsIm5iZiI6MTcyNTI1OTI1NCwicGF0aCI6Ii80NTk2NTExNy8zNjIyMzU2OTMtNjk1OWQxZTUtZDY3Ni00NDU2LWI3YjUtMGJlNTBkOGNhMzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2NDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyN2JhMjE4OWYyNDg3NWY4YWQzNzk3MGQ0NzBjNzkwNmIwOWJjYjNiNDM2NjY1N2RhZWUzNjdkNWQyY2E2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FMe05U3HTKsW2O9jZCdHdPe35JCYhYKoMn1_Pp-3wNo)
> 
Se han modificado los colores estableciendo tonos propios de SinergiaTIC https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/cc3ba729c940cb2a075af70372a08d1a3f202dbf

2024-09-02 10:20 UTC, juanSTIC commented
> 4\. Construir el menú arrastrando módulos de un lado para otro resulta intuitivo, pero no acaba de quedar claro qué módulos están disponibles. Por un lado, aparentemente solo se puede operar con los módulos que previamente han sido habilitados en la opción de admin que sirve a tal efecto (inciso: lo cual es distinto del comportamiento actual) pero por el otro, si un módulo incluido en el menú es inhabilitado "por el otro lado", sigue apareciendo en la configuración y se puede trasladar entre pestañas. Solo si se pone como oculto y se guarda desaparece del interfaz. Aunque no sea grave, parece un tanto inconsistente.

Se ha modificado el código de manera que ahora en la página de configuración del menú solamente aparecen los módulos que están habilitados. En el momento que se deshabilitan mediante la interfaz propia de SuiteCRM, desaparecen del configurador. https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/8d0e9daf1f19f7ebed7958bd5d297a83f45cc101

_Si se optará por permitir manejar en el configurador todos los módulos (habilitados o no) habría que hacer los cambios en este sentido._

2024-09-02 10:37 UTC, juanSTIC commented
> 5\. La etiqueta "Módulos ocultos" no parece muy precisa. Realmente se refiere a módulos que están habilitados y que se muestran en TODO, pero que no han sido incluidos en el menú de forma específica. Si el comportamiento es el esperado, cabría modificar la etiqueta.

Se ha modificado la etiqueta para ser mas específica.  https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/6706343fc2a2a5909d62d64799127d861f40ee2a

2024-09-02 14:53 UTC, juanSTIC commented
> 10\. La maquetación de la vista de configuración podría "respetar el estándar" y, en cualquier caso, ganar aire entre los diferentes elementos, aparecen un tanto amontonados.
> 
> ![image](https://private-user-images.githubusercontent.com/45965117/362243635-fca39cd0-d2d1-4886-8968-5950c8c7cdbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzI5MDYsIm5iZiI6MTcyNTI3MjYwNiwicGF0aCI6Ii80NTk2NTExNy8zNjIyNDM2MzUtZmNhMzljZDAtZDJkMS00ODg2LTg5NjgtNTk1MGM4YzdjZGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEwMjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYzRmYjQ3NzczMzk3OWJmYzlhYTc0YzI1MWExNjE5MGRiMzk1NTk4N2FlNTVlN2I1YTQ5OWQ3NWQ2ZGU0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jAYu3LxeEEyT0am0L7tEu_5CCRK-9pZQsehtzTFibN0)
> 
> ![image](https://private-user-images.githubusercontent.com/45965117/362243528-af0fb548-8428-4a5a-ae00-887c8f39ef1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzI5MDYsIm5iZiI6MTcyNTI3MjYwNiwicGF0aCI6Ii80NTk2NTExNy8zNjIyNDM1MjgtYWYwZmI1NDgtODQyOC00YTVhLWFlMDAtODg3YzhmMzllZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEwMjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyN2Q2ZWY2NDNhNDIyZDZmMDViZjE5ZDdmMTg0ODEzMWM4Nzc4OTZhZmEzMTIxYWQzMjM3MmMwMTJmNGMxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e5BpdK7mXLJAJa9ZAPGomg2gGO1uTSAzr8x9dLUeuwI)
> 
> 8. Los botones del menú se parecen mucho a los botones generales pero al mismo tiempo tienen diferencias relevantes (bordes, negrita, espacio entre texto y borde). O los "clonamos" (creo que apostaría por eso) o los hacemos muy diferentes. En línea con lo anterior, darle aire al árbol.
> 9. El icono de opción desplegada parece tener algo "sucio" en el vértice inferior del triángulo.
> 
> ![image](https://private-user-images.githubusercontent.com/45965117/362245568-a4b4b545-d82f-4400-9544-d96a8c4f8d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzI5MDYsIm5iZiI6MTcyNTI3MjYwNiwicGF0aCI6Ii80NTk2NTExNy8zNjIyNDU1NjgtYTRiNGI1NDUtZDgyZi00NDAwLTk1NDQtZDk2YThjNGY4ZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEwMjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NmE0OTg4YzBhNjJkODc2MTIwODBhZTRmM2Q4OTJiYzE4ZmEyNmVjOGI2ODMyZWVkM2NlMDVhMmNhYzZkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpP4tq2FCCM_rpn3t9Iqb9kQELe7vU9vx-T_DYOjOcM)

Se hace una nueva propuesta, recogiendo los puntos indicados (en la medida de lo posible, claro). Se corrigen los errores de visualización detectados https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/0a7cc2977e193011d258459f9b0e5891d6080055 https://github.com/SinergiaTIC/SinergiaCRM/pull/208/commits/3371b226ccfa2e231fa0031d80e5fb7ca3c725b2

2024-09-02 18:54 UTC, jalbaiges approved these changes

2024-09-04 08:53 UTC, AlbertoSTIC commented on config.php
> + *
![Selection_421](https://github.com/user-attachments/assets/0f9a96f9-98ee-447f-bb75-82e1086a4a9d)
![Selection_422](https://github.com/user-attachments/assets/0dc61228-6616-4bc7-ad9f-b1a87354e0d0)

2024-09-10 15:37 UTC, PaulaaSTIC requested changes
El botón de Home no funciona, y cada vez que lo seleccionamos se duplican las acciones disponibles en el módulo actual.

![image](https://github.com/user-attachments/assets/9909cc12-03e3-4776-b861-e9ab15ef417b)
Además en estas opciones se ven los símbolos aunque no se haya seleccionado  la opción _Mostrar iconos de módulos_

2024-09-13 10:21 UTC, jalbaiges commented
Si es posible, debería poder traducirse el menú contextual que aparece en los elementos del menú.

2024-09-20 05:40 UTC, juanSTIC commented
> El botón de Home no funciona

Corregido el botón home. Se ha añadido un evento explicito inline, para garantizar que el enlace de home no se sobreescribe por ningún otro proceso.

2024-09-20 07:55 UTC, juanSTIC commented
> Además en estas opciones se ven los símbolos aunque no se haya seleccionado la opción _Mostrar iconos de módulos_

Yo diría que en este caso se puede dejar así, ya que la visibilidad de los iconos se refiere exclusivamente a los de los módulos, no a las acciones.

2024-09-20 08:51 UTC, jalbaiges submitted a review, later dismissed

2024-09-30 09:44 UTC, AlbertoSTIC commented on modules/Administration/metadata/adminpaneldefs.php
> +$admin_option_defs['Administration']['configure_advanced_menu_tabs'] = [
Esta definición la podemos poner en esta ruta: custom/Extension/modules/Administration/Ext/Administration

2024-09-30 09:44 UTC, AlbertoSTIC requested changes
Ver comentario.

2024-09-30 09:44 UTC, AlbertoSTIC requested changes
Ver comentario.

2024-10-01 17:13 UTC, jalbaiges requested changes
Cadenas revisadas. Ver otros comentarios.

2024-10-02 14:23 UTC, juanSTIC commented on modules/Administration/metadata/adminpaneldefs.php
> +$admin_option_defs['Administration']['configure_advanced_menu_tabs'] = [
ok, cambiado a custom

2024-10-02 14:24 UTC, juanSTIC commented on modules/Administration/metadata/adminpaneldefs.php
> +$admin_option_defs['Administration']['configure_advanced_menu_tabs'] = [
sí, movido a custom

2024-10-02 15:54 UTC, juanSTIC commented on custom/Extension/modules/Studio/Ext/Language/ca_ES.SticLang.php
Porque la pantalla de gestión de nuevo menú (al igual que el antiguo) son parte del módulo _Studio_, se puede ver en la url `/index.php?action=wizard&module=Studio&wizard=StudioWizard&option=ConfigureMainMenu` Asi que se  ha mantenido como estaba el atiguo menú.

2024-10-02 16:03 UTC, juanSTIC commented on custom/Extension/modules/Studio/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_CONFIGURE_GROUP_TABS'] = "Configurar l'agrupació de subpanells";
En este caso (módulo Studio) se trata de la cadena que se muestra cómo encabezado de la página agrupación de subpaneles, mientras que la otra etiqueta (módulo Administration) es la que se muestra para el item del menú de administración.

2024-10-03 14:20 UTC, AlbertoSTIC submitted a review, later dismissed
Aprobado

2024-10-04 11:53 UTC, jalbaiges commented on custom/Extension/modules/Studio/Ext/Language/ca_ES.SticLang.php
Sí, efectivamente, pero da la sensación de que esa ubicación es herencia Sugar no demasiado razonable. Si no hay razones de reaprovechamiento de ficheros, creo que debería moverse de _Studio_ a _Administration_.

2024-10-04 11:54 UTC, jalbaiges commented on custom/Extension/modules/Studio/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_CONFIGURE_GROUP_TABS'] = "Configurar l'agrupació de subpanells";
Si se hace el movimiento que sugería en el otro comentario, la cadena debería poder eliminarse.

2024-10-04 11:55 UTC, jalbaiges requested changes
Solicito revalorar los comentarios previos sobre ubicación del código.

2024-10-04 17:39 UTC, jordiSTIC requested changes
Verificación inicial de la funcionalidad realizada. 

Observaciones del editor del menú principal:
1. Se Restaura al menú por defecto: Los ítems del menú RESERVAS y VENTAS aparecen como menú principal sin hijos en el editor, pero no se ven en el menú
2. Solo aparecen en el menú los elementos con links o que apunten a algún módulo. Es confuso, en la configuración del menú no parece que haya ningún error pero no se ven los elementos que en su estructura no haya nigún enlace. Se podría indicar de alguna forma (¿color distinto o en el texto de ayuda?)
3. En la descripción del PR se indica que se puede duplicar un elemento manteniendo el Ctrl. No se indica nada en la descripción que hay en el editor.
4. En el texto de la pantalla de configuración se indica que se eliminan elementos arrastrando a la columna de la derecha: sólo funciona si hay algún módulo habilitado no incluído y se arrastra el módulo de la izquierda al módulo de la derecha. Si todos los módulos están incluídos en el menú, únicamente se eliminan con la opción del menú contextual
5. El listado de módulos de la derecha acepta módulos como hijos
6. Si a un nodo con hijos se le indica un enlace, no se aplica el link. Si a un nodo con enlace se le añade un hijo, pierde el link. En cambio, un nodo a un módulo puede tener hijos y en el menú el link al módulo funciona correctamente.
7. Es poco intuitivo crear un nodo principal. Sólo se puede crear un elemento mediante el menú contextual dentro de otro nodo, después se debe arrastrar.
8. El duplicado de una rama no funciona correctamente mediante la tecla Ctrl: Se duplica la rama "ECONOMÍA" dentro de otro nodo: la nueva rama no contiene los nombres correctos y los nodos no se expanden correctamente. Al publicar no aparecen los items "Economía" en el menú

Otras observaciones:
- El menú TODO no tiene en cuenta la configuración "Mostrar iconos de módulos"

2024-10-08 07:50 UTC, juanSTIC commented
> 1. Se Restaura al menú por defecto: Los ítems del menú RESERVAS y VENTAS aparecen como menú principal sin hijos en el editor, pero no se ven en el menú

Es el funcionamiento esperado, si los módulos están inhabilitados

2024-10-08 07:51 UTC, juanSTIC commented
> 3\. En la descripción del PR se indica que se puede duplicar un elemento manteniendo el Ctrl. No se indica nada en la descripción que hay en el editor.

Se ha inhabilitado la opción de duplicar elementos mediante CTRL que era errática y se ha incluido en el menú contextual para los nodos intermedios y en un enlace al principio del árbol para crear nodos principales

2024-10-08 08:05 UTC, juanSTIC commented
> 4\. En el texto de la pantalla de configuración se indica que se eliminan elementos arrastrando a la columna de la derecha: sólo funciona si hay algún módulo habilitado no incluído y se arrastra el módulo de la izquierda al módulo de la derecha. Si todos los módulos están incluídos en el menú, únicamente se eliminan con la opción del menú contextual

Se ha visto que esto funciona correctamente y es posible arrastra a la zona de la derecha los elementos, aunque esta zona esté vacía

2024-10-08 08:09 UTC, juanSTIC commented
> 2\. Solo aparecen en el menú los elementos con links o que apunten a algún módulo. Es confuso, en la configuración del menú no parece que haya ningún error pero no se ven los elementos que en su estructura no haya nigún enlace. Se podría indicar de alguna forma (¿color distinto o en el texto de ayuda?)

Pienso que bastaría con añadir en la documentación que los elementos padre, que a su vez tienen una URL esta no funcionará. Por otro lado es una situación improbable.

2024-10-08 08:14 UTC, juanSTIC commented
> * El listado de módulos de la derecha acepta módulos como hijos

Corregido

2024-10-08 08:29 UTC, juanSTIC commented
> 6\. Si a un nodo con hijos se le indica un enlace, no se aplica el link. Si a un nodo con enlace se le añade un hijo, pierde el link. En cambio, un nodo a un módulo puede tener hijos y en el menú el link al módulo funciona correctamente.

Corregido. Ahora los nodos con URL pueden tener hijos manteniendo la funcionalidad del enlace

2024-10-08 08:29 UTC, juanSTIC commented
> 7\. Es poco intuitivo crear un nodo principal. Sólo se puede crear un elemento mediante el menú contextual dentro de otro nodo, después se debe arrastrar.

Corregido, añadiendo un enlace específico a tal efecto.

2024-10-08 08:30 UTC, juanSTIC commented
> 8\. El duplicado de una rama no funciona correctamente mediante la tecla Ctrl: Se duplica la rama "ECONOMÍA" dentro de otro nodo: la nueva rama no contiene los nombres correctos y los nodos no se expanden correctamente. Al publicar no aparecen los items "Economía" en el menú

Se ha corregido con la nueva funcionalidad de duplicado

2024-10-08 08:38 UTC, juanSTIC commented
1. Se ha movido la lógica del menú de configuración al módulo Administration
2. Se han corregido los problemas funcionales [detectados por Jordi](https://github.com/SinergiaTIC/SinergiaCRM/pull/208#pullrequestreview-2348743023), para ello se ha optado, entre otras cosas menores,  por:
   - Inhabilitar el duplicado de nodos mediante el uso de la tecla CTRL y en su lugar se usa un nuevo elemento del menu contextual
   - Se ha añadido unos enlaces al inicio del árbol que permite crear un nuevo nodo principal (además de expandir o contraer el árbol) .

2024-10-08 09:37 UTC, jalbaiges requested changes
Cadenas revisadas. Ver un par de comentarios adicionales.

2024-10-08 09:37 UTC, jalbaiges commented on custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_CONFIGURE_MAIN_MENU_DESC'] = "Configuració de l'estructura i el contingut del menú";
En este bloque de cadenas aparecen todos los elementos que hemos ido incorporando en la página de administración del CRM. Cada elemento tiene una pareja de cadenas, título y descripción, que por lo general siguen el estándar _LBL_STIC_ITEM_LINK_TITLE_ y _LBL_STIC_ITEM_DESCRIPTION_. A efectos de uniformidad, modificaría las dos añadidas en este PR como _LBL_STIC_MAIN_MENU_LINK_TITLE_ y _LBL_STIC_MAIN_MENU_DESCRIPTION_.

Además, si es posible, aprovecharía para cambiar _LBL_SINERGIACRM_TAB_STIC_SETTINGS_X_ por _LBL_STIC_SETTINGS_X_ y _LBL_STIC_MANAGE_SDA_ACTIONS_X_ por _LBL_STIC_SINERGIADA_X_.

2024-10-08 09:37 UTC, jalbaiges commented on custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_STIC_MENU_CHANGE_TO_LEGACY_CONFIRM'] = "Voleu canviar al menú clàssic? Es restaurarà la configuració que hi havia quan es va activar el menú avançat. Podreu tornar a activar el menú
Si no lo recuerdo mal, en un commit anterior se habían eliminado estas cadenas porque la funcionalidad de cambio entre versiones de menú finalmente no se iba a desplegar o algo por el estilo. Valorar si procede (re)eliminar estas cadenas.

2024-10-08 10:52 UTC, juanSTIC commented on custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_STIC_MENU_CHANGE_TO_LEGACY_CONFIRM'] = "Voleu canviar al menú clàssic? Es restaurarà la configuració que hi havia quan es va activar el menú avançat. Podreu tornar a activar el menú
En este caso se habían mantenido estas cadenas y el código que las usaría, pero comentado, a modo de referencia por si en un futuro fueran necesario. Elimino la cadena y el código relacionado con la funcionalidad y así todo quedará más limpio.

2024-10-08 11:11 UTC, juanSTIC commented on custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_CONFIGURE_MAIN_MENU_DESC'] = "Configuració de l'estructura i el contingut del menú";
Aplicados los cambios en todas las etiquetas indicadas, incluidas las de stic_Settings y SinergiaDA

2024-10-08 11:47 UTC, jalbaiges approved these changes

2024-10-09 10:49 UTC, jordiSTIC requested changes
Verificación funcional:
- Las observaciones anteriores han estado corregidas.

Observaciones del editor del menú:
1. El listado de módulos de la derecha sigue aceptando módulos hijos (estructura de árbol).
2. Si en el listado de la derecha se genera una estructura de árbol, y se arrastra a la izquierda, al guardar y aplicar vuelven a aparecer elementos arrastrados a la derecha y la estructura de árbol de la izquierda tiene valores "J1 122" y parecidos y el menú no muestra el subárbol.
3. La funcionalidad de enlace se pierde si existen nodos hijos

Observaciones del menú:
1. La opción "TODO" no muestra nunca los iconos

2024-10-09 11:31 UTC, PaulaaSTIC requested changes
Algunas observaciones:

- Si un nodo tiene nodos colgando, se permite crear una URL, y en el editor aparece bien, pero no funciona el link.
- Cuando le damos a guardar, aparece en la esquina superior derecha un mensaje de guardado diferente al que se muestra al restaurar. 
- El símbolo de cambios sin guardar que aparece en el botón 'Guardar y aplicar' solo se muestra si añadimos un nuevo nodo; si hacemos cambios en nodos ya creados, no avisa de esos cambios.

2024-10-09 14:16 UTC, juanSTIC commented
> 1. El listado de módulos de la derecha sigue aceptando módulos hijos (estructura de árbol).

Aunque ya estaba implementado, parece que un problema de cache en la instancia de prueba impedía que funcionara correctamente. volver a probar

2024-10-09 14:30 UTC, jordiSTIC commented
> > 1. El listado de módulos de la derecha sigue aceptando módulos hijos (estructura de árbol).
> 
> Aunque ya estaba implementado, parece que un problema de cache en la instancia de prueba impedía que funcionara correctamente. volver a probar

Ok, el listado de módulos de la derecha no puede tener estructura de árbol. Esto elimina también el error que se produce al arrastrar un árbol de la derecha a la izquierda

2024-10-09 16:49 UTC, juanSTIC commented
> 1. La opción "TODO" no muestra nunca los iconos

cCorregido

2024-10-10 11:57 UTC, juanSTIC commented
> 3\. La funcionalidad de enlace se pierde si existen nodos hijos

Esto ya está corregido, parece que era tema de cache

2024-10-10 11:58 UTC, juanSTIC commented
> * Si un nodo tiene nodos colgando, se permite crear una URL, y en el editor aparece bien, pero no funciona el link.

Esto está corregido, parece que era tema de cache

2024-10-10 11:58 UTC, juanSTIC commented
> * Cuando le damos a guardar, aparece en la esquina superior derecha un mensaje de guardado diferente al que se muestra al restaurar.

Son funciones diferentes, ya que uno requiere confirmación y el otro no. Se valora dejarlo asi.

2024-10-10 12:08 UTC, juanSTIC commented
Se han corregido los problemas informados. Para evitar cierto problema de inconsistencia entre los ids de los arboles al arrastrar y soltar se ha optado por eliminar la funcionalidad de arrastrar nodos desde el menú hasta los módulos ocultos, de manera que esta operación (eliminar) hay que hacerla siempre mediante el menú contextual.
Esto ha implicado un cambio mínimo en el texto informativo del menú @jalbaiges

2024-10-10 21:42 UTC, jalbaiges submitted a review, later dismissed

2024-10-11 07:14 UTC, jordiSTIC requested changes
Se han realizado pruebas en el editor de menús.
Se verifica que funciona correctamente y se han aplicado los cambios solicitados.

Se observa un nuevo error introducido: 
- Se crea un nodo hijo a un nodo principal
- Bajo ese nodo se crea otro
- Se le añade una url al nodo creado
- Al guardar, el primer nodo creado pierde el nombre y el hijo

2024-10-14 05:52 UTC, juanSTIC commented
> Se observa un nuevo error introducido:
> 
> * Se crea un nodo hijo a un nodo principal
> * Bajo ese nodo se crea otro
> * Se le añade una url al nodo creado
> * Al guardar, el primer nodo creado pierde el nombre y el hijo

Corregido. 
Se ha visto que este error se daba si los nodos creados tenían el mismo ID

2024-10-14 09:57 UTC, jordiSTIC approved these changes
(A)Probado
Los errores detectados han sido solucionados. 
Las pruebas realizadas han ido bien. Todo parece robusto y funcional.
Hecha revisión de código (aunque no en profundidad)

2024-10-15 08:17 UTC, PaulaaSTIC submitted a review, later dismissed
¡(A)probado!

2024-12-16 13:04 UTC, juanSTIC commented on custom/Extension/modules/Studio/Ext/Language/ca_ES.SticLang.php
Se han movido las cadenas relacionadas con el nuevo menú al módulo Administration

2024-12-23 07:59 UTC, jalbaiges commented
FYI, he añadido el PR al proyecto _SuiteCRM core modifications_ con estado _Internal STIC_ (veo que se modifica _include/MVC/View/SugarView.php_).

2024-12-23 11:47 UTC, jalbaiges submitted a review, later dismissed
Cadenas revisadas.

2024-12-30 15:55 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2025-01-03 09:35 UTC, jalbaiges submitted a review, later dismissed
Cadenas revisadas.

2025-01-08 11:42 UTC, jordiSTIC requested changes
Observaciones funcionales:
#### Iconos
En algunos módulos no aparece el icono aunque en "Estudio" sí aparece. Por ejemplo, los módulos "Plantillas de Email" y "Público Objetivo". Hay otros módulos que no aparecen en Estudio pero parece que sí tienen icono y el menú no lo detecta. Por ejemplo, "Calendario de Reservas". 
Los iconos de Estudio se obtienen mediante la llamada: `IconRepository::getIconName($this->module)` que contiene alguna personalización de iconos para ciertos módulos. Se debería usar la misma función

#### Buscador en "TODOS"
El buscador es sensible a los acentos: Si se escribe "pu" no aparecen los módulos con la u acentuada, por ejemplo "listas de público objetivo"

2025-01-08 12:32 UTC, juanSTIC commented
> #### Iconos
> En algunos módulos no aparece el icono aunque en "Estudio" sí aparece. Por ejemplo, los módulos "Plantillas de Email" y "Público Objetivo". Hay otros módulos que no aparecen en Estudio pero parece que sí tienen icono y el menú no lo detecta. Por ejemplo, "Calendario de Reservas". Los iconos de Estudio se obtienen mediante la llamada: `IconRepository::getIconName($this->module)` que contiene alguna personalización de iconos para ciertos módulos. Se debería usar la misma función

Se utiliza el método propuesto, lo que ahora incluye los iconos en los que la función`IconRepository::getIconName` devuelve algo, lo que no es el caso de _stic_Booking_Calendar_ o _Kreports_, que no tienen un icono propio, ni está previsto en la función anterior. Si en algún momento se añaden iconos para estos módulos, aparecerán automáticamente en el menú.

2025-01-08 12:33 UTC, juanSTIC commented
> #### Buscador en "TODOS"
> El buscador es sensible a los acentos: Si se escribe "pu" no aparecen los módulos con la u acentuada, por ejemplo "listas de público objetivo"

Se ha corregido y ahora la búsqueda no es sensible a caracteres especiales.

2025-01-08 16:10 UTC, jordiSTIC approved these changes
(A)Probado.
Se ha probado testeando tanto la parte de administración/configuración como la propia del menú, usando distintos idiomas y validando los ficheros generados.

Muy bueno!! Buen menú multi-nivel y multi-idioma altamente configurable :+1:

2025-01-08 16:27 UTC, PaulaaSTIC approved these changes
(A)probado!!

2025-01-20 11:40 UTC, AlbertoSTIC approved these changes
Aprobado

2025-01-21 09:04 UTC, merged