Feature - Reservas - Cambios para incluir la gesión residencial
SinergiaTIC/SinergiaCRM pull request #209
Opened 2024-04-24 11:27 UTC by PaulaaSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-04-29 07:29 UTC, AlbertoSTIC commented on modules/stic_Resources/metadata/detailviewdefs.php
> +                'LBL_PANEL_RECORD_DETAILS' => array(
Valorar si este cambio puede afectar a etiquetas de instancias que ya se ha modificado. Lo comentamos en reunión de equipo.

2025-03-25 11:38 UTC, AlbertoSTIC submitted a review, later dismissed
Además de los comentarios en código, algunos puntos:
- Hasta ahora, el módulo de Plazas depende de que el módulo Recursos esté activo. Propongo estudiar las posibilidad de que los módulos de Plazas y Recursos sean independientes pero utilizando los mismos vardefs/tablas de BDD. ¿Que las plazas sean un nuevo bean que extienda de Recursos?
- Según el punto anterior, considerar si es relevante que las plazas tengan su propia definición de vista de edición/detalle.

2025-04-15 15:59 UTC, PaulaaSTIC commented on custom/include/generic/SugarWidgets/SugarWidgetSubPanelCloseButtonstic_Resources.php
> +class SugarWidgetSubPanelCloseButtonstic_Resources extends SugarWidgetField
Corregido

2025-04-15 16:00 UTC, PaulaaSTIC commented on modules/stic_Resources/views/view.list2.php
Corregido

2025-04-15 16:00 UTC, PaulaaSTIC commented on modules/stic_Resources/controller.php
> +    public function action_places()
Corregido

2025-04-15 16:00 UTC, PaulaaSTIC commented on modules/stic_Resources/controller.php
> +        global $app_list_strings;
Corregido

2025-04-15 16:00 UTC, PaulaaSTIC commented on modules/stic_Bookings/config_place_fields.php
Corregido

2025-04-21 08:26 UTC, PaulaaSTIC commented on modules/stic_Resources/views/view.list2.php
> +            $savedSearchName = empty($_REQUEST['saved_search_select_name']) ? '' : (' - ' . $_REQUEST['saved_search_select_name']);
Eliminada

2025-04-21 08:28 UTC, PaulaaSTIC commented on include/tabConfig.php
Eliminado, se usa: `custom/include/SticAdvancedTabConfig.php`

2025-04-22 08:12 UTC, PaulaaSTIC commented on modules/stic_Bookings/config_place_fields.php
> +global $config_place_fields;
Corregido

2025-04-22 08:13 UTC, PaulaaSTIC commented on modules/stic_Bookings_Places_Calendar/controller.php
> +class stic_Bookings_Places_CalendarController extends SugarController
Si, modificado para extender del controlador de stic_Bookings_Calendar

2025-04-22 08:13 UTC, PaulaaSTIC commented on modules/stic_Bookings/config_resource_fields.php
> +global $config_resource_fields;
Corregido

2025-04-23 11:33 UTC, PaulaaSTIC commented on SticInclude/vendor/fullcalendar_new/index.global.js
Corregido

2025-05-21 08:46 UTC, enricsinergia submitted a review, later dismissed
Finalizadas pruebas indicadas en PR (falta trastear todavía un poco y revisar los ficheros).

A lo mostrado en el comentario anterior (lo siento, quería dejarme un comentario en la review y se lanzó), se añade:

1) El botón de "Cargar centros", permite añadir más de una vez el mismo centro

2) En Plazas no veo filtro por centro ni columna. Si quiero ver las plazas de un centro,  ¿cómo lo hago?

3) En Recursos aparecen los recursos de tipo plaza. ¿Es correcto?

4) El botón “Cargar recursos” está muy bien para encontrar las plazas que cumplen el criterio, pero me las añade todas a la reserva si no las elimino una a una…. ¿quizás unos checkboxes para seleccionar las que queremos?

5) Al cargar los recursos, aparecen pre-rellenados algunos campos, pero lo hacen con el valor interno y no con el literal traducido

6) No me deja eliminar un recurso de una reserva si todavía no ha llegado su fecha de inicio (mensaje “la fecha de cierre debe ser anterior a la de inicio”)

2025-05-23 09:09 UTC, PaulaaSTIC commented on modules/stic_Resources/Utils.js
> +    if (centerLabelTd.length && !centerLabelTd.find("span.required").length) {
Resuelto

2025-05-23 09:09 UTC, PaulaaSTIC commented on modules/stic_Bookings/language/en_us.lang.php
> +    'LBL_PLACE_BOOKING' => 'Place booking',
Incluido en todos los idiomas

2025-06-02 10:55 UTC, PaulaaSTIC commented
> Finalizadas pruebas indicadas en PR (falta trastear todavía un poco y revisar los ficheros).
> 
> A lo mostrado en el comentario anterior (lo siento, quería dejarme un comentario en la review y se lanzó), se añade:
> 
> 1. El botón de "Cargar centros", permite añadir más de una vez el mismo centro.
**Corregido**
> 2. En Plazas no veo filtro por centro ni columna. Si quiero ver las plazas de un centro,  ¿cómo lo hago?
**Corregido**
> 3. En Recursos aparecen los recursos de tipo plaza. ¿Es correcto?
**Corregido**
> 4. El botón “Cargar recursos” está muy bien para encontrar las plazas que cumplen el criterio, pero me las añade todas a la reserva si no las elimino una a una…. ¿quizás unos checkboxes para seleccionar las que queremos?
**En lugar de seleccionar cada plaza manualmente, se utilizarán filtros y el campo _Número de plazas_ para gestionar las reservas de forma más eficiente..** 
> 5. Al cargar los recursos, aparecen pre-rellenados algunos campos, pero lo hacen con el valor interno y no con el literal traducido
**Corregido**
> 6. No me deja eliminar un recurso de una reserva si todavía no ha llegado su fecha de inicio (mensaje “la fecha de cierre debe ser anterior a la de inicio”)
**Se ha modificado el mensaje , añadiendo una nueva etiqueta: _LBL_CLOSE_RESOURCE_BEFORE_START_ERROR_**

2025-06-11 08:25 UTC, jalbaiges commented on modules/stic_Payment_Commitments/language/en_us.lang.php
> +    'LBL_STIC_BOOKINGS_STIC_PAYMENT_COMMITMENTS_FROM_STIC_BOOKINGS_TITLE' => 'Booking',
Si esta cadena es necesaria, entonces debería aparecer en el resto de ficheros de idiomas.

2025-06-11 08:33 UTC, jalbaiges commented on modules/stic_Centers/language/es_ES.lang.php
> +  'LBL_STIC_RESOURCES_STIC_CENTERS_FROM_STIC_RESOURCES_TITLE' => 'Plazas',
Si esta cadena es necesaria (ya aparece una con el mismo valor unas filas más arriba), entonces debería replicarse en el resto de ficheros de idiomas.

2025-06-11 08:56 UTC, jalbaiges commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_list_strings['stic_resources_types_list']['places'] = 'Plaça';
Si no supone mucho trabajo, el nombre interno debería ser _place_ en lugar de _places_.

2025-06-13 08:45 UTC, enricsinergia requested changes
Sigo con la revisión, pero avanzo algunos puntos para poder ir revisándolos:

Una chorrada: cambiaría el literal "Nuevo recurso" por "Nuevo recurso/plaza"

Hay un error al hacer la consulta de recursos
![image](https://github.com/user-attachments/assets/a48c01b7-0ef1-4725-adfe-73746fc59d3a)

Algunos literales "Undefined" (en catalán)
![image](https://github.com/user-attachments/assets/5d446f9c-02d9-40e1-9a58-ec9202183a5d)



Si en la plaza no fijo el "tipo de ususario del servicio", no debería aparecer esa plaza marque lo que marque en el filtro?

En la reserva de recurso, si intento mostrar los recursos antes de entrar las fechas, aparece error enlos campos de fecha (se ve poco). Pero el problema no es ese, el problema es que una vez rellenados, vuelvo a cargar recursos, éstos se muestran, pero el mensaje de error en los campos fecha no desaparece

Creo que ya está comentado y aceptado,pero el campo estado no se está contemplando a la hora de cargar recursos disponibles. Si se quiere dejar una plaza inactiva (porqué hay que reformarla o lo que sea, será necesario hacer una reserva a tal fin)

En los filtros de reservas, no se puede filtrar para ver sólo reservas de plazas o de recursos estándar. Sería bueno (ya sabéis que yoincluso separaría unas reservas de otras como se ha hecho con el listado de plazas y recursos) tenerlo.

Tenemos un calendario de reservas y un calendario de plazas, pero en el calendario std de reservas también aparecen las reservas de plazas. En el filtro es cierto que se puede seleccionar sólo plazas o el resto..... a partir del campo categoría... que no he sido capaz de identificar




Cuando modifico la fecha prevista, se modifica la real, aunque sea una fecha ya pasada y los valores fueran distintos.

Si a una reserva existente que tiene un recurso no plaza, le marco el check de plaza, se pierde la vinculación con el recurso que tenía.

No sé si puede tener sentido o no, pero imaginemos que tengo que hacer una reserva para 1 hombre y 2 mujeres. Con el funcionamiento actual del filtro no podría incluir las 3 reservas juntas o tendría que coger todas las plazas de hombres y mujeres y luego eliminar todas las no usadas. Si pongo primero hombre 1, y luego mujer 2, pierdo la reserva de hombre. Si pongo 3 y hombre y mujer en el filtro, me puede coger las 3 de hombre....

Si añado manualmente un recurso a una reserva de plaza, el pop-up que me aprece es estándar de recurso y no me permite filtrar por los campos de plaza (género, etc).

Deja incluir en una reserva tanto recursos plaza como no plaza. No tiene mayor importancia, pero luego la gestión de la carga de recursos puede resultar un poco inconsistente.

Desde familias, falla el literal del subpanel de reservas:
![image](https://github.com/user-attachments/assets/5636bf2a-b926-437a-905b-26b825bbf0a4)

Me he encontrado el módulo de centros oculto, pero no el subpanel. Si se quiere desplegar el módulo oculto, también habría que incluir el script para ocultar los subpaneles

En la descripción del PR, en la prueba de "3. Reserva de plazas", se espcifica "Se muestran los filtros adecuados según el tipo de recurso.". ¿Los filtros de plaza no son siempre los mismos? y si no es plaza no hay filtros...

En el apartado de "2.Reservas estándar", el cálculo para recursos std está mal expresado (donde dice hourly sería el daily y viceversa)



Ampliación 16/06/2025:
Cuando estoy en "Recursos", puedo acceder al calendario de reservas pero no tengo la opción del calendario de plazas
Quizás és más un bug/mejora para el menú: la opción de "Calendari de reserva de places" cuando aparece en el menú no aparece todo lo "bonita" que debería
![image](https://github.com/user-attachments/assets/d649ba5d-6b06-4f7e-b401-5afad70a37e8)


En el calendario de reservas de plazas:
A pesar de estar en catalán, me aparecen literales en inglés
El "Today" si me pongo encima, me dice "This month" o "This week" (no sé si ya es lo normal o habría que revisar algún literal)
La semana empieza en domingo a pesar que la configuración del usuario dice que empieza en lunes

Obtengo error (mejor dicho, no tengo campos) cuando intento crear un recurso desde el subpanel de centros
![image](https://github.com/user-attachments/assets/c5ef451c-ac09-448a-a60b-ca7f09a05438)

Al cargar recursos de un centro, si selecciono "Hombre", no me aparecen los "mixtos". Puede que ya sea correcto, pero si estoy intentando coger 100 camas para hombres y sólo tengo 90 de hombres, quizás debería coger también las plazas mixtas..... podemos pensar en que se puede añadir "mixta" al criterio de búsqueda, pero en ese caso pueden aparecer las plazas mixtas delante de las de hombres. Quizás habría que repensar alguna cosa aquí o documentar que en ese caso lo mejor es hacer 2 reservas: una para hombres y otra para las plzas mixtas que he tenido que usar.

El "Cargar recursos" no me está fucnionando corretamente en algún caso (debería haberme cargado el C2P3 que no tiene ninguna reserva):
![image](https://github.com/user-attachments/assets/2dcd2070-8b7d-4161-a14a-f907a2154015)

![image](https://github.com/user-attachments/assets/1c991e7f-b5ae-4c6f-af20-3281fd977b03)


Si borro la fecha final prevista, me borra también la fecha final real 

Si modifico una reserva, al cargar recursos, nome muestra el recurso que ya tenía asociado a la reserva
![image](https://github.com/user-attachments/assets/7ae30e75-5e46-47bd-a704-f19d4e472c76)

![image](https://github.com/user-attachments/assets/56f60df4-610f-4a26-b264-89a9aadaa314)

2025-06-23 10:35 UTC, PaulaaSTIC commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +$app_list_strings['stic_resources_types_list']['places'] = 'Plaça';
Cambiado

2025-06-23 10:36 UTC, PaulaaSTIC commented on modules/stic_Centers/language/es_ES.lang.php
> +  'LBL_STIC_RESOURCES_STIC_CENTERS_FROM_STIC_RESOURCES_TITLE' => 'Plazas',
Añadida en todos los idiomas. La tenemos que incluir porque esta es para el subpanel y la otra para el campo.

2025-07-04 10:11 UTC, enricsinergia requested changes
Se han corregido ya muchos puntos :clap:, pero todavía quedan algunos puntos:

no es capaz de encontrarme plazas donde no haya marcado el tipo de usuario. Quizás habría que hacer el tipo de usuario (y algún otro campo) obligatorio en la creación de plaza o cambiar el comportamiento para que sea simétrico.
Revisar si en algún lugar todavía se utiliza "places" en lugar de "place" (se corrigió el controller en el calendario de plazas tanto en sql como en un filtro php)
Desde familias, falla el literal del subpanel de reservas:
![image](https://github.com/user-attachments/assets/1e25d474-f340-43ef-ab74-ba3b8c5b6c23)

Me he encontrado el módulo de centros oculto, pero no el subpanel. Si se quiere desplegar el módulo oculto, también habría que incluir el script para ocultar los subpaneles (como se hizo con el Journal por ejemplo)
Cuando estoy en "Recursos", puedo acceder al calendario de reservas pero no tengo la opción del calendario de plazas
Cuando estoy en recursos, me muestra la opción de mostrar plazas aunque el módulo no esté activo
Sigue no mostrándome bien algunos recursos


![image](https://github.com/user-attachments/assets/3bc266b2-643b-4854-9273-c480d8033108)

![image](https://github.com/user-attachments/assets/8e7fe21c-3fc2-4902-8241-f7cb35c75568)

Sigue habiendo algún problema cuando elimino un recurso que tenía en una reserva: creo una reserva con el R1. La edito, borro el R1 de la lista, busco de nuevo en el Centro y me dice que no hay plazas.

2025-07-10 11:34 UTC, PaulaaSTIC commented
> Pequeño bug al seleccionar la fecha de inicio en una Reserva. Se quita la fecha cuando se selecciona: ![bug-gestion-residencial-reservas-fecha-inicio](https://private-user-images.githubusercontent.com/95768967/461100327-7d613f52-9980-4554-a029-96afb7d8b165.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDAzMjctN2Q2MTNmNTItOTk4MC00NTU0LWEwMjktOTZhZmI3ZDhiMTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMmFiM2ZhNjA5OTBiNDBiYjBiZjUyMTU4ZmUyNzk2MTEzYmMzODA2OTQyZmQyZTgxZGE2Yzg0NDZiZjA3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MPauqsvAzSonKnqBVR-HGt0P1BhAScta7ATGwYbS_BI) [ ![bug-gestion-residencial-reservas-fecha-inicio](https://private-user-images.githubusercontent.com/95768967/461100327-7d613f52-9980-4554-a029-96afb7d8b165.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDAzMjctN2Q2MTNmNTItOTk4MC00NTU0LWEwMjktOTZhZmI3ZDhiMTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMmFiM2ZhNjA5OTBiNDBiYjBiZjUyMTU4ZmUyNzk2MTEzYmMzODA2OTQyZmQyZTgxZGE2Yzg0NDZiZjA3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MPauqsvAzSonKnqBVR-HGt0P1BhAScta7ATGwYbS_BI) ](https://private-user-images.githubusercontent.com/95768967/461100327-7d613f52-9980-4554-a029-96afb7d8b165.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDAzMjctN2Q2MTNmNTItOTk4MC00NTU0LWEwMjktOTZhZmI3ZDhiMTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMmFiM2ZhNjA5OTBiNDBiYjBiZjUyMTU4ZmUyNzk2MTEzYmMzODA2OTQyZmQyZTgxZGE2Yzg0NDZiZjA3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MPauqsvAzSonKnqBVR-HGt0P1BhAScta7ATGwYbS_BI) [ ](https://private-user-images.githubusercontent.com/95768967/461100327-7d613f52-9980-4554-a029-96afb7d8b165.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDAzMjctN2Q2MTNmNTItOTk4MC00NTU0LWEwMjktOTZhZmI3ZDhiMTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMmFiM2ZhNjA5OTBiNDBiYjBiZjUyMTU4ZmUyNzk2MTEzYmMzODA2OTQyZmQyZTgxZGE2Yzg0NDZiZjA3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MPauqsvAzSonKnqBVR-HGt0P1BhAScta7ATGwYbS_BI)
> 
Resuelto
> Pequeño bug al marcar Reserva de plazas. Aparece "Cargar centro" en Recursos cuando desmarcas Reserva de plazas: ![bug-cargar-centro-recursos](https://private-user-images.githubusercontent.com/95768967/461101959-2e4e31c2-d081-449a-8601-690bdbcb8195.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDE5NTktMmU0ZTMxYzItZDA4MS00NDlhLTg2MDEtNjkwYmRiY2I4MTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MWNiOWJlNDMzZmYwNmE4MWEwMTZkMjVmOWM2Njc2MGZhNmEwOGZhOTM4NDQ1MDBkMzg1YTA5NWEzZmZjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hDlILPYyztclQyQIKswMvcFZkZu5MM-x32AeJe7sxQ4) [ ![bug-cargar-centro-recursos](https://private-user-images.githubusercontent.com/95768967/461101959-2e4e31c2-d081-449a-8601-690bdbcb8195.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDE5NTktMmU0ZTMxYzItZDA4MS00NDlhLTg2MDEtNjkwYmRiY2I4MTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MWNiOWJlNDMzZmYwNmE4MWEwMTZkMjVmOWM2Njc2MGZhNmEwOGZhOTM4NDQ1MDBkMzg1YTA5NWEzZmZjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hDlILPYyztclQyQIKswMvcFZkZu5MM-x32AeJe7sxQ4) ](https://private-user-images.githubusercontent.com/95768967/461101959-2e4e31c2-d081-449a-8601-690bdbcb8195.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDE5NTktMmU0ZTMxYzItZDA4MS00NDlhLTg2MDEtNjkwYmRiY2I4MTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MWNiOWJlNDMzZmYwNmE4MWEwMTZkMjVmOWM2Njc2MGZhNmEwOGZhOTM4NDQ1MDBkMzg1YTA5NWEzZmZjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hDlILPYyztclQyQIKswMvcFZkZu5MM-x32AeJe7sxQ4) [ ](https://private-user-images.githubusercontent.com/95768967/461101959-2e4e31c2-d081-449a-8601-690bdbcb8195.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODA4NDEsIm5iZiI6MTc1MTg4MDU0MSwicGF0aCI6Ii85NTc2ODk2Ny80NjExMDE5NTktMmU0ZTMxYzItZDA4MS00NDlhLTg2MDEtNjkwYmRiY2I4MTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA3VDA5MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MWNiOWJlNDMzZmYwNmE4MWEwMTZkMjVmOWM2Njc2MGZhNmEwOGZhOTM4NDQ1MDBkMzg1YTA5NWEzZmZjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hDlILPYyztclQyQIKswMvcFZkZu5MM-x32AeJe7sxQ4)

Resuelto

2025-07-10 11:42 UTC, PaulaaSTIC commented
> Se han corregido ya muchos puntos 👏, pero todavía quedan algunos puntos:
> 
> no es capaz de encontrarme plazas donde no haya marcado el tipo de usuario. Quizás habría que hacer el tipo de usuario (y algún otro campo) obligatorio en la creación de plaza o cambiar el comportamiento para que sea simétrico. 

Resuelto

Revisar si en algún lugar todavía se utiliza "places" en lugar de "place" (se corrigió el controller en el calendario de plazas tanto en sql como en un filtro php) 
> Desde familias, falla el literal del subpanel de reservas: ![image](https://private-user-images.githubusercontent.com/57436616/462420169-1e25d474-f340-43ef-ab74-ba3b8c5b6c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxNDc0NjIsIm5iZiI6MTc1MjE0NzE2MiwicGF0aCI6Ii81NzQzNjYxNi80NjI0MjAxNjktMWUyNWQ0NzQtZjM0MC00M2VmLWFiNzQtYmEzYjhjNWI2YzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDExMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYjQ1MTlhYTQ0ZmZhOGRiNDRjYWM1NjY0MjhiOTdmMmM0OTI1OTUxODhmMzllODliMmQ5MmNhYWQ4NzVlMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qe9GmAQQ50vq79UufczEbErZV_B_0W6uXvml9XgAcmE)


> 
Resuelto
> Me he encontrado el módulo de centros oculto, pero no el subpanel. Si se quiere desplegar el módulo oculto, también habría que incluir el script para ocultar los subpaneles (como se hizo con el Journal por ejemplo) 

Se incluyó en el despliegue de Centros.

> Cuando estoy en "Recursos", puedo acceder al calendario de reservas pero no tengo la opción del calendario de plazas 

Esto es a propósito: el de plazas se muestra desde la vista de plazas, y el de reservas desde la de reservas.

> Cuando estoy en recursos, me muestra la opción de mostrar plazas aunque el módulo no esté activo 

Resuelto
> Sigue no mostrándome bien algunos recursos
> ![image](https://private-user-images.githubusercontent.com/57436616/462419996-3bc266b2-643b-4854-9273-c480d8033108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxNDc0NjIsIm5iZiI6MTc1MjE0NzE2MiwicGF0aCI6Ii81NzQzNjYxNi80NjI0MTk5OTYtM2JjMjY2YjItNjQzYi00ODU0LTkyNzMtYzQ4MGQ4MDMzMTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDExMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNzgwYTI3NTM4OTM0MTRhY2FiNzUyZWE3NzY5ZGZmMDMwYmFhNTI1MDk4NTNmMWRiMGYyYjFiOTA0ZTQ0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3TonbqdDoK_-c0ZbtHK6E5qZNYhraV-I8E92Jhj36ts)
> 
> ![image](https://private-user-images.githubusercontent.com/57436616/462419913-8e7fe21c-3fc2-4902-8241-f7cb35c75568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxNDc0NjIsIm5iZiI6MTc1MjE0NzE2MiwicGF0aCI6Ii81NzQzNjYxNi80NjI0MTk5MTMtOGU3ZmUyMWMtM2ZjMi00OTAyLTgyNDEtZjdjYjM1Yzc1NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDExMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYTRjMmYxM2VkZDgxZDQwN2Y1NzkzZjg4Y2I0NWIxMDgwN2QzZGI4ZDkzMDRkZjQxZTdiZjBkZDYxYjBiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.28AZmWGH8QXqwSxYGt-8Hxp15Hrhl-dyCmSgW6ZZVkk)

Resuelto

> Sigue habiendo algún problema cuando elimino un recurso que tenía en una reserva: creo una reserva con el R1. La edito, borro el R1 de la lista, busco de nuevo en el Centro y me dice que no hay plazas.

Resuelto, no se estaba eliminando de la lista de recursos, solo se eliminaba visualmente.

2025-07-10 13:15 UTC, enricsinergia requested changes
Ver comentarios

2025-07-10 13:15 UTC, enricsinergia commented on modules/stic_Bookings/controller.php
> +        $resourceGenderCondition = $this->createFilterCondition($resourceGender, 'gender', $db);
Veo que la condición que se genera es un  AND (gender LIKE '%men%' OR gender = '') entiendo que es porqué es un campo multienum, pero en ese caso creo que sería mejor tener un '%^men^%, así si en algún momento se crea algún valor que comparta raíz con alguno de los existentes no dará problemas

2025-07-10 13:15 UTC, enricsinergia commented on modules/stic_Bookings/controller.php
> +                if ($numberOfPlaces && $totalCenters >= (int)$numberOfPlaces) {
Esta es la condición que está haciendo que no te encuentre el recurso. No acabo de entender qué es este totalCenters, perocuando llega al recurso adecuado vale 1 que es el número d eplazas que buscamos y hace el break en lugar de mirar la disponibilidad

2025-07-11 11:27 UTC, PaulaaSTIC commented on modules/stic_Bookings/controller.php
> +                if ($numberOfPlaces && $totalCenters >= (int)$numberOfPlaces) {
Corregido

2025-07-11 11:27 UTC, PaulaaSTIC commented on modules/stic_Bookings/controller.php
> +        $resourceGenderCondition = $this->createFilterCondition($resourceGender, 'gender', $db);
Corregido

2025-07-11 15:36 UTC, enricsinergia commented
Me deja entrar una fecha final prevista anterior a la fecha incial prevista

Revisar mensaje de error "Valor no vàlid: No es pot desar: la reserva conté una combinació de tipus de recursos (places i no places). Si us plau, selecciona només places o només recursos que no siguin places.". Aparece cuando tengo un sólo recurso pero no es del tipo correcto. Quizás debería ser algo más del estilo "hay recursos del tipo incorrecto para este tipo de reserva"

Si tengo un recurso que había tenido una reserva (se ha borrado la reserva) no me deja cambiar el tipo de std a plaza o viceversa (debe faltar un delete = 0 en algún where)

Cuando buscamos plazas, le damos a añadir y no nos añade todas las que hemos pedido, estaría bien indicarlo con un mensaje

Si cambio las tarifas de un recurso, los importes de las reservas se mantienen como estaban. ¿No deberían recalcularse los a futuro? De igual forma, una reserva ya vencida, no debería cambiar la tarifa aunque cambie el precio de los recursos (ahora se recalcula si la edito).
Si "cierro" un recurso de una reserva no se recalcula hasta que se edita la reserva.

La comprobación de hora en el cambio de horario invierno/verano no funciona correctamente. Tengo una reserva que empieza el 30/3/25 a las 03.00. Si intento modificar una que tenía hasta el 29/3 para que llegue hasta el 30/03/25 a las 02.00 me da error. Si le digo hasta la 1 lo deja entrar.

Estoy entrando los datos de una reserva, pongo fechas 1/8 y 3/8 a las 11.00. Veo que en realidad quería todo el día. Si clico en "todo el día" me cambia la fecha al día 2. Si vuelvo a desclicar, me queda el día 2/8 a las 11.

Si manualmente añado un recurso a una reserva que ya estaba presente, no se queja, pero al guardar se pierde una de las 2 relaciones.... conclusión, esa quinta plaza que he añadido manualmente, no queda registrada y no me entero que me ha quedado la reserva con un recurso de menos si no miro el subpanel

Si dentro de la edición de la reserva, elimino un recurso, y vuelvo a buscar en su centro, no me lo encuentra para devolverlo a la reserva.

Cuando edito una reserva que tiene plazas asignadas, no sé si estaría bien que los centros de las plazas asignadas estuvieran ya cargados por defecto


No me están apareciendo los iconos de los módulos de plazas.

En el calendario de recursos, me están apareciendo reservas de plazas
<img width="1035" height="575" alt="image" src="https://github.com/user-attachments/assets/3eb9a880-05bc-4d35-887c-0dfa7cea050e" />
<img width="1035" height="483" alt="image" src="https://github.com/user-attachments/assets/817d1355-c139-4143-acb6-c410005e1309" />

2025-07-11 15:42 UTC, enricsinergia commented
Incluyo el plan de pruebas realizado (lástima que no se preservan los colores para identificar todo lo que SÍ funciona) :

**Creación / edición de recursos**
Crear recurso std
Crear plaza
Intentar convertir std en plaza
Intentar convertir plaza en std
Repetir 3 y 4 con el recurso/plaza ya usado
Borrar recursos (std y plaza), estando reservado o no
Comprobar campos obligatorios distintos en recurso y plaza
**Creación de reservas**
Crear reserva con recursos std
Crear reserva con plazas
Jugar con las fechas previstas y reales, en futuro y pasado
Ignorar primero las previstas, poner enpasado y en futuro
Poner las previstas, en pasado y en futuro
Editar fechas previstas, en pasado y futuro
Editar fechas reales, en pasado y futuro
Editar fechas para provocar conflictos
Editar previstas x futuro,pasado
Editar reales x futuro, pasado
Crear reserva sin recursos (std y de plazas)
Crearla inicialmente
Borrarle luego los recursos
Intentar asignar recursos del tipo incorrecto de la reserva (std si es reserva de plazas y viceversa)
Con ventana pop-up
Con el autocompletar
Plazas a reserva std, recursos a reserva plazas
Revisar importes de las reservas
STD
Cambiar fechas
Cambiar precio recurso
Cambiar recurso
Plazas
Cambiar fecha
Cambiar precio recurso
Cambiar recurso
Asignar manualmente un recurso comprometido en las fechas 
Horas normales
Horas límite de día 
Horas límite de cambio de horario
**Búsqueda de plazas**
Reserva sin filtros
Reseva con cada uno de los filtros
Añadir recursos a una reserva
Reserva que necesita recursos de más de un centro
Añadir, quitar y volver a añadir recursos a una reserva
Comprobar que encuentra el recurso cuando hay 
Reseva borrada

**Calendarios**
Comprobar que reservas de recursos y plazas se muestran en su propio calendario
Comprobar calendario plaza cuando se cancela una reserva
Comprobar cal. plaza cuando se cierra un recurso en una reserva
Comprobar calendario cuando se borra una plaza

2025-07-14 11:31 UTC, enricsinergia requested changes
Ver comentarios de código

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Bookings/views/view.detail.php
> +        if ($this->bean->place_booking==0) {
¿Por qué printamos el script en lugar de incluirlo en un fichero js?

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Bookings/controller.php
> +        $timeZoneOffsetHourStartDate = $startDate ? $dateTimeZone->getOffset(new DateTime($startDate)) / 3600 : 0;
¿Cuando se puede producir que lleguemos aquí sin startDate ni endDate? ¿Tiene sentido? La SQL que se genera para comprobar availability queda sin fechas !¡

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Bookings/controller.php
> +            $response['options'][] = array('value' => $value, 'label' => $label);
Yo no enviaría el json con options, options2 y options3. Creo que se puede poner el nombre de la lista o del campo y, sobretodo si hay modificaciones añadiendo o quitando campo más adelnate, aumentará la legibilidad del código JS asociado.

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Bookings/controller.php
> +            $existingBooking = $GLOBALS['db']->getOne("SELECT COUNT(*) FROM stic_bookings WHERE name = '{$uniqueName}' and deleted =0");
En este caso no sé si pondŕia el "deleted = 0". Tal como está ahora si cierro varios recursos, se generan las .1, .2, .3 .... si borro una de estas reservas gneeradas, aprovechará luego el agujero dejado.

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Bookings_Places_Calendar/Utils.php
> +    public static function getAllPlaces()
No acabo de ver esta función. Parece que siempre devuelve un array vacío. ¿Es para forzar que se carguen los literales?

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Bookings_Places_Calendar/controller.php
> +            SELECT
¿Esta query no debería recoger sólo recursos de tipo "place"?

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Resources/views/view.list.php
> +            $savedSearchName = empty($_REQUEST['saved_search_select_name']) ? '' : (' - ' . $_REQUEST['saved_search_select_name']);
Esta variable no se está usando.

2025-07-14 11:31 UTC, enricsinergia commented on modules/stic_Resources/views/view.listplaces.php
> +            $savedSearchName = empty($_REQUEST['saved_search_select_name']) ? '' : (' - ' . $_REQUEST['saved_search_select_name']);
ídem. Variable sin usar

2025-07-14 16:37 UTC, PaulaaSTIC commented on modules/stic_Resources/views/view.listplaces.php
> +            $savedSearchName = empty($_REQUEST['saved_search_select_name']) ? '' : (' - ' . $_REQUEST['saved_search_select_name']);
Eliminada

2025-07-14 16:37 UTC, PaulaaSTIC commented on modules/stic_Resources/views/view.list.php
> +            $savedSearchName = empty($_REQUEST['saved_search_select_name']) ? '' : (' - ' . $_REQUEST['saved_search_select_name']);
Eliminada

2025-07-14 16:38 UTC, PaulaaSTIC commented on modules/stic_Bookings/controller.php
> +            $existingBooking = $GLOBALS['db']->getOne("SELECT COUNT(*) FROM stic_bookings WHERE name = '{$uniqueName}' and deleted =0");
Modificado

2025-07-14 16:38 UTC, PaulaaSTIC commented on modules/stic_Bookings/views/view.detail.php
> +        if ($this->bean->place_booking==0) {
Cambiado al case details del Utils.js

2025-07-15 16:36 UTC, PaulaaSTIC commented on modules/stic_Bookings_Places_Calendar/Utils.php
> +    public static function getAllPlaces()
Eliminada, ya no se usa

2025-07-15 16:49 UTC, PaulaaSTIC commented on modules/stic_Bookings/controller.php
> +            $response['options'][] = array('value' => $value, 'label' => $label);
Cambiado

2025-07-16 08:26 UTC, PaulaaSTIC commented on modules/stic_Bookings_Places_Calendar/controller.php
> +            SELECT
Modificada

2025-07-16 10:07 UTC, enricsinergia requested changes
Un par de detalles encontrados:

Subpanel de recursos en vista detalle de reserva: muestra siempre los precios de reserva estándard y no los precios de plaza. Si no se puede hacer que las columnas varíen en función del tipo de reserva, quizás quitaría los campos porqué elusuario puede pensar que es una incidencia que se muestren vacíos.

Al seleccionar  plazas al crear la reserva parece que falta un deleted = 0 ya que me recupera una plaza que está borrada.

2025-07-16 15:24 UTC, ainaraRT requested changes
Ver comentarios en código.
Además, cuando se añade otra plaza en una reserva que ya tenía una plaza previa, con la tarifa total/copago ya calculada de la primera plaza, al guardar la reserva con las dos plazas, no calcula las nuevas tarifas con las plazas que haya.

2025-07-16 15:24 UTC, ainaraRT commented on modules/stic_Bookings_Calendar/Utils.js
> +          mobile: SUGAR.language.get("stic_Bookings_Calendar", "LBL_MOBILE_BUTTON"),
No veo que esto funcione, ya que esas cadenas parecen "inexistente" en el módul, haciendo que no se muestre bien los botones.
<img width="1425" height="747" alt="Captura desde 2025-07-16 16-29-55" src="https://github.com/user-attachments/assets/4334bb06-d441-454c-a8ff-603ba5a6090c" />

Además, hay un bug en el calendario, que cuando se quiere cambiar de mes con las flechas, no funciona y se añade el botón de información por cada clic en las flechas.
![bug-calendario-reservas](https://github.com/user-attachments/assets/3ebe446d-46ed-4a8b-a678-59e9a4e14460)

2025-07-16 15:24 UTC, ainaraRT commented on modules/stic_Centers/metadata/subpaneldefs.php
> +$layout_defs[$module_name]["subpanel_setup"]['stic_resources_stic_centers'] = array(
Un detalle insignificante, habría que añadir el comentario de `// Bookings subpanel` antes de la definición

2025-07-16 19:16 UTC, PaulaaSTIC commented on modules/stic_Bookings_Calendar/Utils.js
> +          mobile: SUGAR.language.get("stic_Bookings_Calendar", "LBL_MOBILE_BUTTON"),
Corregidos los botones

2025-07-16 19:16 UTC, PaulaaSTIC commented
> Ver comentarios en código. Además, cuando se añade otra plaza en una reserva que ya tenía una plaza previa, con la tarifa total/copago ya calculada de la primera plaza, al guardar la reserva con las dos plazas, no calcula las nuevas tarifas con las plazas que haya.

Para que se actualice el importe se debe de eliminar primero el valor del importe, funciona como el campo nombre.

2025-07-16 19:18 UTC, PaulaaSTIC commented on modules/stic_Centers/metadata/subpaneldefs.php
> +$layout_defs[$module_name]["subpanel_setup"]['stic_resources_stic_centers'] = array(
Añadido

2025-07-16 19:19 UTC, PaulaaSTIC commented
> Un par de detalles encontrados:
> 
> Subpanel de recursos en vista detalle de reserva: muestra siempre los precios de reserva estándard y no los precios de plaza. Si no se puede hacer que las columnas varíen en función del tipo de reserva, quizás quitaría los campos porqué elusuario puede pensar que es una incidencia que se muestren vacíos.
> 
> Al seleccionar plazas al crear la reserva parece que falta un deleted = 0 ya que me recupera una plaza que está borrada.

Se han añadido los precios de plazas al subpanel y se ha modificado la query

2025-07-18 15:28 UTC, ainaraRT submitted a review, later dismissed
(A)Probado. Bugs corregidos y código correcto :)

2025-07-22 07:46 UTC, enricsinergia commented on modules/stic_Bookings/stic_Bookings.php
:clap:

2025-07-23 08:02 UTC, enricsinergia approved these changes
(A)probado

2025-07-23 08:41 UTC, ainaraRT submitted a review, later dismissed
(A)Probado

2025-07-23 10:05 UTC, enricsinergia submitted a review, later dismissed
(A)probado

2025-07-28 10:24 UTC, closed without merging

2025-07-29 15:21 UTC, enricsinergia approved these changes
(A)probado

2025-07-29 15:43 UTC, ainaraRT approved these changes
(A)Probado