Enhancement - Traducciones - Traducciones 202405
SinergiaTIC/SinergiaCRM pull request #219
Opened 2024-04-29 16:10 UTC by jalbaiges

2024-11-19 12:54 UTC, ainaraRT commented on modules/Administration/language/es_ES.lang.php
>      'LBL_AOP_BUSINESS_HOURS_DESC' => "Restringir el flujo de trabajo para lanzar solo en ciertos días y horas",
Debería de llevar comillas simples como se hace en todo el fichero

2024-11-19 13:00 UTC, ainaraRT commented on modules/EmailMan/language/es_ES.lang.php
>      'LBL_ALLOW_DEFAULT_SELECTION' => "Los usuarios pueden enviar como identidad de esta cuenta:",
`'LBL_ALLOW_DEFAULT_SELECTION' => "Los usuarios pueden enviar como identidad de esta cuenta:",`
Debería de ir en comillas simples como se hace en todo el documento.

2024-11-19 13:06 UTC, ainaraRT requested changes
Ver comentarios

2024-11-19 13:20 UTC, jalbaiges commented on modules/EmailMan/language/es_ES.lang.php
>      'LBL_ALLOW_DEFAULT_SELECTION' => "Los usuarios pueden enviar como identidad de esta cuenta:",
Ver respuesta anterior: https://github.com/SinergiaTIC/SinergiaCRM/pull/219#discussion_r1848348279

2024-11-19 13:24 UTC, ainaraRT submitted a review, later dismissed
(A)Probado

2024-11-20 08:03 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-11-20 08:31 UTC, ainaraRT approved these changes

2024-11-20 10:09 UTC, merged