Enhancement - Vistas Personalizadas - Pequeñas mejoras de usabilidad
SinergiaTIC/SinergiaCRM pull request #234
Opened 2024-05-09 16:50 UTC by jordiSTIC

- Closes #200

2024-05-10 08:07 UTC, jalbaiges approved these changes
Cadenas revisadas.

2024-05-27 14:44 UTC, enricsinergia submitted a review, later dismissed
(A)provado

El background de todo el campo se ve un poco raro, pero con el layout de SuiteCRM tampoco veo mucha alternativa
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/57436616/732b77b2-de33-4fcb-9fa6-6102dde6a4fd)

2024-05-28 09:44 UTC, juanSTIC requested changes
Ver comentario

2024-05-28 09:44 UTC, juanSTIC commented on modules/stic_Custom_Views/stic_Custom_Views_ModuleView.php
> +                    case 'underline':
En la vista de detalle, si se establece subrayado para todo el campo, al cargar la VP se muetsra subrayada la etiqueta, pero no la casilla. 
Tras editar inline, sí se muestra subrayada la casilla, pero si se recarga la página vuelve a perder el subrayado.

Solo ocurre en los campos de texto. En los desplegables funciona correcatmente

2024-05-29 08:00 UTC, jordiSTIC commented on modules/stic_Custom_Views/stic_Custom_Views_ModuleView.php
> +                    case 'underline':
Parece ser un error en el subrayado de la casilla de campos de texto en la vista de detalle: al aplicar "subrayado a todo el campo", se aplican las acciones "subrayado a la etiqueta" + "subrayado a la casilla".
La acción de subrayado a la casilla no tiene el comportamiento esperado en este tipo de campos en la vista detalle.

2024-05-29 16:22 UTC, jordiSTIC commented
> (A)provado
> 
> El background de todo el campo se ve un poco raro, pero con el layout de SuiteCRM tampoco veo mucha alternativa ![image](https://private-user-images.githubusercontent.com/57436616/334140663-732b77b2-de33-4fcb-9fa6-6102dde6a4fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Njk0MjIsIm5iZiI6MTcxNjk2OTEyMiwicGF0aCI6Ii81NzQzNjYxNi8zMzQxNDA2NjMtNzMyYjc3YjItZGUzMy00ZmNiLTlmYTYtNjEwMmRkZTZhNGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA3NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOWYxODcwNjAxZmFhZGJmNWFlY2ZmODljZDIwODQ3ZDE2NWViM2Q5MjhiM2NjNTI1YTMwZWQwNDllODBlMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDql0TfPVN9z-vPMhSLLBchpR4aFKkPojBUDAnzRrXg)

Se ha realizado un cambio para que el layout de todo el campo sea más "natural":
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/126675190/71de9197-7a84-41c6-8d34-84132c6f1f4e)

![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/126675190/930e62ab-f3cc-40b2-abcb-4f13d88986a2)

2024-06-03 05:09 UTC, enricsinergia approved these changes
(A)provado

Sólo 2 nimiedades que no evitan el aprovado:
- El tema del sort que se ha retirado
- El background en campos textarea sigue sin ser perfecto, aunque sí aceptable

2024-06-03 05:09 UTC, enricsinergia commented on modules/stic_Custom_View_Customizations/metadata/subpanels/default.php
> -    'sort_order' => 'asc',
¿Por qué se han eliminado estos atributos?

2024-06-03 07:43 UTC, jordiSTIC commented on modules/stic_Custom_View_Customizations/metadata/subpanels/default.php
> -    'sort_order' => 'asc',
Porque se ignoraban y se aplicaba el orden definido en modules/stic_Custom_Views/metadata/subpaneldefs.php, en el que se ha corregido el nombre de la columna

2024-06-03 07:48 UTC, jordiSTIC commented
> * El background en campos textarea sigue sin ser perfecto, aunque sí aceptable
> 
> ![image](https://private-user-images.githubusercontent.com/57436616/335944661-aec48f1a-4de1-46fc-bff3-eea12cbfdb70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDA5ODEsIm5iZiI6MTcxNzQwMDY4MSwicGF0aCI6Ii81NzQzNjYxNi8zMzU5NDQ2NjEtYWVjNDhmMWEtNGRlMS00NmZjLWJmZjMtZWVhMTJjYmZkYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA3NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzODMyZTdlODA1MGNmODk1MjgyNTBiOTQ5MTBhZjlmNDg2MDg3NzEwMmRhNTRkNjhjYjNjNGJmYzFhYjVmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YM86MMc2NarZEltZ0xmYkyLz28Iw2UXtOlFyqRztebw)

Sí, el background de la etiqueta de un campo con editores multilínea (text area, opción, selección múltiple no selectize, etc) no ocupa el alto del editor. Se tendría que modificar "al vuelo" el DOM del layout sin afectar la apariencia global de la vista

2024-06-03 08:45 UTC, jordiSTIC commented
> (A)provado
> 
> * El background en campos textarea sigue sin ser perfecto, aunque sí aceptable
> 
> ![image](https://private-user-images.githubusercontent.com/57436616/335944661-aec48f1a-4de1-46fc-bff3-eea12cbfdb70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDQzMTUsIm5iZiI6MTcxNzQwNDAxNSwicGF0aCI6Ii81NzQzNjYxNi8zMzU5NDQ2NjEtYWVjNDhmMWEtNGRlMS00NmZjLWJmZjMtZWVhMTJjYmZkYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA4NDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDA0NzVkMWQ2ZGI4ZjlmZTQ0YzEzN2Y0NjJjNTdjN2RhOTk3NDVmNGI3ZmU2MDI4YjM4ZTE1YTBiMTYwNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hPOMJzgVR4c_m6MIj4PavkvpKtIM2aoNiQTmQ0kUxSY)

Se han realizado pequeñas modificaciones para que la etiqueta de un campo ocupe el mismo alto que el editor asociado:
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/126675190/07b95331-444b-47c3-b5a9-41dbb16032cf)
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/126675190/dae19112-5b71-406e-a726-fc5547ac73bd)
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/126675190/bb40f579-c91e-46de-a279-a73963aaf736)

2024-06-03 15:24 UTC, enricsinergia approved these changes
(A)provado

2024-06-03 15:58 UTC, juanSTIC approved these changes

2024-06-04 08:17 UTC, merged