Hotfix - Vistas Personalizadas - Comportamiento anómalo al indicar campo "Solo lectura" y "Visible"
SinergiaTIC/SinergiaCRM pull request #236
Opened 2024-05-10 12:33 UTC by jordiSTIC

- Closes #217 

###  Descripción
Se ha detectado que en Vistas Personalizadas, al indicar una acción que fuerce la visibilidad de un campo que se ha marcado como "solo lectura", se muestra el editor del campo y un texto con el contenido del editor

El problema estaba en que al marcar como "solo lectura", se crea un elemento con el texto a mostrar y se ocultaba el elemento de edición del campo, y al marcarlo como Visible, se forzaba la visualización del elemento de edición

### Solución propuesta
En la estructura DOM de la vista, en el campo que se accede para modificarse por Vistas Personalizadas, se crea un elemento contenedor que incluye el elemento correspondiente al editor del campo y al correspondiente al texto mostrado en caso de "solo lectura".
Al ejecutar la acción de "solo lectura", se modificará la visibilidad del texto y el editor
Al ejecutar la acción de "visible", se modificará la visibilidad del nuevo contenedor con el texto y el editor

### Pruebas a realizar
1. Crear una Vista Personalizada del módulo Personas, en la Vista de Edición
2. Agregar una acción con: 
   - Modificación de campo - Apellidos - Solo lectura - Sí
   - Modificación de campo - Apellidos - Visible - Sí
3. Editar un registro de Persona
4. Verificar que el campo "Apellidos" se visualiza correctamente y no aparece su editor

Alternativamente:
- Crear acciones que modifiquen la visibilidad de un campo en función del valor de otro
- Crear una acción que modifique "solo lectura" del mismo campo, en función de otras condiciones
- Editar un registro del módulo afectado por la Vista Personalizada
- Realizar combinaciones para que se modifique la visibilidad y "solo lectura" del campo 
- Verificar que el comportamiento es el esperado

2024-05-27 15:00 UTC, enricsinergia requested changes
El código del PR fuciona perfectamente, pero se ha detectado una anomalía con los readonly en textarea: no se visualizan los retornos de carro cuando el campo textarea semarca como readonly

2024-05-27 16:45 UTC, jordiSTIC commented
> El código del PR fuciona perfectamente, pero se ha detectado una anomalía con los readonly en textarea: no se visualizan los retornos de carro cuando el campo textarea semarca como readonly

Se ha solucionado el problema de los retornos de carro: para ello, en el div del texto no editable, se añaden los saltos de línia (<br>) correspondientes

2024-05-28 05:28 UTC, enricsinergia approved these changes
(A)provado

2024-05-28 12:37 UTC, jordiSTIC commented on modules/stic_Custom_Views/processor/js/sticCVUtils.js
> +        fieldContent.$readonlyLabel.append("<br>");
Hecho

2024-05-28 13:40 UTC, ManuSinergiaCRM approved these changes
(A)probado 

- Probado a nivel funcional
- Código revisado a nivel sintáctico

2024-05-28 14:34 UTC, enricsinergia approved these changes
(A)provado

2024-05-30 07:09 UTC, merged