Hotfix - Registro horario y Calendario laboral - Incidencias post despliegue
SinergiaTIC/SinergiaCRM pull request #268
Opened 2024-06-11 19:09 UTC by ManuSinergiaCRM

- Closes #267

## Descripción

[EN PROCESO]

## Pruebas

**Incidencia 1**
1. Acceder con un usuario administrador y comprobar que los checkboxs son editables en la vista de Edición.
2. Crear un usuario que sea no administrador y salir de la sesión del CRM.
3. Acceder con el usuario NO administrador y comprobar que los checkboxs NO son editables en la vista de Edición.

**Incidencia 2**
1. Ir al módulo de Registro horario y eliminar todos los registros del usuario logueado
2. Crear un registro con fecha y hora de inicio anterior a 24h y comprobar que el botón se muestra en verde.
3. Modificar la fecha y hora de inicio para que no sea anterior a 24h y comprobar que el botón se muestra en rojo
4. Cerrar el registro y comprobar que el botón se pinta de verde

**Incidencia 3**
1. Crear un registro de Calendario laboral de tipo Laborable de 9h a 18h
2. Duplicar el registro y comprobar que al guardar salta la validación de tipos incompatibles
3. Modificar la *fecha y hora de inicio* a las 18:01 y comprobar que al guardar ya NO salta la validación de tipos incompatibles
4. Modificar la *fecha y hora de finalización* a las 8:59 y comprobar que al guardar ya NO salta la validación de tipos incompatibles
5. Modificar la *fecha y hora de inicio* a las 18:00 y comprobar que al guardar SÍ salta la validación de tipos incompatibles
4. Modificar la *fecha y hora de finalización* a las 9:00 y comprobar que al guardar SÍ salta la validación de tipos incompatibles

**Incidencia 4**
1. Crear un usuario no administrador
2. Acceder al CRM y comprobar que tenemos acceso a la acción de **Generar Calendario laboral** desde la vista de detalle de un Empleado
3. Crear un rol donde configurar la opción de Editar a Nada para el módulo de Calendario laboral
4. Añadir el usuario al rol
5. Salir y volver a acceder al CRM y comprobar que ya **NO** tenemos acceso a la acción de **Generar Calendario laboral** desde la vista de detalle de un Empleado

2024-06-14 09:15 UTC, enricsinergia commented on custom/modules/Users/SticUtils.js
> +        debugger;
No soy el único que se deja "debugger"s ;-)

2024-06-14 09:26 UTC, enricsinergia commented on modules/stic_Time_Tracker/stic_Time_Tracker.php
> +            AND TIMESTAMPDIFF(SECOND, CONVERT_TZ(start_date, '+00:00', '" . $tzone . "'), NOW()) < 86400
Entiendo el tema de las 24 horas, pero no sé si soluciona realmente el problema o nos crea otro.
Me explico:
 - En personas con un turno de 24 horas (que las hay, aunque muy pocas), este cambio a las 24 nos funde, porqué si sale 5 minutos tarde (profesional comprometido al que no se le cae el lápiz), ya le habrá cambiado el botón.
 - En personas con jornadas "normales", si ayer llegué a las 9.05 y me olvidé de fichar al salir, hoy no podré fichar de entrada hasta las 9.05 aunque llegue a las 8.30 (sí que puedo si cierro el anterior y abro uno nuevo, claro)

 Alternativas (quizás para más adelante):
 - Configuración general para marcar el número de horas a las que se "cierra" un fichaje abierto
 - Lo mismo que la anterior pero a nivel de usuario
 - Utilizar la jornada determinada por el calendario laboral en el día de inicio del marcaje más un % para "cerrar" el marcaje

2024-06-14 10:05 UTC, enricsinergia requested changes
Incidencia 1 -> Error al desactivar (ver comentario código)
Incidencia 2 -> Checked
Incidencia 3 -> Checked
Incidencia 4 -> Checked
Incidencia 5 -> Checked
Incidencia 6 -> Checked

2024-06-14 12:37 UTC, ManuSinergiaCRM commented on custom/modules/Users/SticUtils.js
> +            document.getElementById('stic_clock_c').disabled = 1;
Campos escondidos en vez de deshabilitados

2024-06-14 13:56 UTC, ManuSinergiaCRM commented on modules/stic_Time_Tracker/stic_Time_Tracker.php
> +            AND TIMESTAMPDIFF(SECOND, CONVERT_TZ(start_date, '+00:00', '" . $tzone . "'), NOW()) < 86400
El caso de uso de jornadas de más de 24h ni lo había pensado 😅

- Como dices, tb pienso que es un caso poco probable, y creo que no debería bloquear el cambio propuesto en el PR.

- El segundo caso si se ha contemplado y sí, tendría que cerrar el registro abierto del día anterior para poder empezar otro fichaje nuevo. 

Y todo esto ocurre si la entidad no permite la edición de sus propios registros a los empleados, si no, siempre tendrán la posibilidad de modificar el registro abierto antes de comenzar el nuevo fichaje. 

Por último, por ahora anotaría lo que dices para valorarlo en una fase dos y que no influya en el PR. 
A ver que dice Alberto! 

Gracias :+1:

2024-06-14 13:57 UTC, ManuSinergiaCRM commented on custom/modules/Users/SticUtils.js
> +        debugger;
Eliminado

2024-06-17 05:25 UTC, enricsinergia approved these changes
(A)provado

2024-06-17 15:39 UTC, PaulaaSTIC requested changes
Incidencia 4.
Un usuario con un rol de Editar a Nada para el módulo de Calendario laboral puede ver **Generar Calendario laboral** desde la vista de detalle de su usuario.

2024-06-17 16:01 UTC, ManuSinergiaCRM commented
> Incidencia 2. Si generamos un **registro horario** en el **futuro**, el **botón** se muestra en **rojo**. Si lo pulsamos, la fecha de fin será anterior a la fecha de inicio.
> 
> Incidencia 4. Un usuario con un rol de Editar a Nada para el módulo de Calendario laboral puede ver **Generar Calendario laboral** desde la vista de detalle de su usuario.

Hecho!

2024-06-17 16:26 UTC, PaulaaSTIC approved these changes
(A)probado

2024-06-18 05:04 UTC, enricsinergia submitted a review, later dismissed
(A)provado

2024-06-18 10:47 UTC, enricsinergia approved these changes
(A)provado

2024-06-18 11:59 UTC, PaulaaSTIC approved these changes
(A)probado

2024-06-19 07:42 UTC, merged