Improvements - SinergiaDA - Algunas mejoras
SinergiaTIC/SinergiaCRM pull request #280
Opened 2024-06-20 06:47 UTC by juanSTIC

## Exclusión del módulo Vistas personalizadas
Se excluye el módulo de vistas personalizadas del procesamiento

*Cómo probarlo*
Verificar que tras rebuild no existe la vista sda_stic_custom_views

2024-07-16 15:41 UTC, AlbertoSTIC commented
Varios temas sobre los campos virtuales:
- Arquitectura de los ficheros y contenido: diría que es la primera vez que nos vemos con la necesidad de añadir código en los módulos de SinergiaCRM que afecte directamente a una herramienta externa que no necesariamente deba de estar integrada. Aunque esta arquitectura no tiene porque afectar al resto de código, diría de seguir un patrón similar al que se utiliza en SuiteCRM. Hago directamente la propuesta y comentamos lo que sea necesario.
1- Añadir un fichero SDAvardef.php en los módulos que sea necesario e incluir allí la definición de todos los campos, a modo array/objeto similar a la definición de los vardef. De este modo, cualquier persona que conozca la estructura vardef de SuiteCRM podrá identificar fácilmente los campos
2- Para los módulos de SuiteCRM, o personalizaciones de las entidades, lo añadimos en Extensión con una [extensión custom](https://docs.suitecrm.com/developer/extension-framework/#_custom_extensions). La misma estrategia se ha aplicado con alguna otra adaptación de entidad. Seguría la ruta de `custom/Extension/modules/<módulo>/Ext/SDAvardef/SticSdaVardef.php`. 
3- Para finalizar, el sistema de rebuild tendrá que buscar ficheros existentes en `modules/<módulo>/SDAvardef.php` y en `custom/modules/<módulo>/Ext/SDAvardef/SDAvardefs.ext.php` o similar.

En unos inicios dudaba de si crear un nuevo tipo de campo en SinergiaCRM que se llamara "SdaVirtualField" y que se pudiera añadir/editar desde Estudio. Ya lo hemos hecho otras veces, como con el campo "ColorPicker". Pero en este caso, al ser un campo para una aplicación externa, no sé si tiene el mismo sentido. Si es necesario lo comentamos.

Sobre el uso de los campos virtuales propuestos:
- Campos de relaciones activas en el pasado: 
1- ¿Cuál es la limitación de SinergiaDA para no poder generar este filtro? ¿Es sobre el uso de los operadores "OR" y "AND" en las condiciones?¿Es algo que tenemos ya una propuesta de mejora en SDA?
2- ¿No se podría generar un sistema para filtrar en cualquier periodo del año? Sin limitar si hace 4 años, 2, o el año actual.

- Para los campos de pagos: Quizás tiene sentido reutilizar las etiquetas de los campos de Kreporter ya existentes. Este punto se lo dejo a @jalbaiges.

2024-07-16 15:42 UTC, AlbertoSTIC requested changes
Ver comentario anterior.

2024-07-16 17:25 UTC, jalbaiges commented
Por alusiones... ¿En qué contexto se visualizarán las cadenas de tipo _description_? Si realmente no fueran necesarias, eliminaría todas las cadenas SDA (las de campos y las de descripción) y me quedaría con las que ya existen para los campos virtuales de KReports.

Por lo demás, a favor de dar un repaso a los otros aspectos que comenta Alberto.

2024-07-17 06:00 UTC, juanSTIC commented
> * 1- ¿Cuál es la limitación de SinergiaDA para no poder generar este filtro? ¿Es sobre el uso de los operadores "OR" y "AND" en las condiciones?¿Es algo que tenemos ya una propuesta de mejora en SDA?

Sí, en este caso se trata justamente de la imposibilidad de combinar operadores y anidar diferentes condiciones (en el caso de las altas o bajas dependen de que la fecha sean anterior/posterior a.... o que no exista tal fecha). Aunque ya se está abordando, no parece que vaya a ser inmediato solucionarlo "completamente" en SinergiaDA, y esto además de la necesidad expresada por algunas entidades es lo que ha motivado incluir estos campos.

> * 2- ¿No se podría generar un sistema para filtrar en cualquier periodo del año? Sin limitar si hace 4 años, 2, o el año actual.

Espero que eso se pueda hacer mediante SinergiaDA cuando esté el sistema de filtros AND/OR completo en SinergiaDA, pero por ahora hemos atendido la necesidad más inmediata expresada, que se refiere al año actual y al año pasado y, puesto que solo se trataba de copiar, lo hemos extendido a cuatro años atrás.

> * Para los campos de pagos: Quizás tiene sentido reutilizar las etiquetas de los campos de Kreporter ya existentes. Este punto se lo dejo a @jalbaiges.

Sin duda podrían usarse las etiquetas de los campos de kreporter, pero lo que ha motivado a crear un juego de etiquetas distinto es que, justamente, las ya existentes inluyen la palabra Kreporter, cuando el uso en SDA nada tiene que ver con Kreports. Si lo véis claro, elimino las nuevas y usamos las ya existentes.


> ¿En qué contexto se visualizarán las cadenas de tipo _description_? Si realmente no fueran necesarias, eliminaría todas las cadenas SDA (las de campos y las de descripción) y me quedaría con las que ya existen para los campos virtuales de KReports.

En SinergiaDA, las columas de las tablas tienen una propiedad _Description_ que se muestra como un tooltip en en diseñador de informes y en la visualización de los mismos. Puesto que los campos de SinergiaCRM, por lo general no tienen descripción, lo habitual es que en este tooltip se muestre el propio nombre del campo, pero en los campos _calculados_, como estos que se incluyen y que no existen en SinergiaCRM, tiene sentido incluir información adicional, que explique qué es exactamente lo que se muestra.
![image](https://github.com/user-attachments/assets/1c0aba2a-c396-4af1-b8a9-dfd590debe0e)
![image](https://github.com/user-attachments/assets/b3009543-f842-44ec-8213-5c43ba01e4b4)

2024-07-17 15:03 UTC, AlbertoSTIC requested changes
Ver comentarios.

2024-07-17 16:14 UTC, juanSTIC commented on modules/stic_Payment_Commitments/language/ca_ES.lang.php
> +    'LBL_SDA_EXPECTED_PAYMENTS_DESCRIPTION_MONTH_12' => 'Import previst per al mes 12 a partir de l\'actual',
hecho

2024-07-19 17:50 UTC, PaulaaSTIC approved these changes
(A)probado

2024-08-19 08:36 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2024-08-19 08:49 UTC, AlbertoSTIC commented on custom/Extension/application/Ext/Extensions/SDAVardefs.php
Falta licencia.

2024-08-19 09:33 UTC, juanSTIC commented on custom/Extension/application/Ext/Extensions/SDAVardefs.php
hecho

2024-08-19 11:41 UTC, jalbaiges approved these changes
Cadenas revisadas.

2024-08-20 07:51 UTC, AlbertoSTIC approved these changes
Aprobado

2024-08-20 08:37 UTC, PaulaaSTIC approved these changes

2024-08-21 08:06 UTC, merged