Hotfix - Vistas Personalizadas - Aplicación de las Personalizaciones durante la edición inline en Vista Detalle
SinergiaTIC/SinergiaCRM pull request #292
Opened 2024-06-28 12:12 UTC by jordiSTIC

- Closes #276 

## Descripción
Tal y como se describe en el Issue #276, el comportamiento de las Vistas Personalizadas en una Vista de Detalle durante la edición Inline de un campo era distinto al comportamiento durante la edición en la Vista de Edición:
- En la vista de Edición se aplican las personalizaciones mientras el valor de un campo cambia
- En la vista de Detalle, cuando se editaba online, la personalización únicamente cambiaba cuando el usuario aceptaba el cambio de valor

Este PR soluciona el error, tratando la edición inline del mismo modo que la edición del campo en la vista de edición.

## Pruebas
1. Crear una VP sobre un módulo cualquiera y su Vista de Detalle (Por ejemplo: Personas)
2. Añadir una Personalización con una condición y una acción. Por ejemplo: Condición: "Nombre - Contiene - Valor - Test". Acción "Campo-Nombre - Color del fondo - Rojo - Todo el campo"
3. Visualizar un registro del módulo (Personas)
5. Mediante edición inline, modificar el campo para que cumpla la condición (Nombre: Test)
6. Verificar que mientras el editor inline está activo, se aplica la acción cuando la condición se cumple
7. Opcionalmente, repetir con otro tipo de campo

2024-07-10 09:31 UTC, enricsinergia submitted a review, later dismissed
(A)provado

2024-07-11 10:56 UTC, ManuSinergiaCRM requested changes
Veo que en diferentes tipos de campos sigue sin funcionar correctamente: 

- Multienum --> Funciona mientras se aplica el cambio inline pero deja de aplicarse al guardar el cambio

- Fecha --> No se aplica el cambio al indicar la fecha desde el calendario. Si escribo el valor si aplica.

- Fecha y hora --> Se aplica el cambio alguna vez pero falla en muchas ocasiones

2024-07-11 15:23 UTC, jordiSTIC commented
> Veo que en diferentes tipos de campos sigue sin funcionar correctamente:
> 
> * Multienum --> Funciona mientras se aplica el cambio inline pero deja de aplicarse al guardar el cambio
> * Fecha --> No se aplica el cambio al indicar la fecha desde el calendario. Si escribo el valor si aplica.
> * Fecha y hora --> Se aplica el cambio alguna vez pero falla en muchas ocasiones

Se han corregido los siguientes errores:
* Multienum: Se producía un error de js al leer los elementos seleccionados, que provocaba que las acciones siguientes no se ejecutasen. Se ha corregido, tanto para multienum como enum
* Fecha, Fecha y hora: En la edición inline se modifica la estructura del DOM, se define un MutationObserver para observar esta nueva estructura, pero no se escuchaban los eventos de cambio de los editores que crea la edición inline. Corregido.

Se observa un error en las condiciones de Fecha y hora: Se definen en hora local, se guardan en utc y el procesador de Vistas Personalizadas entiende la hora utc como local. (Pendiente de corrección)

2024-07-12 12:26 UTC, jordiSTIC commented
> Se observa un error en las condiciones de Fecha y hora: Se definen en hora local, se guardan en utc y el procesador de Vistas Personalizadas entiende la hora utc como local. (Pendiente de corrección)

Se ha creado el issue #302 para resolver la incidencia comentada con las Vistas Personalizadas con condiciones sobre un campo del tipo fecha y hora

2024-07-15 07:26 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-07-17 07:26 UTC, enricsinergia approved these changes
(A)provado

2024-07-23 15:13 UTC, merged