Feature - Grupos de seguridad - Gestión avanzada
SinergiaTIC/SinergiaCRM pull request #3
Opened 2024-01-02 08:47 UTC by juanSTIC

## Funcionalidades

### Activación de Funcionalidades
- La funcionalidad completa del módulo se activa o desactiva mediante el Setting `ENABLE_SECURITY_SUITE_ADVANCED` en SinergiaCRM.
- Si el Setting `ENABLE_SECURITY_SUITE_ADVANCED` está desactivado, los menús y el módulo no se mostrarán, y se desactivará el LogicHook `after_save` que aplica las reglas de herencia.

### Configuración Avanzada de Herencias Personalizadas
- **name:** Nombre del modulo de configuración. Identifica la configuración específica para un módulo.
- **inherit_assigned:** Permite definir si se heredan los Grupos de Seguridad del usuario asignado al registro.
- **inherit_creator:** Habilita la herencia de los Grupos de Seguridad del usuario que creó el registro.
- **inherit_parent:** Establece si se deben heredar los Grupos de Seguridad del registro padre en la jerarquía. Aunque este campo sea falso, si se han especificado módulos en `inherit_from_modules`, se heredarán los Grupos de Seguridad de los módulos indicados.
- **inherit_from_modules:** Campo de selección múltiple que determina no solo de qué módulos se deben heredar los Grupos de Seguridad, sino también la relación específica que se usará para llegar al módulo y heredar los Grupos de Seguridad del registro de destino. Funciona incluso si la herencia del registro padre está desactivada.
- **non_inherit_from_security_groups:** Campo de selección múltiple para especificar qué Grupos de Seguridad no deben ser heredados por el registro.

## Detalles Relevantes
- **Reglas de Herencia Custom y Estándar:**
  - Las reglas de herencia custom por módulo tienen prioridad sobre las reglas de herencia estándar de los Grupos de Seguridad aplicables a todos los módulos.
- **Vista de lista de reglas personalizadas**
  - Se ha creado una vista de lista custom que muestra todos (y exclusivamente) los módulos habilitados en el Menú.
  - Los registros en este módulo se crean de manera automática si no existen al cargar la vista.
  - No se permite la creación de nuevos registros manualmente.
  - En la vista de lista solo se mantienen las opciones de Actualización masiva y eliminar. En el caso de Eliminar, los registros vuelven a regenerarse de inmediato.
- **Acceso y Vista del Módulo:**
  - El acceso a la vista de lista del módulo está disponible en el menú "Configuración de Grupos de Seguridad" como un nuevo icono.
  - El módulo carece de Vista de detalle, ya que esta redirecciona automáticamente a la vista de edición.
- **Reglas de Grupos de Seguridad:**
  - Los Grupos de Seguridad marcados como "No heredable" mantienen este comportamiento.
  - Se mantiene la limitación de una relación por registro y Grupo de Seguridad.
- **Proceso de Aplicación de Reglas:**
  - Se ejecuta a través del LogicHook `after_save`.
  - Verifica y aplica las reglas definidas para nuevos registros. Este proceso se desactiva si `ENABLE_SECURITY_SUITE_ADVANCED` está desactivado.

2024-01-08 11:00 UTC, AlbertoSTIC requested changes
Ver comentarios en código.

¿Sería posible ordenar por defecto por la columna "Módulo" en la visa de lista de las reglas personalizadas?

Falta validación de funcionalidad.

2024-01-08 11:08 UTC, juanSTIC commented on modules/stic_Security_Groups_Rules/Utils.php
> +                                               AND securitygroups.noninheritable = 0");
Correcto. Añadido

2024-01-08 12:16 UTC, juanSTIC commented on modules/stic_Security_Groups_Rules/Utils.php
> +        $relID = $db->getOne("SELECT {$relatedID} FROM contacts_cstm WHERE id_c='{$bean->id}' LIMIT 1");
Revisar literal contacts_cstm

2024-01-08 17:14 UTC, jalbaiges requested changes
Las cadenas de uso reconocible en el interfaz han sido revisadas en todos los idiomas. Las cadenas de uso no reconocible han sido marcadas en el fichero del idioma catalán. En caso de que se confirme su no necesidad, deben ser borradas de todos los ficheros de idiomas.

Aparte de algún comentario indicado directamente en el código, apunto algunas cosas más que he visto al gestionar las traducciones. Ya valoraréis lo que proceda (igual no tengo toda la info en algún caso):

1. La opción incorporada a la configuración de SG para habilitar globalmente las reglas a nivel de módulo me parece innecesaria y potencialmente "conflictiva" en términos de experiencia de usuario con el campo Activo del nuevo módulo (aunque aparezca un mensaje de alerta). Creo que con este último basta y que se podría evitar la modificación de "SG Settings", además de no necesitar el mecanismo de alerta. 

2. El menú del nuevo módulo es inconsistente con, por ejemplo, el de GS. Teniendo en cuenta que el nuevo módulo es una especie de "submódulo" de GS y que además no permite otras opciones que no sean ir a la vista de lista (no permite crear ni importar) , podría usarse el mismo menú en ambos casos (en SG y en SGMR).

3. La vista de lista del nuevo módulo siempre envía a editview y nunca a detailview. Parece innecesariamente inconsistente con el funcionamiento general del CRM.

4. La lista de módulos en "Heredar solo de..." tiene contenidos "raros" (valores duplicados, referencias a relaciones/módulos que el usuario desconoce, etc.). Ya sabemos que esto suele suceder cuando se intenta automatizar la generación de un listado de módulos relacionados, pero igual puede afinarse.

5. ¿"Heredar solo de..." no debería ser incompatible con "Heredar de todos los registros padre"? Ergo, si se marca esta casilla, el multiselección debería vaciarse e inhabilitarse, y solo debería estar habilitado en caso de que la casilla no esté marcada.

2024-01-09 16:11 UTC, juanSTIC commented
> ¿Sería posible ordenar por defecto por la columna "Módulo" en la visa de lista de las reglas personalizadas?

hecho

2024-01-09 16:17 UTC, juanSTIC commented
> 1. La opción incorporada a la configuración de SG para habilitar globalmente las reglas a nivel de módulo me parece innecesaria y potencialmente "conflictiva" en términos de experiencia de usuario con el campo Activo del nuevo módulo (aunque aparezca un mensaje de alerta). Creo que con este último basta y que se podría evitar la modificación de "SG Settings", además de no necesitar el mecanismo de alerta.

Se ha tomado esta decisión por las siguientes razones:
- Si solo dejamos la posibilidad de desactivar las reglas en el campo _active_, y por cualquier razón es necesario desactivar la aplicación de las mismas, deberíamos establecerlas todas como `active=false` mediante actualización masiva, lo que implicaría perder la información de cuales estaban activas y cuales no.
- Si una entidad no usa este modelo de Reglas por módulo (lo cual sera lo habitual, en principio) no es necesario comprobar mediante SQL si hay una regla activada o no para cada registro que se guarde, lo que aligera la ejecución en alguna medida.

2024-01-09 16:26 UTC, juanSTIC commented
> 2\. El menú del nuevo módulo es inconsistente con, por ejemplo, el de GS. Teniendo en cuenta que el nuevo módulo es una especie de "submódulo" de GS y que además no permite otras opciones que no sean ir a la vista de lista (no permite crear ni importar) , podría usarse el mismo menú en ambos casos (en SG y en SGMR).

Hecho

2024-01-09 16:57 UTC, juanSTIC commented
> 3\. La vista de lista del nuevo módulo siempre envía a editview y nunca a detailview. Parece innecesariamente inconsistente con el funcionamiento general del CRM.

Propuesta aceptada

2024-01-09 16:59 UTC, juanSTIC commented
> 4\. La lista de módulos en "Heredar solo de..." tiene contenidos "raros" (valores duplicados, referencias a relaciones/módulos que el usuario desconoce, etc.). Ya sabemos que esto suele suceder cuando se intenta automatizar la generación de un listado de módulos relacionados, pero igual puede afinarse.

Se ha refinado la lista de módulos relacionados para que solo aparezcan aquellos que están activos en el CRM, por lo que problema se ha reducido en lo posible

2024-01-10 06:32 UTC, juanSTIC commented on modules/stic_Security_Groups_Rules/Utils.js
> +/**
De manera general, los ficheros JS están formateados con 2 espacios https://docs.suitecrm.com/community/contributing-code/coding-standards/#_indentation

2024-01-10 06:45 UTC, juanSTIC commented
> 5\. ¿"Heredar solo de..." no debería ser incompatible con "Heredar de todos los registros padre"? Ergo, si se marca esta casilla, el multiselección debería vaciarse e inhabilitarse, y solo debería estar habilitado en caso de que la casilla no esté marcada.

Aunque ya eran mutuamente excluyentes, ahora además, el control multiselect se muestra como desactivado siempre que el checkbox _Heredar de todos los registros padre_ esté activado.

2024-01-10 07:33 UTC, juanSTIC commented on custom/Extension/application/Ext/Language/ca_ES.SticLang.php
> +// Llista de regles d'herència SG
No se usa, así que se elimina de todos los idiomas

2024-01-10 07:36 UTC, juanSTIC commented on modules/stic_Security_Groups_Rules/language/ca_ES.lang.php
> +    'LBL_INHERIT_CUSTOM_RULES' => "Regles d'herència personalitzades",
No, se elimina de todos lo idiomas

2024-01-10 07:38 UTC, jalbaiges commented
> > 3. La vista de lista del nuevo módulo siempre envía a editview y nunca a detailview. Parece innecesariamente inconsistente con el funcionamiento general del CRM.
> 
> Propuesta aceptada
> 
> **Rectificación:** después de haber estado configurando las reglas de módulos durante el desarrollo del PR, al haber re-activado la vista de detalle, creo que se pierde en usabilidad, ya que no aporta (prácticamente) nada y supone un paso intermedio adicional para el usuario administrador. Se trata de un módulo _especial_, solo para administradores, y creo que es aceptable que carezca de vista de detalle, puesto que toda la información existente ya se muestra adecuadamente en la propia vista de lista y en la vista de edición. Dejo activada la vista de detalle, pero lo someto a vuestra opinión @jalbaiges, @AlbertoSTIC y @enricsinergia.

El usuario sigue teniendo la capacidad de acceder a la vista de edición en un solo clic mediante el icono del lápiz, que es el mecanismo habitual conocido, ergo no se produce penalización por mantener el estándar. Por otro lado, tengo entendido que el módulo ampliará su funcionalidad en fases posteriores de desarrollo, lo que puede llevar al escenario típico de no poder tener todos los campos en la vista de lista. En síntesis, apostaría de forma bastante indudable por mantener el comportamiento estándar.

2024-01-10 08:09 UTC, juanSTIC commented on custom/modules/SecurityGroups/config.php
> +echo get_module_title($mod_id, $mod_name . ": " . $mod_strings['LBL_CONFIGURE_SETTINGS'], false);
corregido

2024-01-10 08:09 UTC, juanSTIC commented on modules/SecurityGroups/SecurityGroup.php
> +
corregido

2024-01-10 11:25 UTC, enricsinergia requested changes
A falta de muchas más pruebas:
Si operamos con un usuario no admnistrador, aparecen errores "Acceso no autorizado a la administración."

Para reproducir (en la instancia develop): 
- Login con eps1 (o cualquier otro usuario no admin)
- Crear relación con personas
- Escogemos persona (test eps1)
- Al guardar se obtiene error
El error se lanza desde modules/stic_Security_Groups_Rules/Utils.php:32 (donde se está dando error si elque entra no es administrador), pero el fichero se requiere para realizar la herencia de cualquier usuario

2024-01-10 11:28 UTC, juanSTIC commented on modules/stic_Security_Groups_Rules/createRecordTest.php
> +<?php
cierto, eliminado

2024-01-10 17:42 UTC, enricsinergia requested changes
Realizadas diversas pruebas se detectan 2 temas:
A) Relaciones mostradas en el módulo de reglas
Al definir las reglas de herencia de un módulo, me aparecen relaciones que no deberían aparecer (aquellas en que el módulo relacionado tiene cardinalidad "muchos"), ya que nunca podrá heredar de ahí. Por ejemplo, una persona no podrá heradar nunca de un compromiso de pago.

B) Se duplican grupos relacionados
1. En Payment Commitments marcamos importar de Personas y de Persona destinataria
2. A Persona le asignamos los grupos G1 y G2
3. A persona destinataria los G1, G3 y G4
4. Creamos (desde vista edición) un CP, escogiendo las personas creadas
5. El registro resultante tiene 2 veces el grupo G1. En el subpanel sólo se muestra 1 vez pero el contador del subpanel indica 5 grupos en lugar de 4 y se puede verificar vía BBDD).

C) Grupo no heredable para un usuario
1. Creo un usuario y le asigno varios grupos heredables
2. En la vista de detalle de ese usuario, modifico la relación con un grupo para indicar que no es heradable (aunque el grupo en si, sí lo es)
3. Marco herencia de usuario creador para un módulo
4. Hereda todos los grupos del usuario, incluyendo el marcado para no heredar

Otras pruebas realizadas con resultado satisfactorio:
- Activación / desactivación de reglas custom general 
- Activación / desactivación de reglas para un módulo concreto
- No se heredan grupos no heredables
- Se muestran distintas relaciones con un mismo módulo 
- Poner todos los grupos que se heradarían como prohibidos
- Creación directa de registro
- Creación desde subpanel
- Si se marca heredar de una relación que no se rellena, no genera error
- Creación vía LH (payments)
- Creación vía batch (payments)

Me falta probar vía API y volver sobre algún caso, pero por ahora tiene muy buena pinta

2024-01-11 12:05 UTC, juanSTIC commented
> C) Grupo no heredable para un usuario
> 
> 1. Creo un usuario y le asigno varios grupos heredables
> 2. En la vista de detalle de ese usuario, modifico la relación con un grupo para indicar que no es heradable (aunque el grupo en si, sí lo es)
> 3. Marco herencia de usuario creador para un módulo
> 4. Hereda todos los grupos del usuario, incluyendo el marcado para no heredar

No se había contemplado. Añadido.

2024-01-11 12:29 UTC, juanSTIC commented
> B) Se duplican grupos relacionados
> 
> 1. En Payment Commitments marcamos importar de Personas y de Persona destinataria
> 2. A Persona le asignamos los grupos G1 y G2
> 3. A persona destinataria los G1, G3 y G4
> 4. Creamos (desde vista edición) un CP, escogiendo las personas creadas
> 5. El registro resultante tiene 2 veces el grupo G1. En el subpanel sólo se muestra 1 vez pero el contador del subpanel indica 5 grupos en lugar de 4 y se puede verificar vía BBDD).

Corregido, ahora se eliminan asignaciones duplicadas (antes de ejecutarlas)

2024-01-12 06:51 UTC, enricsinergia requested changes
La herencia de campo relacionado no me ha funcionado. Identificado el punto donde me falla, no sé si depende de la forma de definir el campo o qué.
Pasos:
1. En un módulo custom he añadido un campo relacionado a contacts
2. Al crear registro de módulo custom, informando ese contacto (ninguna regla más activa), no me ha arrastrado ningún grupo de seguridad (no entra en la condición de la línea 291)

2024-01-12 06:51 UTC, enricsinergia commented on modules/stic_Security_Groups_Rules/Utils.php
> +                    if ($rulesBean->inherit_parent == 1 || in_array($rulesBean->name . $value['relationship'], $filteredRelatedModules)) {
En el caso de los campos relacionados no coinciden los nombres y no se aplica la herencia

2024-01-12 06:51 UTC, enricsinergia requested changes
La herencia de campo relacionado no me ha funcionado. Identificado el punto donde me falla, no sé si depende de la forma de definir el campo o qué.
Pasos:
1. En un módulo custom he añadido un campo relacionado a contacts
2. Al crear registro de módulo custom, informando ese contacto (ninguna regla más activa), no me ha arrastrado ningún grupo de seguridad (no entra en la condición de la línea 291)

2024-01-12 08:25 UTC, juanSTIC commented
> La herencia de campo relacionado no me ha funcionado. Identificado el punto donde me falla, no sé si depende de la forma de definir el campo o qué. Pasos:
> 
> 1. En un módulo custom he añadido un campo relacionado a contacts
> 2. Al crear registro de módulo custom, informando ese contacto (ninguna regla más activa), no me ha arrastrado ningún grupo de seguridad (no entra en la condición de la línea 291)

Revisado. Aseguramos que si _id_name_ no está presente, se usa _name_

2024-01-12 09:29 UTC, enricsinergia requested changes
El SELECT con UNION al que añadí la condición habrá que revisarlo y supongo que cambiar alguna cosa más.

He visto que cuando determinamos que herede de algún registro padre, si éste tiene algún grupo que en la relación con el usuario está puesto como no heredable (el grupo es heredable pero no para ese usuario), ese grupo no se está heredando. 

Supongo que habrá que modificar la lógica para que ese segundo conjunto de grupos sólo se eliminen de los grupos a heredar si viene del usuario creador o asignado (cada cual con su propia lista). Es decir, al tratar el usuario creador y asignado, antes de añadir los grupos al array securityGroupsCandidatesToInherit, habría que hacer la limpieza según los grupos de ese usuario concreto.

2024-01-17 10:56 UTC, AlbertoSTIC requested changes
No se heredan correctamente los grupos de seguridad:
![Screenshot from 2024-01-17 11-52-07](https://github.com/SinergiaTIC/SinergiaCRM/assets/46563429/33e8767a-7bb6-438b-8738-12b8e82a99e7)
Con la regla anterior, después de crear un registro de Documentos desde una Organización que tengan los 3 grupos de seguridad, no hereda ningún grupo. Parece que hay algún error en el momento de heredar los grupos.

Además, en local, se ha visto este error en la consola del navegador:
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/46563429/45e15a5c-b892-4067-89da-783161b44fd7)

No estoy seguro si es un problema aislado o sucede en otros lugares. De todas maneras se ha visto que la variable del config "stic_security_groups_rules_enabled" no está definida en el fichero config.php. Debería estar definida por defecto con valor `stic_security_groups_rules_enabled = false`.

Sugerencia en relación al último punto: añadir la configuración `stic_security_groups_rules_enabled` en el array de `js_available` del config.php y prescindir de tener que añadirle en cada vista: https://github.com/SinergiaTIC/SinergiaCRM/blob/3ae0c18f3744559a852ecd05963c119a8943b5ce/modules/stic_Security_Groups_Rules/views/view.list.php#L72-L73

2024-01-17 12:52 UTC, juanSTIC commented
> No se heredan correctamente los grupos de seguridad:
> ![Screenshot from 2024-01-17 11-52-07](https://private-user-images.githubusercontent.com/46563429/297354106-33e8767a-7bb6-438b-8738-12b8e82a99e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTYxNzYsIm5iZiI6MTcwNTQ5NTg3NiwicGF0aCI6Ii80NjU2MzQyOS8yOTczNTQxMDYtMzNlODc2N2EtN2JiNi00MzhiLTg3MzgtMTJiOGU4MmE5OWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyNTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ODRjZTQyZDE5ZGYyZGI1YjU4ZGUwYzUxZmI3YTkwZDg5ZWFmYjE5NDhkYTBmNzJkNTU1MzQ4ZmEwODFjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ly53Kqjl6fCeY2H2tco5iXtxjyvO_v-ueNG_N4Hakx4)
> Con la regla anterior, después de crear un registro de Documentos desde una Organización que tengan los 3 grupos de seguridad, no hereda ningún grupo. Parece que hay algún error en el momento de heredar los grupos.

Esta parte debe estar ya resuelta

2024-01-17 13:09 UTC, juanSTIC commented
> Además, en local, se ha visto este error en la consola del navegador: ![image](https://private-user-images.githubusercontent.com/46563429/297354579-45e15a5c-b892-4067-89da-783161b44fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTYxNzYsIm5iZiI6MTcwNTQ5NTg3NiwicGF0aCI6Ii80NjU2MzQyOS8yOTczNTQ1NzktNDVlMTVhNWMtYjg5Mi00MDY3LTg5ZGEtNzgzMTYxYjQ0ZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyNTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ODg3MWRiZGFlYjIwMTAzMzY0MmNmZTc4YzUyNzcyNGIyOTE4Nzc2NTc4MTA5YTAwNjNjOTFhNzNmMzgxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SpuWBsF6xI2dNgkFY6BbZ3Y_Gbf2cmijUsXpG4pjBS4)
> 
> No estoy seguro si es un problema aislado o sucede en otros lugares. De todas maneras se ha visto que la variable del config "stic_security_groups_rules_enabled" no está definida en el fichero config.php. Debería estar definida por defecto con valor `stic_security_groups_rules_enabled = false`.
> 
> Sugerencia en relación al último punto: añadir la configuración `stic_security_groups_rules_enabled` en el array de `js_available` del config.php y prescindir de tener que añadirle en cada vista:
> 
> https://github.com/SinergiaTIC/SinergiaCRM/blob/3ae0c18f3744559a852ecd05963c119a8943b5ce/modules/stic_Security_Groups_Rules/views/view.list.php#L72-L73

Se ha traspasado la lógica de la variable a config.php. El error de JS no lo he podido reproducir, probablemente fuera debido a esto.

2024-01-17 13:51 UTC, AlbertoSTIC requested changes
Ahora sí que funciona correctamente la herencia de registro Padre cuando se selcciona algún módulo, pero en el caso de seleccionar la opción de "Inherit from all parent records", no funciona correctamente.
Pasos:
1- Activar la regla "Inherit from all parent records" para el módulo Documentos sin ninguna otra modificación. 
2- Desde una Persona crear un Documento, este no hereda los grupos de la Persona.

2024-01-17 15:05 UTC, juanSTIC commented
> nherit from all parent records", no funciona correctamente.
> Pasos:



> Ahora sí que funciona correctamente la herencia de registro Padre cuando se selcciona algún módulo, pero en el caso de seleccionar la opción de "Inherit from all parent records", no funciona correctamente. Pasos: 1- Activar la regla "Inherit from all parent records" para el módulo Documentos sin ninguna otra modificación. 2- Desde una Persona crear un Documento, este no hereda los grupos de la Persona.

Corregido

2024-01-17 17:36 UTC, enricsinergia commented on modules/stic_Security_Groups_Rules/Utils.php
> +    public static function getSticUserSecurityGroups($userId)
Cambiaría el nombre de esta función y un poco la SQL. Le llamaría getSticUserInheritableSecurityGroups y no devolvería ningún grupo no heradable (sea por la relación grupo-usuario o en la propia definición del grupo). El nombre actual induce a error (no habla de que sólo devuelve heredables y la explicación y la SQL no acaban de encajar al 100%: la descripción dice que se excluyen los no heredables, pero la SQL sólo excluye los no heradables según la relación usuario-grupo). Y para nota, haría lo que comentamos: un flag que me diga si quiero todos o sólo los no heredables pensando en el futuro, pero ahora no es necesario.

2024-01-17 17:48 UTC, enricsinergia submitted a review, later dismissed
(A)provado

Aparte de lo comentado sobre la función getSticUserSecurityGroups (tema menor), todo parece OK.
Pruebas realizadas:
- Relaciones 1:n, N:1, M:N, 1:1
- Creación directa y desde subpanel 
- Creación de compromiso y pago con distintas reglas de herencia
- Creación pago vía batch
- Creación vía Workflow
- Distintas herencias separadas y en combinación con grupos disyuntos y coincidentes
- Grupos no heredables, no heredables para usuario (presente y no presente en otras herencias), grupos prohibidos según la regla
- Múltiples relaciones con el mismo módulo

Anteriormente:
- Creación vía API
- Creación vía Importación
- Merge de registros

2024-01-17 18:49 UTC, jalbaiges approved these changes

2024-01-18 08:24 UTC, AlbertoSTIC approved these changes
(A)probado

2024-01-18 08:27 UTC, enricsinergia approved these changes
(A)provado

(Comprobado que los métodos se invocan correctamente ;-) )

2024-01-18 09:04 UTC, merged