Improvement - Formularios Web - Inclusión de nombre y apellidos del pagador en el envío a Redsys
SinergiaTIC/SinergiaCRM pull request #324
Opened 2024-08-05 16:46 UTC by jordiSTIC

- Closes #212

2024-08-08 14:58 UTC, ManuSinergiaCRM requested changes
Probada la funcionalidad y funciona correctamente. 

Una propuesta de mejora para aquellos casos donde la persona u organización ya existan en el CRM y en el formulario el usuario no haya indicado los mismos datos. 

En vez de coger coger el nombre y los apellidos de la REQUEST, cogerlos de la persona u organización relacionada con el pago que recibe como parámetro el método `private function redsysPrepareFirstStep($payment)`

2024-08-09 10:30 UTC, jordiSTIC commented
> Probada la funcionalidad y funciona correctamente.
> 
> Una propuesta de mejora para aquellos casos donde la persona u organización ya existan en el CRM y en el formulario el usuario no haya indicado los mismos datos.
> 
> En vez de coger coger el nombre y los apellidos de la REQUEST, cogerlos de la persona u organización relacionada con el pago que recibe como parámetro el método `private function redsysPrepareFirstStep($payment)`

Se ha substituido el mecanismo de obtención del nombre del titular: No se recoge de los datos introducidos por el usuario en el formulario, sino que se recogen los datos que figuran en el CRM.

Nota: Antes de enviarse los datos a RedSys para que se realice el pago, se han creado en el CRM los datos relacionados al Compromiso de Pago y la Persona/Organización. Por lo tanto, siempre habrá datos en el CRM relacionados con quien realliza el pago

2024-08-12 11:50 UTC, ManuSinergiaCRM submitted a review, later dismissed
(A)probado

2024-08-22 10:29 UTC, juanSTIC requested changes
El nombre que aparece en el formulario de confirmación se obtiene a partir de la relación con Personas u Organizaciones , pero si ya hay un registro con el mismo número de identificación, este es el que se muestra en el formulario de confirmación de Redsys, sin embargo, creo que lo correcto es que se muestre el nombre que el usuario ha escrito en el formulario, independientemente de que ya haya una persona/Org con el mismo DNI/NIF.
Creo que podría obtenerse directamente del $_REQUEST 

Puesto que justamente esta cuestión es objeto de controversia, @jalbaiges ¿qué datos deben mostrarse en la pantalla de confirmación del pago de Redsys?
1. El nombre y apellidos escrito en el formulario.
2. Los datos que eventualmente ya pudiera haber en el CRM si existe registro previo con el mismo DNI

2024-08-22 11:18 UTC, jalbaiges commented
En caso de no coincidir los datos del formulario con los ya existentes en el CRM, yo diría que a efectos de identificar la transacción a la entidad le interesará más ver en el TPV los datos que tiene en el CRM que los que el usuario introdujo en el formulario (que los tendrá en el correo de notificación en el que se le indica que se detectó un duplicado).

2024-08-22 11:42 UTC, juanSTIC approved these changes
Aprobado, con el enfoque indicado en los comentario (se prefiere que se muestren los datos existentes en el CRM, si existen)

2024-08-22 12:17 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-09-20 11:27 UTC, merged