Enhancement - Encuestas - Mensaje agradecimiento fijado en inglés
SinergiaTIC/SinergiaCRM pull request #339
Opened 2024-08-14 11:22 UTC by ainaraRT

- Closes #155 

**Desarrollo del issue**
Al completar una encuesta se redirige a una página dónde el mensaje está únicamente en inglés "Thanks for completing this survey". El mensaje se debería mostrar en el idioma por defecto de la instancia.

**Solución implementada:**
Se ha implementado las diferentes cadenas con el mensaje que aparecía al principio en inglés, por ello se ha creado una variable con la función de `translate()` para que recoja dichas cadenas según el idioma seleccionado en el login.

**Pruebas**
1. Acceder con cualquier idioma al CRM.
2. Ir al módulo de encuestas y crear una con alguna pregunta.
3. Enviar la encuesta y comprobar que aparece el mensaje en el idioma seleccionado en el login o el que tiene por defecto la instancia.

2024-08-21 14:54 UTC, jordiSTIC submitted a review, later dismissed

2024-08-23 08:52 UTC, juanSTIC submitted a review, later dismissed
Visto y probado

2024-08-29 11:17 UTC, jalbaiges requested changes
Si se modifica el código del core (que es correcto), las cadenas también tienen que ir a los ficheros del core.

2024-09-03 08:25 UTC, ainaraRT commented
> Si se modifica el código del core (que es correcto), las cadenas también tienen que ir a los ficheros del core.

Hecho!!

2024-09-04 11:31 UTC, jalbaiges approved these changes

2024-09-20 11:14 UTC, juanSTIC submitted a review, later dismissed
Aprobado

2024-09-20 15:42 UTC, AlbertoSTIC approved these changes
Aprobado

2024-09-23 10:59 UTC, jordiSTIC approved these changes
(A)Probado

2024-09-23 14:37 UTC, merged

2024-10-29 16:06 UTC, SinergiaCRM commented
PR en SA: https://github.com/salesagility/SuiteCRM/pull/10565