Enhancement - SinergiaDA - Algunas mejoras
SinergiaTIC/SinergiaCRM pull request #373
Opened 2024-08-22 08:55 UTC by juanSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-08-22 10:06 UTC, PaulaaSTIC approved these changes

2024-08-28 09:03 UTC, AlbertoSTIC approved these changes
Aprobado

2024-09-09 11:50 UTC, PaulaaSTIC approved these changes

2024-09-11 15:28 UTC, PaulaaSTIC approved these changes
(A)probado

2024-09-20 11:21 UTC, AlbertoSTIC requested changes
Ver comentarios.

2024-09-20 11:35 UTC, juanSTIC commented on SticInclude/SinergiaDA.php
> +                                if ($u['user_name'] == 'u1') {
absolutamente!. Quitado

2024-09-20 11:40 UTC, juanSTIC commented on modules/stic_Accounts_Relationships/SDAVardefs.php
> +            WHEN (m.start_date IS NULL OR m.start_date <= LAST_DAY(CONCAT(YEAR(CURDATE()),'-12-31')))
Sí, en la creación de las vistas se define m (main) como alias para la tabla principal de cada módulo.
https://github.com/SinergiaTIC/SinergiaCRM/blob/edea762cf72e7a20b66d2a9f51fc5f0f6701f698/SticInclude/SinergiaDA.php#L864

2024-09-20 15:41 UTC, AlbertoSTIC approved these changes
Aprobado.

2024-09-23 14:38 UTC, PaulaaSTIC approved these changes

2024-09-24 08:23 UTC, merged