Hotfix - General - Evitar la regenración innecesria de ficheros de idioma
SinergiaTIC/SinergiaCRM pull request #405
Opened 2024-09-26 09:06 UTC by enricsinergia

## Descripción
En el análisis que llevó a la apertura de los issues #392 y #393, se observó también que los ficheors de idioma eran regenerados con excesiva frecuencia sin que hubiera un motivo aparente.

Después de investigar el tema y múltiples pruebas, se han observado 2 causas posibles:
1.- Si hay algún módulo activo que no contiene literales (por ejemplo ResourceCalendar está activo en algunas instancias), no genera información en caché. Al hacer login e intentar recuperar los literales de todos los módulos no se encuentra la información de estos módulos y se fuerza la regeneración de los ficheros de idiomas (que tampoco generará información en caché) con lo que el siguiente login provocará una nueva regeneración.
2.- Los formularios, en la clase WebFormDataController, dentro de la función loadLanguage está ejecutando la sentencia `$this->mod_strings[$this->defaultModule] = return_module_language($this->lang, $this->defaultModule, true); // Load the module labels by default`, la cual provoca que se regeren siempre los ficheros de idioma.

## Solución aplicada
1.- Para el caso (1) se ha aplicado un cambio para que siempre se genere información en caché aunque sea vacía
2.- Para el caso (2) se han modificado las llamadas a _return_module_language_ para que no fuerzen el refresco de los ficheros de idiomas.

## Pruebas
### No regenera con módulo vacío
1.- Habilitar algún módulo sin literales (por ejemplo ResourceCalendar)
2.- Realizar un nuevo login
3.- Comprobar la fecha de modificación de los ficheros de idioma
`ls -la /web/custom/application/Ext/Language/`
4.- Cerrar sesión y volver a iniciar sesión pasado un minuto
5.- Comprovar que no se han regenerado los ficheros de idioma
### No regenera con formulario
1.- Crear un formulario que ataque la instancia de prueba
2.- Comprobar la fecha de modificación de los ficheros de idioma
`ls -la /web/custom/application/Ext/Language/`
3.- REllenar y lanzar el formulario
4.- Comprovar que no se han regenerado los ficheros de idioma

## Información adicional
Realizando búsuqeda con el patrón `return_module_language\([^)]*,\s*[^)]*,\s*true\)` se detecta quehay más usos dentro de SuiteCRM de la llamada a return_module_language con el refresh a true. No se abordan en este PR por el posible impacto que pueden tener.

2024-10-09 11:59 UTC, jordiSTIC requested changes
Realizadas las pruebas.
**Login con módulo sin literales**
Ok, funciona correctamente

**Formulario con fichero adjunto**
Se han regenerado los literales (ca_ES y en_us): Al recibir el formulario, en local se han regenerado

2024-10-14 14:30 UTC, jordiSTIC submitted a review, later dismissed
Se han realizado más pruebas:
- Al iniciar sesión habilitando el módulo de ResourceCalendar, únicamente regenera el fichero de idioma al hacer login cambiando el idioma. No se regeneran los ficheros en cada login
- Al recibir el resultado de un formulario, regenera el idioma la primera vez. Al enviar múltiples veces el formulario, no se regeneran los idiomas cada vez que se recibe.

Revisado el código.
Apruebo ya que se consigue que no se regeneren de forma masiva los ficheros de idioma

2024-11-18 12:55 UTC, ManuSinergiaCRM requested changes
Funcionalidad probada :+1: 

Solo veo una cosilla a nivel de código y es que hay que eliminar o modificar el log de la línea 132 de include/SugarObjects/LanguageManager.php

Y además, habría que meter el PR en core modification ya que se toca el fichero anterior

2024-11-20 09:36 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-11-20 10:01 UTC, jordiSTIC approved these changes
(A)Probado

2024-11-20 10:01 UTC, merged