Hotfix - Reuniones - "Run Email Reminder Notifications" no se ejecuta al eliminar una persona
SinergiaTIC/SinergiaCRM pull request #406
Opened 2024-09-26 16:21 UTC by ainaraRT

- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/395

### Desarrollo del issue
Se ha comprobado que al crear una reunión con recordatorios, tanto emergente como por correo, y se elimina una persona/usuario antes de que se ejecute la tarea programada "Run Email Reminder Notifications", falla la ejecución, haciendo que se quede estancada la tarea y desde ese momento, no se enviará ningún recordatorio. 
Además, si lleva mucho tiempo estancada la tarea, las reuniones con fechas pasadas, se envían.

### Solución implementada
1. Se ha añadido una condición de que si lleva mucho tiempo la tarea estancada y ya ha pasado el recordatorio (fecha de inicio de la reunión, ejemplo: 16/06/2022 9:00), no se mande ningún recordatorio a los asistentes de la reunión pasada.
2. Se ha añadido una condición de que si la persona queda eliminada, no se intente mandar un correo y continúe la ejecución dicha tarea.

### Pruebas
**Persona eliminada**
1. Configurar correctamente la cuenta de correo.
2. Crear una reunión, añadiendo un recordatorio de correo a los asistentes.
3. Guardar y enviar invitaciones.
4. Eliminar la persona/usuario antes de ejecutar la tarea programada "Run Email Reminder Notifications".
8. Ver en la reunión que aparece la persona como "UNKNOWN".
5. Ejecutar la tarea "Run Email Reminder Notifications".
6. Comprobar que llega el correo electrónico del recordatorio a los invitados, menos a la persona eliminada, y al creador de la reunión.
7. Además, comprobar que la tarea ha sido ejecutada correctamente.

**Reunión pasada**
1. Configurar correctamente la cuenta de correo.
2. Crear una reunión pasada, añadiendo un recordatorio de correo a los asistentes.
3. Guardar y enviar invitaciones.
5. Ejecutar la tarea "Run Email Reminder Notifications".
6. Comprobar que no llega el correo electrónico del recordatorio, a ninguno de los invitados ni el creador de la reunión.
7. Además, comprobar que la tarea ha sido ejecutada correctamente.

2024-09-30 15:35 UTC, ManuSinergiaCRM requested changes
Ver comentarios de la revisión

2024-09-30 15:35 UTC, ManuSinergiaCRM commented on modules/Reminders/Reminder.php
> +                if($eventBean->date_start > $dateNow || $eventBean->date_start == $dateNow){
Entiendo que queremos enviar aquellos recordatorios donde la fecha actual no sea mayor a la fecha de la reunión ya que si ya ha empezado o finalizado, el recordatorio no es necesario

Valorar la siguiente propuesta de solución a implementar en la siguiente línea de código: https://github.com/SinergiaTIC/SinergiaCRM/blob/develop/modules/Reminders/Reminder.php#L267:

```
// STIC-Custom 
// https://github.com/SinergiaTIC/SinergiaCRM/pull/406
// if ($now_ts >= $remind_ts) {
$event_ts = $timedate->fromUser($eventBean->date_start)->ts;
if ($now_ts >= $remind_ts && $now_ts <= $event_ts) {
// END STIC-Custom
```

Valorar también si queremos enviar el recordatorio durante la duración de la reunión. Si fuera así, usar date_end en vez de date_start

En último caso, si la propuesta realizada no cuadra, cambiar

`($eventBean->date_start > $dateNow || $eventBean->date_start == $dateNow`

por 

`($eventBean->date_start >= $dateNow)``

2024-09-30 15:35 UTC, ManuSinergiaCRM commented on modules/Reminders/Reminder.php
> +                // STIC-Custom 20240926 ART - “Run Email Reminder Notifications” does not run when deleting a person
Cambiar el texto ya que no describe lo que se está realizando

2024-09-30 15:35 UTC, ManuSinergiaCRM commented on modules/Reminders/Reminder.php
> +                // STIC-Custom 20240926 ART - “Run Email Reminder Notifications” does not run when deleting a person
Indicar en el comentario que la tarea generaba un error bloqueante y en vez de persona indicaría  invitado.

2024-10-01 11:45 UTC, ainaraRT commented on modules/Reminders/Reminder.php
> +                // STIC-Custom 20240926 ART - “Run Email Reminder Notifications” does not run when deleting a person
hecho!!

2024-10-01 11:45 UTC, ainaraRT commented on modules/Reminders/Reminder.php
> +                // STIC-Custom 20240926 ART - “Run Email Reminder Notifications” does not run when deleting a person
hecho!!

2024-10-07 12:59 UTC, ManuSinergiaCRM commented on modules/Reminders/Reminder.php
> +                // STIC-Custom 20240926 ART - “Run Email Reminder Notifications” does not run when deleting a person
En vez de añadir las dos líneas nuevas, modificaría el comentario que ya existía:

> // STIC-Custom 20240926 ART - Evitar la notificación a un invitado si este ya no existe en el CRM ya  provocaba un error que impedía que finalizará correctamente la tarea “Run Email Reminder Notifications”
> // https://github.com/SinergiaTIC/SinergiaCRM/pull/406

por 

// STIC-Custom 20240926 ART - https://github.com/SinergiaTIC/SinergiaCRM/pull/406
// Evitar el envío del recordatorio a cualquier invitado si este ya no existe en el CRM, ya que provoca un error que impide que la tarea “Run Email Reminder Notifications” finalice correctamente.

2024-10-07 13:01 UTC, ManuSinergiaCRM requested changes
Ver el comentario: https://github.com/SinergiaTIC/SinergiaCRM/pull/406#discussion_r1790181178

2024-10-28 16:38 UTC, ainaraRT commented on modules/Reminders/Reminder.php
> +                // STIC-Custom 20240926 ART - “Run Email Reminder Notifications” does not run when deleting a person
Comentario añadido!

2024-10-29 12:09 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-10-30 15:30 UTC, jordiSTIC approved these changes
(A)Probado

2024-11-19 15:30 UTC, merged

2025-01-28 16:33 UTC, SinergiaCRM commented
PR en SA: https://github.com/salesagility/SuiteCRM/pull/10631