Hotfix - Usuarios - Generación automática de contraseña con requisitos de seguridad
SinergiaTIC/SinergiaCRM pull request #417
Opened 2024-10-02 12:47 UTC by jordiSTIC

- Closes #416 

## Descripción
Si se definía en "Administración - Usuarios - Administración de contraseñas" una configuración de seguridad de contraseñas, y a la vez se habilitaba la generación de contraseñas por el sistema, las contraseñas generadas automáticamte no cumplían los requisitos de seguridad definidos.

## Solución propuesta
Se ha modificado la función `User::generatePassword()` para que genere una contraseña teniendo en cuenta el cumplimiento de los requisitos de seguridad definidos en `$sugar_config['passwordsetting']`

## Pruebas
En una instancia con servidor de correo saliente configurado:

1. Ir a Administración - Usuarios - Administración de Contraseñas
2. Habilitar Característica de Contraseñas Generadas por el Sistema
3. Modificar la Configuración de seguridad de contraseña: Longitud mínima 8, e incluir carácteres especiales por ejemplo
4. Crear un usuario con una cuenta de correo válida
5. Verificar que en el correo enviado al usuario con la nueva contraseña, ésta SÍ cumple los requisitos de seguridad

2024-10-28 12:04 UTC, ManuSinergiaCRM requested changes

2024-10-28 12:04 UTC, ManuSinergiaCRM commented on modules/Users/User.php
> +        if (isset($res['minpwdlength']) && is_numeric($res['minpwdlength']) && $res['minpwdlength'] < $length) {
En caso de configurar un número mayor a 6 no entra en el IF

--> Cambiar `$res['minpwdlength'] < $length` por `$res['minpwdlength'] > $length` o `$res['minpwdlength'] != $length` dependiendo de si queremos que la contraseña tenga 6 caracteres de longitud mínima o no.

2024-10-28 12:04 UTC, ManuSinergiaCRM commented on modules/Users/User.php
> +        for ($i = 0; $i < $length - count($requirements) + 1; $i++) {  // loop and create password
Se crea una contraseña con un carácter más de lo indicado. Cambiar `$i < $length ... ` por `$i <= $length` o no sumar el `+ 1`

2024-10-28 14:54 UTC, jordiSTIC commented on modules/Users/User.php
> +        if (isset($res['minpwdlength']) && is_numeric($res['minpwdlength']) && $res['minpwdlength'] < $length) {
Corregido: Asumido que la longitud mínima será 6: en la antigua generación de contraseñas siempre se generaban de longitud 6

2024-10-28 14:54 UTC, jordiSTIC commented on modules/Users/User.php
> +        for ($i = 0; $i < $length - count($requirements) + 1; $i++) {  // loop and create password
Corregido :+1:

2024-10-28 15:00 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-10-28 16:23 UTC, ainaraRT approved these changes
(A)Probado

2024-11-19 15:30 UTC, merged

2024-12-09 09:01 UTC, SinergiaCRM commented
PR SA: https://github.com/salesagility/SuiteCRM/pull/10592