Hotfix - Plantillas PDF - Formatear número con las preferencias del usuario
SinergiaTIC/SinergiaCRM pull request #429
Opened 2024-10-07 15:57 UTC by ainaraRT

- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/420

## Description

Como se describe en el issue, se ha comprobado que en un campo de tipo decimal, no mostraba el separador de miles al generar una plantilla PDF. Debería reflejar el formato de número tal como se muestra en el CRM, donde sí aparece el separador de miles en las vistas.

Se ha implementado en la función que formatea el número decimal con las preferencias que tiene el usuario, o están por defecto, de los separadores y el número de decimales que se quiere mostrar con la función _number_format()_

## How To Test This

1. Ir a Estudio y en un módulo crear un campo de tipo decimal.
3. Añadir ese campo a la vista de edición y añadir un número mayor a 999 con decimales.
4. Ir a Perfil-Avanzado y comprobar o cambiar los valores de _Separador de miles_, _Separador decimal_ y _Dígitos Significativos en Moneda_
5. Incluir el campo decimal en una plantilla PDF.
6. Comprobar que dicho número se muestra con los separadores y el número de decimales correspondientes al generar la plantilla.

2024-10-28 16:34 UTC, jordiSTIC commented on SticInclude/Utils.php
> +        $sig_digits = empty($user_sig_digits) ? $sugar_config['sigDigits'] : $user_sig_digits;
El nombre correcto de la configuración debería ser `default_currency_significant_digits`: en config.php, se define en `$sugar_config`: 
https://github.com/SinergiaTIC/SinergiaCRM/blob/b96498d8e9090d4a58c77f96e7ee3c346d45ee7d/config.php#L267

2024-10-28 16:34 UTC, jordiSTIC requested changes
Ver comentario en el código

2024-10-28 17:22 UTC, jordiSTIC approved these changes
(A)Probado

2024-11-06 08:43 UTC, PaulaaSTIC approved these changes

2024-11-06 08:44 UTC, PaulaaSTIC approved these changes
(A)probado

2024-11-19 15:31 UTC, merged

2024-12-10 16:28 UTC, SinergiaCRM commented
PR en SA: https://github.com/salesagility/SuiteCRM/pull/10598