Feature - Subvenciones - Alerta nuevas convocatorias
SinergiaTIC/SinergiaCRM pull request #44
Opened 2024-01-09 11:57 UTC by jordiSTIC

- Closes #43

2024-01-09 11:58 UTC, jordiSTIC commented
PR migrado a: https://github.com/SinergiaTIC/SinergiaCRM-SuiteCRM/pull/1335

2024-07-17 12:51 UTC, AlbertoSTIC requested changes
Ver comentarios.

2024-07-17 12:51 UTC, AlbertoSTIC commented on custom/modules/Opportunities/SticUtils.php
> +
Igual podeos deshacer esta modificación si no afecta.

2024-07-17 12:51 UTC, AlbertoSTIC commented on custom/modules/Opportunities/metadata/detailviewdefs.php
> +<?php
En este PR: https://github.com/SinergiaTIC/SinergiaCRM/pull/105 se decidió llevas las personalizaciones de las vistas directamente a los ficheros del core.

2024-07-17 12:51 UTC, AlbertoSTIC commented on custom/modules/Opportunities/metadata/editviewdefs.php
> +<?php
Ídem

2024-07-17 12:51 UTC, AlbertoSTIC commented on include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php
> +        if($module == "Campaigns" && $layout_def["subpanel_id"] == "stic_notifications") {
Entiendo que este código es necesario para que al pulsar el enlace, te redirija directamente a la vista de estado de la campaña. En ese caso, creo que crearía un nuevo SugarWidget solo con este propósito. De la misma manera que hicimos aquí: custom/include/generic/SugarWidgets

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/Campaign.php
> +    public $notification_reply_to_addr;
No tengo claro que sea necesario definir los campos en este punto. Creo que esto es herencia de SugarCRM y ya no se utiliza.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/Campaign.php
> +    // END STIC-Custom
¿Para qué hacemos esto?¿En qué punto se recogen estos datos? Hecho de menos comentarios específicos para algunos de los cambios, sobretodo en el core.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/Campaign.php
> +	}
Ídem. Sería importante comentar este tipo de cambios.
Entiendo que hacemos directamente en el core para llevarlo luego a SA, ¿es así? Sino se podría estudiar hacerlo en LHs.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/TrackDetailView.php
> +    // STIC-Custom - JBL - 20240702 - Notify new Opportunities: New Campaign type (Notification)
Si se clona este fichero en custom/modules/Campaigns/TrackDetailView.php, recogerá el fichero de custom. Por lo tanto añadiría los cambios en ese punto, sin modificar el core.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/TrackDetailView.tpl
>  	</td>
Si creamos el fichero anterior PHP en custom, aprovecharía para cambiar también la ruta de este fichero y pasarlo a custom.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/metadata/detailviewdefs.php
> +        // STIC-Custom - JBL - 20240626 - Campaign type: Notification
Ahora veo estos cambios. Entonces entiendo que no son necesarios los cambios en custom de este fichero.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/metadata/editviewdefs.php
> +    // STIC-Custom - JBL - 20240515 - Notify new Opportunities: New Campaign type (Notification)
Ídem.

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/metadata/subpanels/SticOpportunityNotifications.php
> +<?php
Este fichero podría estar en la misma ruta pero en custom/

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/Campaigns/views/view.detail.php
> +            // STIC-Custom 20240603 JBL - New Campaign type: Notification
¿Estos cambios no se puede trasladar al fichero view.detail.php en custom?

2024-07-17 12:51 UTC, AlbertoSTIC commented on modules/EmailTemplates/EmailTemplateParser.php
> +
¿Qué hacemos en este punto? Faltan comentarios.

2024-07-17 16:21 UTC, jordiSTIC commented on SticInstall/sql/common/FieldsMetadata.sql
> +('Campaignsnotification_prospect_list_names', 'Campaigns', 'notification_prospect_list_names'),
Hecho

2024-07-17 16:21 UTC, jordiSTIC commented on SticUpdates/Migrations/20240705_feature_44_alertOpportunities.sql
> +INSERT INTO `fields_meta_data` (`id`, `custom_module`, `name`) VALUES
Hecho

2024-07-17 16:25 UTC, jordiSTIC commented on custom/modules/Campaigns/SticUtils.js
> -loadScript("include/javascript/moment.min.js");
Sí, este script ya se incluye en sugar_grp1.js: https://github.com/SinergiaTIC/SinergiaCRM/blob/cb471d42491ead6807dadc621eff384f59801832/custom/Extension/application/Ext/JSGroupings/SticJSGroupings.php#L60-L63

2024-07-18 08:59 UTC, jordiSTIC commented on custom/Extension/modules/Opportunities/Ext/Layoutdefs/SticLayoutdefs.php
> +    'subpanel_name' => 'SticOpportunityNotifications',
No es necesario que tengan el mismo nombre (de hecho normalmente no lo tiene). Indica el fichero php que define el $subpane_layout (en modules/Campaigns/metadata/subpanels).
Se ha renombrado a "SticForNotifications", para seguir el patrón estandar de SuiteCRM: valor "default" o indicando para qué es el subpanel especial: "ForTasks", "ForHistory", "ForActivities"...

2024-07-18 09:13 UTC, jordiSTIC commented on custom/Extension/modules/Opportunities/Ext/Layoutdefs/SticLayoutdefs.php
> +$layout_defs['Opportunities']['subpanel_setup']['stic_notifications'] = array(
Cambiado por 'stic_campaigns_notification'

2024-07-18 09:19 UTC, jordiSTIC commented on custom/Extension/modules/Opportunities/Ext/Layoutdefs/SticLayoutdefs.php
> +    'title_key' => 'LBL_OPPORTUNITIES_NOTIFICATIONS_TITLE',
Corregido a `LBL_STIC_CAMPAIGNS_NOTIFICATION_FROM_OPPORTUNITIES_TITLE`: Las etiquetas de los subpaneles se componen de: "LBL_" + nombre del panel + "_FROM_" + módulo principal + "_TITLE"

2024-07-18 09:20 UTC, jordiSTIC commented on custom/modules/Opportunities/SticUtils.php
> +
Hecho

2024-07-18 09:23 UTC, jordiSTIC commented on modules/Campaigns/Campaign.php
> +    // END STIC-Custom
Añadidos comentarios. 
Es necesario porque las Campañas de tipo Notificación tienen campos "non-db" que se calculan a partir de las relaciones. Por ejemplo: listado de LPOs (de las LPOs relacionadas), datos para el envío (del Email Marketing relacionado), etc

2024-07-18 09:26 UTC, jordiSTIC commented on modules/Campaigns/metadata/subpanels/SticOpportunityNotifications.php
> +<?php
Renombrado a SticForNotifications.php y movido a custom

2024-07-18 10:34 UTC, jordiSTIC commented on modules/Campaigns/TrackDetailView.php
> +    // STIC-Custom - JBL - 20240702 - Notify new Opportunities: New Campaign type (Notification)
Cambios trasladados a la carpeta custom

2024-07-18 10:36 UTC, jordiSTIC commented on modules/Campaigns/TrackDetailView.tpl
>  	</td>
Fichero traspasado a la carpeta custom. Cambios en core revertidos

2024-07-18 10:44 UTC, jordiSTIC commented on modules/Campaigns/views/view.detail.php
> +            // STIC-Custom 20240603 JBL - New Campaign type: Notification
Si se trasladasen los cambios a custom, view.detail.php de custom tendría que tener una copia del código de la función `display()` de core y no podría llamar a `parent::display();` 
Actualmente la función `display()` definida en custom es:
https://github.com/SinergiaTIC/SinergiaCRM/blob/cb471d42491ead6807dadc621eff384f59801832/custom/modules/Campaigns/views/view.detail.php#L54-L63

2024-07-18 11:44 UTC, jordiSTIC commented on modules/Campaigns/metadata/editviewdefs.php
> +    // STIC-Custom - JBL - 20240515 - Notify new Opportunities: New Campaign type (Notification)
En custom, el editviewdefs eran de Subvenciones. Se han trasladado a core

2024-07-18 11:49 UTC, jordiSTIC commented on custom/modules/Opportunities/metadata/detailviewdefs.php
> +<?php
Traspasado a core

2024-07-18 11:49 UTC, jordiSTIC commented on custom/modules/Opportunities/metadata/editviewdefs.php
> +<?php
Traspasado a core

2024-07-22 15:37 UTC, jordiSTIC commented on include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php
> +        if($module == "Campaigns" && $layout_def["subpanel_id"] == "stic_notifications") {
Creado Widget en custom/include/generic/SugarWidgets: SugarWidgetSubPanelCampaignTrackDetailViewLink
En caso que no sea una Campaña, ejecutará el código definido en SugarWidgetSubPanelDetailViewLink

2024-08-20 09:59 UTC, AlbertoSTIC requested changes

2024-08-20 09:59 UTC, AlbertoSTIC commented on modules/Campaigns/Campaign.php
> +    }
Revisar si son necesarias estas modificaciones.

2024-08-20 09:59 UTC, AlbertoSTIC commented on modules/Opportunities/metadata/detailviewdefs.php
Este fichero aparece modificado pero no tiene cambios.

2024-08-20 09:59 UTC, AlbertoSTIC commented on modules/Opportunities/metadata/editviewdefs.php
Este fichero aparece modificado pero no tiene cambios.

2024-08-20 09:59 UTC, AlbertoSTIC requested changes
Ver comentarios.

2024-08-20 13:06 UTC, jordiSTIC commented on modules/Opportunities/metadata/detailviewdefs.php
Contiene cambios: nuevos campos: `stic_opportunity_url_c` y `stic_additional_information_c`

2024-08-20 13:06 UTC, jordiSTIC commented on modules/Opportunities/metadata/editviewdefs.php
Contiene cambios: nuevos campos: `stic_opportunity_url_c` y `stic_additional_information_c`

2024-08-20 14:43 UTC, jordiSTIC commented on custom/modules/Campaigns/SticUtils.php
> +<?php
Hecho. No se ha podido mover la función `getNotificationsFromParent` dentro de la clase ya que se define como función para obtener los datos del subpanel ('get_subpanel_data') en custom/Extension/modules/Opportunities/Ext/Layoutdefs/SticLayoutdefs.php

2024-08-20 15:33 UTC, jordiSTIC commented on modules/Campaigns/Campaign.php
> +    public $notification_reply_to_addr;
Se ha verificado que no son necesarias: Las propiedades se crean dinámicamente al definir los campos en el vardefs; se eliminan las nuevas propiedades.
También se traspasa el código que sobreescribía la función `retrieve` por una función ejecutada en el LogicHook `after_retrieve`

2024-08-21 16:53 UTC, jalbaiges commented on custom/Extension/modules/Campaigns/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_LIST_STIC_NOTIFICATION_PROSPECT_LIST_NAMES_C'] = 'Llistes de Públic Objectiu';
¿Es posible que estas dos cadenas estén repetidas con las de más arriba que no incluyen la palabra _LIST_?

2024-08-21 17:05 UTC, jalbaiges requested changes
Cadenas revisadas. Ver un comentario.

2024-08-29 11:24 UTC, jordiSTIC commented on custom/Extension/modules/Campaigns/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_LIST_STIC_NOTIFICATION_PROSPECT_LIST_NAMES_C'] = 'Llistes de Públic Objectiu';
Cierto, se han eliminado las cadenas repetidas, y se usan las que no tienen la palabra _LIST_

2024-08-30 06:28 UTC, AlbertoSTIC commented on modules/EmailTemplates/EmailTemplateParser.php
> +
Estaría bien cambiar el comentario de "Opportunity" y poner módulo padre o algo así, para hacerlo más genérico.

2024-08-30 06:56 UTC, jordiSTIC commented on modules/EmailTemplates/EmailTemplateParser.php
> +
Cambiado el comentario: Se ha eliminado la palabra "Opportunities": únicamente se hace referencia a Notificaciones y módulo padre

2024-08-30 09:20 UTC, ManuSinergiaCRM requested changes
Ver comentarios de revisión

2024-08-30 09:43 UTC, jordiSTIC commented on custom/modules/Campaigns/SticUtils.js
> +  // if (STIC && STIC.campaignEmails && STIC.campaignEmails.outbound) {
Hecho

2024-08-30 10:05 UTC, jordiSTIC commented on custom/modules/Campaigns/SticUtils.php
> +            " LEFT JOIN campaigns_cstm cc on cc.id_c = c.id" .
Hecho

2024-08-30 10:05 UTC, jordiSTIC commented on custom/modules/Campaigns/SticUtils.php
> +            " LEFT JOIN campaigns_cstm cc on cc.id_c = c.id" .
Hecho

2024-08-30 10:05 UTC, jordiSTIC commented on custom/modules/Campaigns/SticUtils.php
> +        foreach ($moduleNames as $moduleName) {
Hecho

2024-08-30 10:05 UTC, jordiSTIC commented on custom/modules/Campaigns/TrackDetailView.php
> +    if ($focus->campaign_type != "Notification") {
Hecho

2024-08-30 10:05 UTC, jordiSTIC commented on custom/modules/Campaigns/TrackDetailView.tpl
> +		{$TRACK_WIZARD_BUTTON}
Hecho

2024-08-30 10:05 UTC, jordiSTIC commented on custom/modules/Campaigns/controller.php
> +require_once 'modules/Campaigns/controller.php';
Hecho

2024-08-30 10:06 UTC, jordiSTIC commented on custom/modules/Opportunities/SticUtils.php
> +}
Hecho

2024-08-30 10:18 UTC, jalbaiges approved these changes

2024-08-30 10:25 UTC, ManuSinergiaCRM requested changes
He encontrado una cosilla a nivel funcional: 

- En la edición clásica de una campaña, si salta alguna validación, aunque la campaña no sea de tipo Notificación, se muestra el panel con los campos de Notificaciones

2024-08-30 10:34 UTC, jordiSTIC commented
> He encontrado una cosilla a nivel funcional:
> 
> * En la edición clásica de una campaña, si salta alguna validación, aunque la campaña no sea de tipo Notificación, se muestra el panel con los campos de Notificaciones

Error solucionado en el commit https://github.com/SinergiaTIC/SinergiaCRM/pull/44/commits/8a725c3a86bc3ea4097491ffb5d8c5a30692b375

2024-09-03 10:03 UTC, AlbertoSTIC commented on modules/Campaigns/Campaign.php
> +        // STIC-Custom - JBL - 20240612 - Notify new Opportunities: New Campaign type (Notification)
Comentario Oportunidades.

2024-09-03 13:51 UTC, jordiSTIC commented on modules/Campaigns/Campaign.php
> +        // STIC-Custom - JBL - 20240612 - Notify new Opportunities: New Campaign type (Notification)
Hecho

2024-09-03 13:55 UTC, jordiSTIC commented
Principales cambios realizados:
- Habilitadas las Notificaciones para Eventos
- Añadida opción para crear y editar Plantillas de Email en la creación de una notificación. Las plantillas de email creadas serán del tipo Notificación, y los módulos de las variables serán los habilitados para Notificaciones
- Se han añadido textos PopUp en los campos de las Notificaciones.
- Pequeñas correcciones

2024-09-04 15:30 UTC, jalbaiges requested changes
Cadenas parcialmente revisadas. Ver comentario.

2024-09-04 15:30 UTC, jalbaiges commented on custom/Extension/modules/Campaigns/Ext/Language/ca_ES.SticLang.php
> +$mod_strings['LBL_NOTIFICATION_INBOUND_EMAIL_ID_TITLE'] = "La bústia de correu pels rebots que s'usarà per a fer el seguiment de l'estat de les Notificacions. Es pot configurar en l'apartat 'Correu e
Entiendo que, al crear una campaña de tipo notificación, en la vista de edición deberían aparecer junto a los campos los iconos "i" para mostrar la ayuda contextual, pero no es el caso. Por otro lado, diría que estas etiquetas solemos definirlas con el apéndice _HELP, no _TITLE, que se usa para títulos/encabezados de subpaneles, por ejemplo.

2024-09-10 08:27 UTC, jalbaiges requested changes
El mensaje de error de campo requerido siempre indica que falta la LPO, en todos los campos. 
![image](https://github.com/user-attachments/assets/82da0922-5554-464f-b2a8-ff5e8beabd98)

2024-09-10 09:26 UTC, ManuSinergiaCRM requested changes
Además del comentario de la revisión. 

Se detecta que al guardar una notificación desde el subpanel de eventos esta no  es creada, quedándose el CRM con el formulario de creación de la notificación abierto

2024-09-10 09:26 UTC, ManuSinergiaCRM commented on custom/modules/EmailTemplates/EditView.php
> +        if (isset($_REQUEST['type']) && $_REQUEST['type'] == "notification") {
Entiendo que este código pretende filtrar los módulos a mostrar en el campo "Insertar Variable" cuando se accede a la vista de edición de una plantilla de email de tipo "notification" pero al editar una plantilla de este tipo, $_REQUEST['type'] está a Null y no se filtra el listado de módulos.

2024-09-10 10:07 UTC, jalbaiges commented
Cadenas revisadas.

2024-09-23 07:55 UTC, jordiSTIC commented on custom/modules/EmailTemplates/EditView.php
> +        if (isset($_REQUEST['type']) && $_REQUEST['type'] == "notification") {
El funcionamiento es el mismo que en las plantillas de email de "Marqueting de email" de una campaña: Sólo se filtran los módulos para las variables si se crea o edita una plantilla desde la edición dentro de la campaña (los links de crear o editar de la plantilla a usar)
En Marketing de email, el único tipo de plantilla es "Campaña" y el único módulo para las variables es "Persona/Interesado/Público objetivo". 
En Notificaciones, el único tipo de plantilla es "Notificación" y los módulos para las variables son "Eventos" y "Subvenciones".

Este filtrado para Campañas y Notificaciones no está operativo si se crea una plantilla de email desde el módulo de Plantillas de Email

2024-09-23 10:37 UTC, jordiSTIC commented
> Además del comentario de la revisión.
> 
> Se detecta que al guardar una notificación desde el subpanel de eventos esta no es creada, quedándose el CRM con el formulario de creación de la notificación abierto

Corregido el proceso de creación de Notificaciones para eventos

2024-09-23 10:58 UTC, ManuSinergiaCRM commented on custom/modules/EmailTemplates/EditView.php
> +        if (isset($_REQUEST['type']) && $_REQUEST['type'] == "notification") {
Ok, no había visto que con las plantillas de marketing solo funciona en el asistente. 

Siendo así, no ampliaría este PR pero sí comentaría con Alberto si crear un issue para hacer que el filtrado funcione en la vista de creación y edición de una plantilla de correo.

2024-09-23 13:54 UTC, ainaraRT approved these changes
(A)Probado

2024-09-24 08:25 UTC, merged