Fix the relationship contacts/activities from subpanel
SinergiaTIC/SinergiaCRM pull request #447
Opened 2024-10-21 14:18 UTC by PaulaaSTIC

## Description
Los cambios realizados en el PR https://github.com/SinergiaTIC/SinergiaCRM-SuiteCRM/pull/849 provocan el issue https://github.com/SinergiaTIC/SinergiaCRM/issues/444

2024-10-23 09:11 UTC, enricsinergia approved these changes
(A)probado

2024-10-28 14:27 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-10-28 14:37 UTC, ManuSinergiaCRM requested changes
La línea de código que se está comentando solucionaba la incidencia para relaciones especiales como **member_accounts** donde **parent_id** no es igual al **ID del registro principal** y ahora vuelve a ocurrir el error. 

Se propone investigar y averiguar si se puede añadir alguna condición más que permita solucionar ambas incidencias. 

Si no es sencillo, y por lo que recuerdo no lo será ya que la función **set_relationship_info()** tenía complejidad, una opción alternativa y sencilla es quitar la opción de Editar en los subpaneles de aquellas relaciones especiales como **member_accounts**

Paula, si lo consideras, podemos comentarlo :) 

**Como reproducir la incidencia**
1. Crear dos organizaciones.
2. Ir a una de ellas y seleccionar a la otra en el subpanel de Organizaciones miembro
3. Desde el mismo subpanel, editar el registro y cambiar varios campos, incluido el campo **Miembro de** 
4. Comprobar que en la organización se han actualizado los campos modificados  excepto el de **Miembro de**

2024-11-27 11:43 UTC, PaulaaSTIC commented
> La línea de código que se está comentando solucionaba la incidencia para relaciones especiales como **member_accounts** donde **parent_id** no es igual al **ID del registro principal** y ahora vuelve a ocurrir el error.
> 
> Se propone investigar y averiguar si se puede añadir alguna condición más que permita solucionar ambas incidencias.
> 
> Si no es sencillo, y por lo que recuerdo no lo será ya que la función **set_relationship_info()** tenía complejidad, una opción alternativa y sencilla podría ser quitar la opción de **Editar** en los subpaneles de aquellas relaciones especiales como **member_accounts**
> 
> Paula, si lo consideras, podemos comentarlo :)
> 
> **Como reproducir la incidencia**
> 
> 1. Crear dos organizaciones.
> 2. Ir a una de ellas y seleccionar a la otra en el subpanel de Organizaciones miembro
> 3. Desde el mismo subpanel, editar el registro y cambiar varios campos, incluido el campo **Miembro de**
> 4. Comprobar que en la organización se han actualizado los campos modificados  excepto el de **Miembro de**

El error mencionado ocurría cuando el subpanel, y por lo tanto la nueva relación, correspondía a un registro del mismo módulo que el módulo padre. Se ha añadido una comprobación específica para este tipo de casos.

2024-11-28 11:40 UTC, ManuSinergiaCRM submitted a review, later dismissed
(A)probado

Se observa que la condición aportada en este PR amplia la cobertura de la condición que sustituye para gestionar correctamente registros que tienen una relación con el registro que contiene al subpanel (registro padre) además de un campo posiblemente relacionado (por ej: registros de llamadas, reuniones o notas), de forma que el registro indicado en el campo posiblemente relacionado no pierda la información por indicar un ID diferente al ID del registro padre. 

La solución ha funcionado correctamente para los casos de uso probados, incluyendo registros con una relacion 1-N personalizada que relaciona a un módulo consigo mismo.

2024-12-10 10:04 UTC, enricsinergia approved these changes
(A)probado

Probado con reuniones y llamadas.
Creación desde subpanel, desde edición, cambiar persona apuntada, cambiar la organización....
También se ha probado con Subvenciones para las relaciones N:M que se pauntaban en el PR anterior.

2024-12-10 10:09 UTC, ManuSinergiaCRM requested changes
Encontrado un caso de uso erróneo ya que `$this->{$new_rel_link}` llega a `NULL`

**Como reproducirlo**
1. Desde la vista de detalle de una organización (O1), crear una organización nueva desde el subpanel de **Organizaciones Miembro** e indicar en el campo **Miembro de** una organización distinta a O1
2. Comprobar que la nueva organización es miembro de O1 aunque se indicó otra. 

Al editar esa misma organización desde el subpanel de **Organizaciones miembro** de O1 y cambiar el valor del campo **Miembro de** `$this->{$new_rel_link}`  es igual a `''` (cadena vacía) y al no ser `NULL` sí funciona correctamente

2024-12-13 11:11 UTC, enricsinergia approved these changes
(A)provado

2024-12-19 08:16 UTC, merged

2025-02-07 16:45 UTC, PaulaaSTIC commented
PR en SA con todos los cambios: https://github.com/salesagility/SuiteCRM/pull/10636