Hotfix - Importación - Evitar uso de variable no definida
SinergiaTIC/SinergiaCRM pull request #470
Opened 2024-10-31 08:53 UTC by enricsinergia

- Closes #451 
- 
## Description
Se resuelven las 2 trazas explicadas en #451.
En el primer caso se estaba usando $key enla expresión $this->$key sin comprobar que $key estuviera informado, lo que generaba elpertiennte warning.
En el segundo caso se realizaban acciones que sólo debían hacerse en creación del registro. PAra ello se comparaban los datos con fetched_row pero sin comprobar si éste estaba informado.

## Motivation and Context
Derivado del proceso realizado para eliminar trazas innecesarias del log, se detectan estas 2 situaciones que se producen en la importación.

## How To Test This
1.- Realizar una importación de Personas y comprobar que no se producen las trazas en el log

2024-12-17 11:57 UTC, ManuSinergiaCRM submitted a review, later dismissed
(A)probado

2024-12-17 12:58 UTC, jordiSTIC requested changes
Ver comentario

2024-12-17 12:58 UTC, jordiSTIC commented on data/SugarBean.php
Falta STIC Custom y comentar el código antiguo: Los cambios de JCH en el core se han pasado al core de la versión 7.14.6 y será difícil su seguimiento

2024-12-18 08:45 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-12-18 10:52 UTC, jordiSTIC approved these changes
(A)Probado

2024-12-19 08:19 UTC, merged