Enhancement - SinergiaDA -October2/November
SinergiaTIC/SinergiaCRM pull request #478
Opened 2024-11-13 15:49 UTC by juanSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-11-26 15:31 UTC, juanSTIC commented
@BelenFFernandez te he citado en este PR porque aunque no es de SinergiaDA directamente establece límites en el uso de SinergiaDA y necesita ser documentado. Lo comentamos.

2024-11-28 10:30 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2024-12-16 10:42 UTC, AlbertoSTIC requested changes
Lo he probado en alberto.sinergiacrm.org y, aunque parece que las vistas se han creado, aparecen multiples mensajes de error de este tipo:
```
2024-12-16 11:36:31 [2585984][2][ERROR] Line 1917: ExternalReporting::batchInsertPermissions: Invalid record structure: Array
(
    [user_name] => pastic
    [table] => sda_stic_work_calendar
    [column] => users_id
    [stic_permission_source] => ACL_ALLOW_ALL
    [global] => 1
)
```
y
```
2024-12-16 11:36:32 [2585984][2][FATAL] Mysqli_query failed.
2024-12-16 11:36:32 [2585984][2][FATAL]  Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_prospect_list_ids_dynamic_prospect_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2024-12-16 11:36:32 [2585984][2][ERROR] Line 1610: ExternalReporting::createEnumView: Error has occurred: [ Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_prospect_list_ids_dynamic_prospect_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1] running Query: [CREATE OR REPLACE VIEW sda_l_campaigns_notification_prospect_list_ids_dynamic_prospect_ AS ]
2024-12-16 11:36:32 [2585984][2][FATAL] Mysqli_query failed.
2024-12-16 11:36:32 [2585984][2][FATAL]  Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_template_id_dynamic_email_template_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2024-12-16 11:36:32 [2585984][2][ERROR] Line 1610: ExternalReporting::createEnumView: Error has occurred: [ Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_template_id_dynamic_email_template_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1] running Query: [CREATE OR REPLACE VIEW sda_l_campaigns_notification_template_id_dynamic_email_template_ AS ]
2024-12-16 11:36:32 [2585984][2][FATAL] Mysqli_query failed.
2024-12-16 11:36:32 [2585984][2][FATAL]  Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_outbound_email_id_dynamic_outbound_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2024-12-16 11:36:32 [2585984][2][ERROR] Line 1610: ExternalReporting::createEnumView: Error has occurred: [ Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_outbound_email_id_dynamic_outbound_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1] running Query: [CREATE OR REPLACE VIEW sda_l_campaigns_notification_outbound_email_id_dynamic_outbound_ AS ]
2024-12-16 11:36:32 [2585984][2][FATAL] Mysqli_query failed.
2024-12-16 11:36:32 [2585984][2][FATAL]  Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_inbound_email_id_dynamic_inbound_em AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2024-12-16 11:36:32 [2585984][2][ERROR] Line 1610: ExternalReporting::createEnumView: Error has occurred: [ Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_inbound_email_id_dynamic_inbound_em AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1] running Query: [CREATE OR REPLACE VIEW sda_l_campaigns_notification_inbound_email_id_dynamic_inbound_em AS ]
```

2024-12-16 15:26 UTC, juanSTIC commented
> 2024-12-16 11:36:31 [2585984][2][ERROR] Line 1917: ExternalReporting::batchInsertPermissions: Invalid record structure: Array
> (
>     [user_name] => pastic
>     [table] => sda_stic_work_calendar
>     [column] => users_id
>     [stic_permission_source] => ACL_ALLOW_ALL
>     [global] => 1
> )

Para este caso se ha añadido el valor para el campo _group_ (null) en los dos sitios dónde no se estaba haciendo

2024-12-16 15:30 UTC, juanSTIC commented
> 2024-12-16 11:36:32 [2585984][2][FATAL]  Query Failed: CREATE OR REPLACE VIEW sda_l_campaigns_notification_prospect_list_ids_dynamic_prospect_ AS : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

Los logs de este tipo se producen porque algún campo referencia a listas desplegables que no existen, lo que no es habitual en producción, pero más común en entornos de desarrollo.

Se corrije haciendo un comprobación específica de si existe o no la lista desplegable, en caso de que no exista se muestra un log con más información y se sale de la función sin intentar hacer la query.

2024-12-17 10:08 UTC, AlbertoSTIC requested changes
Revisados los puntos anteriores y son correctos.

En mi instancia se ve este mensaje en errors.log:
```
[Tue Dec 17 11:06:24.601405 2024] [proxy_fcgi:error] [pid 2155803:tid 2155822] [remote 79.116.233.62:33474] AH01071: Got error 'PHP message: PHP Warning:  unlink(sdaRebuildError.txt): No such file or directory in /usr/home/alberto.sinergiacrm.org/web/SticInclude/SinergiaDARebuild.php on line 66', referer: https://alberto.sinergiacrm.org/index.php?module=Administration&action=sticmanagesdaintegration
```

2024-12-17 14:34 UTC, juanSTIC commented
> En mi instancia se ve este mensaje en errors.log:
Aunque no es un código de este PR se ha corregido, evitando el enaje de warning

2025-01-20 11:25 UTC, AlbertoSTIC approved these changes
Aprobado

2025-01-22 05:19 UTC, merged