Enhancement - Plantillas PDF - Valores del checkbox traducidos
SinergiaTIC/SinergiaCRM pull request #486
Opened 2024-11-25 16:25 UTC by ainaraRT

- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/485

## Description

Como se menciona en el issue, se ha comprobado que, al mostrar datos de campos de tipo casilla de verificación en una Plantilla PDF, los valores no salen en el idioma que corresponda (español/catalán, en función del idioma con el que accede cada usuario). Actualmente, en las plantillas sale "true" o "false".

## Motivation and Context

Se ha implementado las diferentes cadenas de los valores de las casillas de verificación que aparecía al principio en inglés, por ello se ha implementado la función de `translate()` para que recoja dichas cadenas según el idioma seleccionado en el login.

## How To Test This

1. Acceder con cualquier idioma al CRM.
2. Ir a cualquier módulo y crear un campo de tipo "Casilla de verificación".
3. Crear una plantilla PDF de dicho módulo.
4. Generar la plantilla y comprobar que la respuesta de esa casilla está en el idioma seleccionado en el login o el que tiene por defecto la instancia.

2024-11-25 17:01 UTC, jalbaiges requested changes
No estoy completamente convencido de ello, pero creo que en lugar de usar las cadenas _Verdadero/Falso_ usaría _Sí/No_. Me da la sensación que en una plantilla, particularmente si no es para uso interno, el destinatario del documento entenderá mejor un _Sí/No_ que un _Verdadero/Falso_. A valorar, en cualquier caso.

2024-11-26 16:08 UTC, ainaraRT commented
> No estoy completamente convencido de ello, pero creo que en lugar de usar las cadenas _Verdadero/Falso_ usaría _Sí/No_. Me da la sensación que en una plantilla, particularmente si no es para uso interno, el destinatario del documento entenderá mejor un _Sí/No_ que un _Verdadero/Falso_. A valorar, en cualquier caso.

Como tal, es la traducción literal de lo que significa esa casilla (True/False), aún así, la entidad podrá editar dichas etiquetas y poner lo que ellos mejor entiendan

2024-11-26 17:03 UTC, jalbaiges approved these changes

2024-11-28 10:41 UTC, jordiSTIC approved these changes
(A)Probado

2024-11-28 10:56 UTC, PaulaaSTIC approved these changes
(A)probado

2024-12-19 08:16 UTC, merged

2025-01-20 16:54 UTC, SinergiaCRM commented
PR en SA: https://github.com/salesagility/SuiteCRM/pull/10622