Hotfix - Administración - Valores por defecto de DateTime traducidos y valor "first day of next month" corregido
SinergiaTIC/SinergiaCRM pull request #488
Opened 2024-11-26 12:11 UTC by ainaraRT

- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/466
- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/99

## Description

Este PR resuelve dos incidencias.
1. La primera, como se describe en el issue, se detectaba que en la vista de creación/edición de campos de Estudio, para campos de tipo DateTime, los valores por defecto a seleccionar no se muestran en los diferentes idiomas, si no que se muestran siempre en inglés.
2. En la segunda, se detecta que si se selecciona el Valor por defecto "first day of next month" para un campo de tipo "DateTime", de cualquier módulo, la instancia da un error que la deja inutilizable.

## Motivation and Context

1. Se ha añadido la función del constructor junto a `$app_strings` donde se recoge las etiquetas del desplegable. Generando dicho desplegable.
2. Se ha corregido el valor `"first of next month"` que estaba generando problema, por `"first day of next month"`.

## How To Test This

1. Ir a Estudio, a un módulo cualquiera y añadir un campo.
3. Crear un campo de tipo Fecha y hora (DateTime) y comprobar que se muestra la lista de los valores por defecto en el idioma que el usuario ha seleccionado en el login o tiene la instancia por defecto.
4. Además, comprobar que al seleccionar "primer día del próximo mes" (first day of next month), se puede guardar el campo y se visualiza correctamente sin generar un error que impide acceder a "Administración".

2024-11-26 15:34 UTC, jalbaiges requested changes
Cadenas revisadas. Ver comentario sobre comentarios STIC-Custom.

2024-11-26 15:34 UTC, jalbaiges commented on include/language/ca_ES.lang.php
> +    // STIC-Custom 20241126 ART - Translated Default Datetime Values
En los cambios de los ficheros de idiomas que no sean el inglés no hace falta poner los comentarios _// STIC-Custom_ porque no son ficheros que se incluyan en PR al core de SuiteCRM.

2024-11-26 17:08 UTC, jalbaiges commented on include/language/ca_ES.lang.php
> +    // STIC-Custom 20241126 ART - Translated Default Datetime Values
Cierto, hay otros. Como norma general no debería ser necesario que estuvieran, aunque podemos distinguir dos casos: aquellos en los que se introducen cambios que acabarán llegando al core de SuiteCRM y aquellos que quedarán en el contexto de SinergiaCRM. Los primeros no hay necesidad de etiquetarlos, en tanto que en los últimos opcionalmente puede considerarse. En el caso que nos ocupa estaríamos en el primer escenario.

2024-11-26 17:10 UTC, jalbaiges approved these changes
Aprobado a efectos de cadenas y a valorar el tema los comentarios _// STIC-Custom_.

2024-12-04 06:19 UTC, enricsinergia requested changes
Funciona correctamente, incluso los literales con apóstrofe :)
Sin embargo, aplicaría elpequeño cambio comentado sobre mayúsculas y minúsculas

2024-12-04 06:19 UTC, enricsinergia commented on include/language/es_ES.lang.php
>      'LBL_YESTERDAY' => 'Ayer',
Una pequeñísima tontería: Si el resto de opciones empiezan en minúscula, esta también debería hacerlo.

2024-12-04 06:19 UTC, enricsinergia commented on include/language/gl_ES.lang.php
>      'LBL_YESTERDAY' => 'Onte',
ídem que en español

2024-12-04 08:53 UTC, ainaraRT commented on include/language/gl_ES.lang.php
>      'LBL_YESTERDAY' => 'Onte',
Corregido!

2024-12-04 08:53 UTC, ainaraRT commented on include/language/es_ES.lang.php
>      'LBL_YESTERDAY' => 'Ayer',
Corregido!

2024-12-16 17:06 UTC, enricsinergia approved these changes
(A)provado

2024-12-18 16:30 UTC, juanSTIC approved these changes
Visto y probado

2024-12-19 08:21 UTC, merged