Hotfix - Flujos de trabajo - Error en fórmula del cálculo de mes
SinergiaTIC/SinergiaCRM pull request #49
Opened 2024-01-10 17:22 UTC by ainaraRT

- Closes #48 

**Desarrollo del issue**
Al crear un flujo de trabajo para que calcule el mes, con ceros a la izquierda, de un campo fecha, devuelve el mes sin dichos ceros.

**Solución implementada:**
Este código recorre en iteración una lista de fórmulas, calcula sus valores y los establece en los campos apropiados del objeto bean. Garantizando que los valores numéricos se almacenen en el tipo de datos correcto.

**Pruebas**
1. Crear un FdT
- Módulo de Flujo de Trabajo: Personas
- Ejecutar en: Nuevos registros
- Ejecutar: Al guardar

2. Acción: Calcular campos
- Parámetros ->Fecha de nacimiento{P0}
- Fórmulas-> Descripción {date(m;{P0})}

3. Crear una nueva persona rellenando el campo Fecha de nacimiento
4. Comprobar que en descripción se ha guardado el valor del mes con el cero a la izquierda.

2024-01-17 11:59 UTC, jordiSTIC approved these changes
(A)Probado

2024-01-17 12:20 UTC, PaulaaSTIC requested changes
En el código anterior, también se tenían en cuenta los tipos siguientes: 'double', 'uint', 'ulong', 'long', 'short' y 'tinyint'. Creo que deberían incluirse.

`if (in_array($fieldType, ['float', 'decimal', 'currency', 'double', 'uint', 'ulong', 'long', 'short', 'tinyint'])) {
`

2024-01-18 09:02 UTC, jordiSTIC approved these changes
(A)Probado

2024-01-18 09:03 UTC, PaulaaSTIC approved these changes
(A)probado

2024-01-18 09:03 UTC, merged