Mejora - Economía - Mostrar información de previsión de pagos pendientes y de pagos realizados
SinergiaTIC/SinergiaCRM pull request #5
Opened 2024-01-02 09:05 UTC by juanSTIC

**¿Está tu propuesta relacionada con algún problema o falta de funcionalidad?**
Las entidades usuarias del CRM suelen querer conocer cuánto dinero van a ingresar en lo que queda del año en curso. Mediante informes es bastante complicado de resolver, de forma que se valora disponer de una vía alternativa.

**Descripción de la propuesta**
Se propone la creación de dos campos en el módulo _Compromisos de Pago_ (CdP):

1) **Cuota anualizada pendiente**: Este campo reflejaría el importe pendiente de pago en el año en curso basándose en el importe, la periodicidad y las fechas de primer pago y de baja (si existe) del propio CdP. El valor de este campo se calcularía automáticamente para cada CdP en el momento de la generación de los pagos recurrentes y cada vez que se modifique alguno de los campos involucrados del propio CdP. A tener en cuenta que no deben excluirse los CdP de periocidad puntual (es decir, si hay un CdP puntual con fecha de primer pago futura debe ser considerado).

2) **Cuota anualizada pagada**: Este campo reflejaría el importe total ya satisfecho mediante los pagos en estado pagado y con fecha de pago entre el día 1 de enero y el mes en curso. El valor de este campo se calcularía automáticamente cada vez que se modifique alguno de los pagos del CdP (importe, estado, vinculación a/desvinculación de CdP, etc.). 

Además, se propone la **creación en KReporter de campos virtuales para los doce meses posteriores al mes en curso** (mes + 1, mes + 2, etc.) que permitan presentar la información de los ingresos previstos de forma mensualizada. Estos campos se calcularán/comportarán de forma análoga al campo Cuota anualizada pendiente salvo en el período al que aplicarán.

2024-03-18 12:05 UTC, jalbaiges submitted a review, later dismissed
Cadenas revisadas.

2024-03-19 10:03 UTC, enricsinergia requested changes
Pruebas realizadas:
Crear CdP desde subpanel
Crear CdP desde vista edición
 - Pago actual
 - Pago atrasado
 - Pago futuro 
Crear pago (atrasado) desde subpanel de CdP
Añadir un pago (pagado y no pagado) a un CdP
Cambiar estado a pago a pagado e impagado
Crear nuevo pago pagado (se echa de menos el refresco automático)
Cambiada periodicidad a CdP
Creada remesa i enviada a pago (incluso remea grande > 20.000 registros)
Informe previsión


Punto detectado: introdución de pagos futuros:
El cálculo cuando hay pagos futuros introducidos o es correcto. Se podría incorporar a recalculateAllFuturePaymentsViaSQL la suma de los pagos futuros y restarla de la calculada. Otra alternativa sería calcular la proyección primero y luego cuando se calcula el importe pagado, modificar esa SQL para que calcule lo pagado con fecha anterior y con fecha posterior, y actualice los 2 importes.
Hay algunas entidades que al captar una cuota, ésta se introduce con fecha del 1 del mes siguiente, por lo que estos cálculos podríanintroducir un desvío importante. 
También está el caso de introducir cuotas con fecha futura para establecer un precio por debajo del que marca el CdP (puede ser una oferta puntual de 3 meses, una negociación para no perder un socio...)
También habría que modificar, si se quieren tener presentes esos pagos futuros, el LH cuando se cambia el estado de pago para recalcular esta proyección.




En las pruebas, a pesar de tener un cierto volumen, no he notado lentitud. De todas formas, no sería descabellado pensar en incluir un índice en pagos por fecha.

2024-03-19 11:03 UTC, juanSTIC commented on modules/stic_Payment_Commitments/Utils.php
> +    public static function getPaidPayments($PCBean)
correcto. Eliminado.

2024-03-19 11:04 UTC, juanSTIC commented on modules/stic_Payment_Commitments/Utils.php
> +    public static function setPendingPayments($PCBean)
correcto. Eliminado

2024-03-19 11:08 UTC, juanSTIC commented on modules/stic_Payment_Commitments/Utils.php
> +        // Este SQL no usa ninguna tabla específica, pero se ha visto que es muy efectivo para
comentario completado ;)

2024-03-19 11:12 UTC, juanSTIC commented on modules/stic_Payment_Commitments/vardefs.php
> +            'importable' => 1,
cambiado

2024-03-19 11:50 UTC, juanSTIC commented on SticUpdates/Migrations/20230802_feature_payments_prevision.sql
> +UPDATE stic_payment_commitments pc
1) Se ha quitado el filtro de CdP Avtivos y se ha incluido los compromisos de pago que no tengan fecha de finalización o que esta sea del año actual.
2) Se ha quitado el WHERE redundante

2024-03-19 12:05 UTC, juanSTIC commented
> Pruebas realizadas: Crear CdP desde subpanel Crear CdP desde vista edición
> 
> * Pago actual
> * Pago atrasado
> * Pago futuro
>   Crear pago (atrasado) desde subpanel de CdP
>   Añadir un pago (pagado y no pagado) a un CdP
>   Cambiar estado a pago a pagado e impagado
>   Crear nuevo pago pagado (se echa de menos el refresco automático)
>   Cambiada periodicidad a CdP
>   Creada remesa i enviada a pago (incluso remea grande > 20.000 registros)
>   Informe previsión
> 
> Aparte de los comentarios, punto detectado: introdución de pagos futuros: El cálculo cuando hay pagos futuros introducidos o es correcto. Se podría incorporar a recalculateAllFuturePaymentsViaSQL la suma de los pagos futuros y restarla de la calculada. Otra alternativa sería calcular la proyección primero y luego cuando se calcula el importe pagado, modificar esa SQL para que calcule lo pagado con fecha anterior y con fecha posterior, y actualice los 2 importes. Hay algunas entidades que al captar una cuota, ésta se introduce con fecha del 1 del mes siguiente, por lo que estos cálculos podríanintroducir un desvío importante. También está el caso de introducir cuotas con fecha futura para establecer un precio por debajo del que marca el CdP (puede ser una oferta puntual de 3 meses, una negociación para no perder un socio...) También habría que modificar, si se quieren tener presentes esos pagos futuros, el LH cuando se cambia el estado de pago para recalcular esta proyección.
> 
> En las pruebas, a pesar de tener un cierto volumen, no he notado lentitud. De todas formas, no sería descabellado pensar en incluir un índice en pagos por fecha.

Se descarta esta propuesta debido a la dificultad de contemplar las diferentes casuisticas que pueden provocar que haya pagos futuros registrados en el CRM, incluyendo los pagos en que se indica fecha de primer pago futura, o situaciones en que se hacen ajustes a los usuarios  creando pagos futuros con importes diferentes al del CdP, pero que impediran que se genere el pago concurrente del mes ...

2024-03-19 12:09 UTC, juanSTIC commented on modules/stic_Remittances/Utils.php
> +            $paidAnnualizedFeeSQL = "UPDATE stic_payment_commitments pc
El modo actual no aumenta el "tamaño" de la query, sino que simplemente añade el texto de la subconsulta, por lo que no debería afectar en el sentido indicado.

2024-03-19 12:10 UTC, juanSTIC commented on modules/stic_Payment_Commitments/Utils.php
> +        WHERE pc.id IN (SELECT id FROM stic_payment_commitments where active=1 AND deleted=0 ) ;";
Corregido

2024-03-20 10:47 UTC, enricsinergia commented on SticUpdates/Migrations/20230802_feature_payments_prevision.sql
> +UPDATE stic_payment_commitments pc
La nueva SQL, en local, me da error en la condición `OR end_date = ''`. Sin embargo en lainstancia develop no da mayor problema. Lo dejaremos pasar y esperemos que en Iridia no nos fastidie.

2024-03-20 11:08 UTC, enricsinergia commented on SticUpdates/Migrations/20230802_feature_payments_prevision.sql
> +UPDATE stic_payment_commitments pc
Revisado este punto se ve que es por SQL_MODE. Se debe revisar ya que Iridia, como mínimo, no tiene el mismo modo que nuestro servidor.

2024-03-20 11:08 UTC, enricsinergia commented on modules/stic_Payment_Commitments/Utils.php
> +        WHERE pc.id IN (SELECT id FROM stic_payment_commitments where active=1 AND deleted=0 ) ;";
Ídem anterior

2024-03-20 15:29 UTC, enricsinergia approved these changes
(A)provado

2024-03-21 07:06 UTC, AlbertoSTIC approved these changes
Aprobado

2024-03-21 07:39 UTC, enricsinergia approved these changes
(A)provado

2024-03-21 08:00 UTC, merged