Hotfix - Administración - Altura de IFrame no se recogía al cambiarla
SinergiaTIC/SinergiaCRM pull request #502
Opened 2024-12-03 10:39 UTC by ainaraRT

- Closes https://github.com/SinergiaTIC/SinergiaCRM/issues/335

## Description

Como se describe en el issue, no es posible establecer la altura de un campo iframe. Aunque se configure en el estudio, al insertarlo en una vista de detalle de cualquier módulo, la altura no se respeta.
Esto es debido a que en Estudio, al cambiar la altura, no se respeta el nuevo valor que se le establecía, sino que volvía a guardarse con el valor original.
Como tal, el rango de la altura es de 100 a 1024, por lo que menor o mayor a este rango no se cambiará.

## Motivation and Context

Se ha añadido una condición en el que al generar la caché, se guarde el valor añadido en el párametro de la altura:
`$row["ext4"] = $saveCache->ext4;`
Además de añadirlo en la tabla de "módulo_cstm":
`$to_save['ext4'] = (isset($field->ext4) ? $field->ext4 : '');`

## How To Test This

1. Crear un campo, en cualquier módulo, de tipo iframe añadiendo una altura inicial de entre 100 y 1024.
2. Agregar dicho campo a la vista de detalle.
3. Añadir un iframe con dicha altura (ej: https://placehold.co/300), volver a cargar la página y comprobar que es la atura definida.
4. Volver a estudio y editar la altura.
5. Comprobar que se ha guardado correctamente, dentro de estudio, y comprobarlo en la vista de detalle

2024-12-17 15:50 UTC, PaulaaSTIC requested changes
No se recoge bien la altura del iframe cuando es 100, no se guarda en estudio.

2025-01-13 09:04 UTC, PaulaaSTIC approved these changes
(A)probado, se modificia el tamaño del iframe conforme el valor establecido en estudio.

2025-01-14 08:14 UTC, juanSTIC requested changes
En mi opinión el plateamiento utilizado es icorrecto. Se está actualizando el valor de ext4 en fields_meta_data, lo cual es algo no habitual en el CRM, además de nos ser necesario. Cuando en estudio se modifica la altura del iframe, esta queda correcatmente refljada en el fichero vardef correspondiente, por ejemplo:
```php
<?php
// custom/Extension/modules/stic_Sepe_Actions/Ext/Vardefs/_override_sugarfield_test_c.php
// ...
$dictionary['stic_Sepe_Actions']['fields']['test_c']['link_target']='110';
// ...
```

Los valores de _fields_meta_data_ quedan exclusivamente para la el momento de la creación del campo.

La solución del PR debería de hacerse en el punto dónde se recuperan los valores del `bean` para renderizar el iframe y no  dónde se hacen ahora.

2025-01-14 08:21 UTC, juanSTIC requested changes
En mi opinión el plateamiento utilizado es icorrecto. Se está actualizando el valor de ext4 en fields_meta_data, lo cual es algo no habitual en el CRM, además de nos ser necesario. Cuando en estudio se modifica la altura del iframe, esta queda correcatmente refljada en el fichero vardef correspondiente, por ejemplo:
```php
<?php
// custom/Extension/modules/stic_Sepe_Actions/Ext/Vardefs/_override_sugarfield_test_c.php
// ...
$dictionary['stic_Sepe_Actions']['fields']['test_c']['link_target']='110';
// ...
```

La solución del PR debería contemplar la lectura/escritura del nuevo valor de altura del iframe en el fichero vardef correspondiente, no en  _fields_meta_data_ cuyos valores quedan exclusivamente para la el momento de la creación del campo.

Una de las consecuencias del enfoque actual es que la solución solamente sirve para los campos creados en estudio, pero no para los hechos con el constructor de módulos, ya que estos no utilizan la _tabla fields_meta_data_

2025-01-20 15:19 UTC, juanSTIC requested changes
Veo los siguientes errores:

- Al crear un nuevo campo iframe en estudio (antes de modificarlo nuevamente) no se utiliza la altura definida en estudio, siempre se renderiza con un 200px independientemente de lo indicado al crear el campo.

- Al modificar el campo en estudio, se escribe en el fichero _vardef_ las propiedades del campo del siguiente modo:
  ```
     $dictionary['stic_Sepe_Actions']['fields']['test_iframe_c']['link_target']='155';
     $dictionary['stic_Sepe_Actions']['fields']['test_iframe_c']['height']='125';
  ```

     - La primera de las propiedades (_link_target_) es errónea, ya que _link_target_ nada tiene que ver con la altura y no debería usarse en este PR, sin embargo el valor de esta propiedad es el que se cargará al modificar el campo en estudio.
     - La segunda de las propiedades (_height_) es la que se debería estar usando en cualquiera de los casos, ya que es la que se utiliza para renderizar el campo en las vistas y la que **debería** usarse para recuperar el valor del campo en estudio.

2025-06-11 09:45 UTC, juanSTIC requested changes
Al editar en estudio un campo iframe, previamente creado, además de asignarle la altura indicada en estudio en la propiedad _height_, lo cual hace correctamente, también la asigna  en la propiedad _link_target_, lo cual debería ser corregido.

```php
<?php
 // created: 2025-06-11 11:41:17
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['height']='252';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['default']='';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['display_default']='';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['required']=false;
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['inline_edit']='1';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['massupdate']=0;
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['duplicate_merge']='0';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['duplicate_merge_dom_value']='0';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['merge_filter']='disabled';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['labelValue']='iframe';
$dictionary['stic_Sepe_Actions']['fields']['iframe_c']['link_target']='252';
```

2025-06-12 11:41 UTC, ainaraRT commented
> Al editar en estudio un campo iframe, previamente creado, además de asignarle la altura indicada en estudio en la propiedad _height_, lo cual hace correctamente, también la asigna en la propiedad _link_target_, lo cual debería ser corregido.
> 
> ```
> <?php
>  // created: 2025-06-11 11:41:17
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['height']='252';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['default']='';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['display_default']='';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['required']=false;
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['inline_edit']='1';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['massupdate']=0;
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['duplicate_merge']='0';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['duplicate_merge_dom_value']='0';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['merge_filter']='disabled';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['labelValue']='iframe';
> $dictionary['stic_Sepe_Actions']['fields']['iframe_c']['link_target']='252';
> ```

Se ha creado un [issue](https://github.com/SinergiaTIC/SinergiaCRM/issues/676) para corregirlo de manera general.

2025-06-18 11:29 UTC, juanSTIC approved these changes
Visto y probado

2025-06-23 15:01 UTC, PaulaaSTIC approved these changes
(A)probado

2025-06-25 07:27 UTC, merged