Hotfix - KReports - Se desplaza el quote de los valores a operadores concretos
SinergiaTIC/SinergiaCRM pull request #523
Opened 2024-12-20 11:56 UTC by enricsinergia

## Description
En el PR #505 se introduce el quote de los valores introducidos por el usuario. Se ve que existe un problema con determinados operadores (por ejemplo el "es uno de "). 
En este PR se anula el quote de manera general y se mueve a los operadores donde debe funcionar.

## How To Test This
1.- Crear un informe con distintos filtros
2.- Probar los filtros básicos (modificados): autocomplete, equals, soundslike, notequal, greater, after, less, before, greaterequal, lessequal, starts, notstarts, contains, notcontains, between
3.- Probar alguno de los filtros que fallaban (oneof)

2025-01-21 08:45 UTC, ManuSinergiaCRM requested changes
1) Si se deshace lo realizado en el PR 505, yo eliminaría las referencias al PR 505 en el código.

2) Los siguientes operadores fallan con multienum:

- Empieza por, No empieza por, Contiene y No contiene parece que operan con el identificador y no con la etiqueta del valor.

- Igual y Distinto de (≠) → Además, veo que también fallan seleccionando la opción de Castellano.

- **No es uno de o NULL** devuelve registros sin valor en el campo o con valor NULL (configurado a través de base de datos), es decir, devuelve lo mismo que **No es uno de**. Por ahora entiendo que queremos que devuelva aquellos registros con valor diferente o con valor Nulo. 


3. El operador **Es uno de** funciona correctamente

4. El operador: **distinto de (≠),** como indicaba antes,  falla al realizar la prueba propuesta

2025-01-31 08:42 UTC, enricsinergia commented
> 1. Si se deshace lo realizado en el PR 505, yo eliminaría las referencias al PR 505 en el código.
Aplicado

> 2. Los siguientes operadores fallan con multienum:
> 
> * Empieza por, No empieza por, Contiene y No contiene parece que operan con el identificador y no con la etiqueta del valor.
Estos operadores trabajan con el valor interno (key) y no con el literal. Cambiarlo podría afectar a informes ya realizados, asemás al ser los literales distintos en cada idioma podría dar resultados aleatorios, por lo que más razonable sería anular los operadores para campos enum y multineum, pero se decide mantenerlos y no privar de esta posibilidad a las entidades

> * Igual y Distinto de (≠) → Además, veo que también fallan seleccionando la opción de Castellano.
> * **No es uno de o NULL** devuelve registros sin valor en el campo o con valor NULL (configurado a través de base de datos), es decir, devuelve lo mismo que **No es uno de**. Por ahora entiendo que queremos que devuelva aquellos registros con valor diferente o con valor Nulo.
> 
> 3. El operador **Es uno de** funciona correctamente
> 4. El operador: **distinto de (≠),** como indicaba antes,  falla al realizar la prueba propuesta
Se ha revisado y corregido el comporatmiento con multi-enum.

2025-01-31 11:14 UTC, ManuSinergiaCRM requested changes
A nivel funcional veo todo OK menos el operador "No es uno de o NULL" que si tienes 3 personas con perfil de trabajador:

- Persona 1: Restauración
- Persona 2: Limpieza
- Persona 3: Restauración y Limpieza
- Persona 4: Vacio

Y pones el filtro de que "No es uno de o NULL de "Restauración, Limpieza" te devuelve Persona 1, Persona 2 y Persona 4 cuando solo debería devolver Persona 4



A nivel de código, ver el resto de comentarios de la revisión

2025-01-31 11:52 UTC, enricsinergia commented on modules/KReports/js/kreportsbase2.js
> +                                        else {
No se modifica, no, pero entras aquí con un multiple case:
                        case "user_name":
                        case "assigned_user_name":
                        case "enum":
                        case "parent_type":
                        case "radioenum":
                        case "dynamicenum":
                        case "multienum":
Para todos los casos que no es multienum, se mantiene el editor que había, sólo he cambiado el editor para los multienum. No lo he puesto en un case separado del resto porqué se realizan más acciones que no sólo la creación del editor y no quise duplicar más código.

2025-01-31 11:52 UTC, enricsinergia commented on modules/KReports/js/kreportsbase2.js
> +                                        debugger;
OMG

2025-01-31 11:54 UTC, enricsinergia commented on modules/KReports/js/kreportsbase2.js
> +                                else {
Es el mismo caso también. Entras con un múltiple case y puede ser otro tipo el que te traiga aquí.

2025-01-31 11:59 UTC, ManuSinergiaCRM commented on modules/KReports/js/kreportsbase2.js
> +                                        else {
Tooooda la razón :+1:

2025-06-18 10:24 UTC, ainaraRT commented
**Prueba de: Operador distintode ≠ (tratamiento de claves que comparten raíz)**
Cuando haces que la condición sea distinto a "Papa", la prueba de _Comprobar que los registros correspondientes a "papanatas" ya no aparecen en el resultado_ no coincide. Como se puede observar en las capturas, los registros que tiene "Papanatas" siguen apareciendo, además de los que tienen seleccionados ambos valores. 
![image](https://github.com/user-attachments/assets/e54a7644-6269-4781-9003-7c2f0b3b96ce)
![image](https://github.com/user-attachments/assets/d55d3df7-8f9c-47db-967a-68b592cbe91b)

2025-06-18 10:39 UTC, ainaraRT commented
**Prueba de: Operador distintode ≠ (tratamiento general)**
Si el valor es distinto al nombre "Ángel", el registro "Ángel María" sigue apareciendo. No sé si debería de ser así.
![image](https://github.com/user-attachments/assets/ae9a645e-ce48-4397-8195-d322ce44e94c)
![image](https://github.com/user-attachments/assets/a2914092-97c7-427b-97c5-0e4320e57469)


No puedo realizar la prueba con NULL porque me da error al guardar el campo con ese valor en Estudio. (Lo mismo para la prueba de **Operador =**)
![image](https://github.com/user-attachments/assets/ab437080-3e24-445b-9d82-d9e3fa67d6ae)

2025-06-18 10:48 UTC, ainaraRT requested changes
Ver comentarios. Las pruebas de **Quote de los valores**, **Operador esunode** e **Informes no dañados** funcionan.

2025-06-20 08:38 UTC, enricsinergia commented
> **Prueba de: Operador distintode ≠ (tratamiento de claves que comparten raíz)** Cuando haces que la condición sea distinto a "Papa", la prueba de _Comprobar que los registros correspondientes a "papanatas" ya no aparecen en el resultado_ no coincide. Como se puede observar en las capturas, los registros que tiene "Papanatas" siguen apareciendo, además de los que tienen seleccionados ambos valores. ![image](https://private-user-images.githubusercontent.com/95768967/456451726-e54a7644-6269-4781-9003-7c2f0b3b96ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzOTcwNDUsIm5iZiI6MTc1MDM5Njc0NSwicGF0aCI6Ii85NTc2ODk2Ny80NTY0NTE3MjYtZTU0YTc2NDQtNjI2OS00NzgxLTkwMDMtN2MyZjBiM2I5NmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIwVDA1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNWM2MmIxZjRjMDNkMjU2ZWZjNjk5YTYzOTJmNmI2ZDEyYzA0YWQwNWI0MjRmYTUxNzY3ODFhMWIxZjgwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7lGpPJ-BxgDMjJEzI2FH9zKncFdbW0oprYZQvCo6HtE) ![image](https://private-user-images.githubusercontent.com/95768967/456452102-d55d3df7-8f9c-47db-967a-68b592cbe91b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzOTcwNDUsIm5iZiI6MTc1MDM5Njc0NSwicGF0aCI6Ii85NTc2ODk2Ny80NTY0NTIxMDItZDU1ZDNkZjctOGY5Yy00N2RiLTk2N2EtNjhiNTkyY2JlOTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIwVDA1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNTVkN2JlYzg0MTUxMGZhNjhmMTIxNzhkMDMzMTY1NTA4YjYxMzhkNTU4ZDM1YzdmNzRiMGFmMjJkMWJmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7wYZZsw_wLGms8pzIkKw3-uzJpXHneREZPBARYhqsAo)

Revisado con Ainara: el error está en la descripción de la prueba

2025-06-20 08:40 UTC, enricsinergia commented
> **Prueba de: Operador distintode ≠ (tratamiento general)** Si el valor es distinto al nombre "Ángel", el registro "Ángel María" sigue apareciendo. No sé si debería de ser así. ![image](https://private-user-images.githubusercontent.com/95768967/456456555-ae9a645e-ce48-4397-8195-d322ce44e94c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzOTcwNDUsIm5iZiI6MTc1MDM5Njc0NSwicGF0aCI6Ii85NTc2ODk2Ny80NTY0NTY1NTUtYWU5YTY0NWUtY2U0OC00Mzk3LTgxOTUtZDMyMmNlNDRlOTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIwVDA1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OWJjODE3MjlmNTcwOTI4M2MxNTJiMjhjNGMyYzA1MDYyNWU0MzE1ODEyZTMyNWExZWZkNzA4ZTQ3MWRlODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KH8f-5IaT5q0K3T-InEMzjyY36v_XIBwvf5GDjF1Lkc) ![image](https://private-user-images.githubusercontent.com/95768967/456457300-a2914092-97c7-427b-97c5-0e4320e57469.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzOTcwNDUsIm5iZiI6MTc1MDM5Njc0NSwicGF0aCI6Ii85NTc2ODk2Ny80NTY0NTczMDAtYTI5MTQwOTItOTdjNy00MjdiLTk3YzUtMGU0MzIwZTU3NDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIwVDA1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNjlmODBlZGJjYzMxODIzYjEzNzg0MzMyNDFlNDIzYTI3ZTAyOGMyYjFlODA5YzkyMmI5Mjc1ZjIwNDEwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hkMX2o-PZ77apckyPvZ43KdkeGgRlUaj4738i84lRpg)
> 
> No puedo realizar la prueba con NULL porque me da error al guardar el campo con ese valor en Estudio. (Lo mismo para la prueba de **Operador =**) ![image](https://private-user-images.githubusercontent.com/95768967/456461573-ab437080-3e24-445b-9d82-d9e3fa67d6ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzOTcwNDUsIm5iZiI6MTc1MDM5Njc0NSwicGF0aCI6Ii85NTc2ODk2Ny80NTY0NjE1NzMtYWI0MzcwODAtM2UyNC00NDViLTlkODItZDllM2ZhNjdkNmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIwVDA1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YjlhZDBiNjk0YzAyOWEzZjAxZWU5MTJiYWUyMTcwYTc1OWViNTQzMzVlYWVhMTkzMDQ0ZTA4M2MzNWQzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.82taGo4PG4IqO4WtCUOjiwwaik_XQtnY37B7CAhM8EI)

Revisado con Ainara.
Ya es correcto que el distinto de en un campo texto evalue el contenido completo.
Respecto al error NULL, se descarta. La prueba a hacer es tener un registro que no tenga valor en ese campo (en BBDD NULL), por lo que ya no habrá error en Estudio.

2025-06-20 11:29 UTC, ainaraRT approved these changes
(A)Probado

2025-06-24 09:56 UTC, ManuSinergiaCRM approved these changes
(A)probado

2025-06-25 07:37 UTC, merged