Hotfix - Proyectos - Inclusión de ficheros javascript en view.detail.php
SinergiaTIC/SinergiaCRM pull request #529
Opened 2024-12-26 07:51 UTC by juanSTIC

- solves #272 

## Description
Para evitar el problema descrito en el issue se ha optado por hacer la inclusión de los ficheros Javascript usados en la vista de detalle de Proyectos directamente en el controlador de la vista `custom/modules/Project/views/view.detail.php`.

Además del fichero faltante detectado en el issue _(modules/Project/js/custom_project.js),_ se ha añadido el fichero _modules/Project/Project.js_, por igualar la estratégia, al menos en este fichero.

**Cómo probarlo**
1. Hacer cualquier modificación en estudio en la vista de detalle de Proyectos
2. En el fichero _custom/modules/Project/metadata/detailviewdefs.php_ eliminar o comentar las líneas correspondientes al array _includes_, que referencia a los ficheros javascript. 
3. Verificar que, tras hacerlo, las funcionalidades javascript de la vista de detalle siguen funcionando, incluido el borrado del proyecto desde el menú de acciones

2025-01-17 10:53 UTC, jordiSTIC reviewed
Se ha verificado el comportamiento: Se incluyen correctamente los ficheros .js aunque el detailviewdefs.php no los incluya.

Cuestión: ¿Porqué no se eliminan los includes del detailviewdefs? Estos .js se incluirán siempre al cargar la vista de detalle, y versionados. Esto hará que se carguen dos veces como dos recursos distintos (uno sin versionar y otro versionado). No veo mucho problema en eso, pero yo los quitaría

2025-01-17 11:34 UTC, juanSTIC commented
> Se ha verificado el comportamiento: Se incluyen correctamente los ficheros .js aunque el detailviewdefs.php no los incluya.
> 
> Cuestión: ¿Porqué no se eliminan los includes del detailviewdefs? Estos .js se incluirán siempre al cargar la vista de detalle, y versionados. Esto hará que se carguen dos veces como dos recursos distintos (uno sin versionar y otro versionado). No veo mucho problema en eso, pero yo los quitaría

De acuerdo con la propuesta, se han eliminado la inclusión redundante de los ficheros en el detailviewdef a favor de la inclusión versionada en view.detail.php

2025-01-17 13:04 UTC, jordiSTIC approved these changes
(A)Probado

2025-01-20 11:50 UTC, AlbertoSTIC requested changes
Faltan los comentarios STIC-Custom en los ficheros del core.

2025-01-20 12:10 UTC, juanSTIC commented
> Faltan los comentarios STIC-Custom en los ficheros del core.
  
No tengo claro cómo hemos de reflejar esta situación. 

Si se trata del fichero _modules/Project/metadata/detailviewdefs.php_ este ya tiene un bloque STIC Custom, pero nosotros estamos haciendo cambios dentro de nuestro propio bloque de código, y entiendo que aquí no debemos añadir nada más ¿no?. Lo que sí he hecho es añadirlo al proyecto de modificaciones del core como Internal STIC

2025-01-21 09:13 UTC, AlbertoSTIC approved these changes
Aprobado

2025-01-21 09:16 UTC, merged