Enhancement - General - Establecer foco automáticamente en búsqueda global
SinergiaTIC/SinergiaCRM pull request #531
Opened 2024-12-26 12:43 UTC by juanSTIC

- solves #440 

Se añade globalmente el javascript necesario para que el input de búsqueda global obtenga el foco al ser mostrado en cualquiera de las dimensiones de pantalla.

**Cómo probarlo**
Verificar que se obtiene el foco.

2025-01-20 11:44 UTC, PaulaaSTIC approved these changes
(A)probado

2025-01-20 11:44 UTC, AlbertoSTIC requested changes
Entiendo que no es necesario el console.log.

2025-01-21 08:44 UTC, AlbertoSTIC approved these changes
Aprobado

2025-01-21 09:00 UTC, PaulaaSTIC approved these changes
(A)probado

2025-01-21 09:08 UTC, merged

2025-06-23 15:08 UTC, SinergiaCRM commented
Creado PR en SuiteCRM https://github.com/salesagility/SuiteCRM/pull/10692