Improvement - General -  Visualización de detalles adicionales en popup emergente
SinergiaTIC/SinergiaCRM pull request #533
Opened 2024-12-30 17:33 UTC by PaulaaSTIC

## Descripción
El tooltip de detalles adicionales se cortaba en vistas emergentes y ocultaba parte de la información, dificultando la interacción.

Modificada la configuración de qTip para:

Añadir límites de viewport
Implementar ajuste automático de posición

## Pruebas

1. Verificar visibilidad del tooltip en vistas emergentes
2. Probar que se mantiene una visualización correcta en  vista de lista

2025-01-16 16:25 UTC, jordiSTIC requested changes
Sugiero reestablecer espaciado modificado en comentarios.
Probado: El ToolTip se visualiza correctamente tanto en vista lista como en popup emergente de selección de elementos.

Observación: En popup emergente de selección, los links no abren el elemento, en cambio en el tooltip el link abre el elemento en el popup. No creo que sea un error, pero quizá sí para tenerlo en cuenta

2025-01-20 16:36 UTC, juanSTIC requested changes
Creo que sería bueno ajustar la visualización de manera que el propio tooltip no tape parte del cuadro de selección, ya que dificulta el uso.

2025-01-29 12:14 UTC, jordiSTIC submitted a review, later dismissed
(A)Probado

2025-06-11 09:59 UTC, juanSTIC requested changes
aa

2025-06-11 10:07 UTC, juanSTIC approved these changes
Visto y probado

2025-06-25 07:33 UTC, merged