Feature - General - Vistas Personalizadas
SinergiaTIC/SinergiaCRM pull request #73
Opened 2024-01-19 20:13 UTC by jordiSTIC

- Closes #45

2024-02-29 07:30 UTC, AlbertoSTIC commented
Creo que el fichero en esta ruta custom/modules/logic_hooks.php puede ser personalizado por alguna entidad que haya instalado un plugin de la SuiteCRM store. Merecería la pena moverlo a Extension.

2024-03-18 07:19 UTC, juanSTIC requested changes
Al abrir el PR se muestran multiples warnings de php en cualquier página. Se ha comprobado que esto ocurre específicamente en este PR y no en otros 
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/46187267/3f5d0bc7-bcb4-4c48-a011-925aa35cfef4)

2024-03-18 07:44 UTC, jordiSTIC commented
> Al abrir el PR se muestran multiples warnings de php en cualquier página. Se ha comprobado que esto ocurre específicamente en este PR y no en otros ![image](https://private-user-images.githubusercontent.com/46187267/313582382-3f5d0bc7-bcb4-4c48-a011-925aa35cfef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDgwNTQsIm5iZiI6MTcxMDc0Nzc1NCwicGF0aCI6Ii80NjE4NzI2Ny8zMTM1ODIzODItM2Y1ZDBiYzctYmNiNC00YzQ4LWEwMTEtOTI1YWEzNWNmZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3NDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNjZhYTQ2N2JjMmYyMTcyNjMyYmFjMGIxZTE3MzQ1NjM3NDVhNTQ5YTllYTRkYmZjNTE3NGU4Y2NmZDg3NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vsBQvRkZRbl6pVTjNQP2W7qXB-za4yTHIj46G3RXmgQ)

Parece ser que se produce al cargar el módulo temporal de pruebas jblt_TestingCustomViews que se eliminará

2024-03-18 14:59 UTC, juanSTIC commented
Veo algo extraño (o que no comprendo) en la acción fixed_value:

Si establezco un valor fijo en la vista de edición, funciona correctamente, pero me permite cambiarlo y aunque guarde se volverá a establecer como fixed_value al recargar el registro en la vista de edición, y el cambio realizado no servirá para nada. Igual se me escapa algo, pero ¿no sería más sólido que fixed_value fuera acompañado siempre de solo_lectura?

2024-03-18 15:18 UTC, juanSTIC commented
Para responder mejor a la idea de acciones que se realizan sugiero usar un juego de términos algo más específicos y que recogen la acción a realizar:
```
Visible -> Alternar visibilidad
Sólo lectura -> Alternar modo de edición
Obligado -> Alternar obligatoriedad
Valor fijo -> Cambiar el valor
Texto fijo -> Cambiar la etiqueta
Color del texto -> Cambiar el color del texto
Color del fondo -> Cambiar el color de fondo
Negrita -> Alternar negrita
Cursiva -> Alternar cursiva
Subrayado -> Alternar subrayado
Aplicar estilo css -> Aplicar estilo CSS
```

2024-03-18 15:29 UTC, juanSTIC commented
Al editar los subpaneles de Personalizaciones, si pulso "contraer" en cualquiera de ellos (Básico, Condiciones y Acciones) se contraen todos y si pulso expandir, se expanden todos...

2024-03-18 15:31 UTC, jordiSTIC commented
> Veo algo extraño (o que no comprendo) en la acción fixed_value:
> 
> Si establezco un valor fijo en la vista de edición, funciona correctamente, pero me permite cambiarlo y aunque guarde se volverá a establecer como fixed_value al recargar el registro en la vista de edición, y el cambio realizado no servirá para nada. Igual se me escapa algo, pero ¿no sería más sólido que fixed_value fuera acompañado siempre de solo_lectura?

La acción fixed_value asigna el valor que se indique a un campo, cuando se cumplan las condiciones. Este valor se guardará al guardar el registro, pero si no se indica lo contrario, es editable. Está pensado para asignar "valores por defecto" según unas condiciones. Por ejemplo: el personal encargado de registrar la mesdicación, por defecto tendrán "Sí" en medicación administrada, pero pueden indicar "No"
Es cierto que al editar de nuevo un registro con el valor cambiado 'conscientemente', si se cumplen las condiciones volverá a asignar el valor indicado en la acción.
Una posible solución sería modificando la condición, añadiendo una que indique "Si el campo a asignar valor está vacío"

2024-03-18 15:35 UTC, juanSTIC commented
> Una posible solución sería modificando la condición, añadiendo una que indique "Si el campo a asignar valor está vacío"

En mi opinión esto sería bastante coherente; se mantiene el dinamismo de la acción, pero elimina el comportamiento confuso...

2024-03-18 15:36 UTC, juanSTIC commented
Establecer un color de fondo solo para el encabezado de un Panel no aplica, al menos en las pruebas realizadas,
`panel_modification:LBL_STIC_PANEL_CONTACT_DATA.background=#22c37d(panel_header)`

2024-03-18 16:12 UTC, jordiSTIC commented
> Al editar los subpaneles de Personalizaciones, si pulso "contraer" en cualquiera de ellos (Básico, Condiciones y Acciones) se contraen todos y si pulso expandir, se expanden todos...

Solucionado: Se ha tenido que cambiar el código que gestiona los eventos en los paneles de la plantilla EditView.tpl

2024-03-18 16:22 UTC, juanSTIC reviewed
En las condiciones, la comparación de los valores es _Case sensitive_, y no digo que esté mal, pero en general el comportamiento para el usuario no es así, por ejemplo en las búsquedas, no se si puede causar algún tipo de confusión, o simplemente es cuestión de que quede correctamente documentado ...

2024-03-18 18:49 UTC, jordiSTIC commented
> Establecer un color de fondo solo para el encabezado de un Panel no aplica

Solucionado: había un problema en la gestión de la propiedad `!important` en el estilo css. También se ha solucionado otro relacionado: Al aplicar `!important` borraba cualquier estilo css aplicado anteriormente por las Acciones

2024-03-19 07:12 UTC, juanSTIC commented
Sugerencia (supongo que para fase 2): Si se pudiera convertir en un campo multiselect con _Selectize_ la selección de elementos (bien sea campo o pestañas/paneles) y estos se pudieran gestionar de manera conjunta cuando se les quiere aplicar la misma acción al conjunto, se podría reducir considerablemente el número de Personalizaciones...

2024-03-19 09:16 UTC, juanSTIC reviewed
Al modificar el color de fondo de las etiquetas en vista de detalle y edición se aplica directamente sobre el contenedor del texto, y parece que no queda muy bien. Se sugiere aplicarlo sobre el contenedor padre, aunque técnicamente abarca también al contenido del campo, este queda "protegido" por su propio colo de fondo:
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/46187267/4b276408-092b-4743-a781-a8dfa856b482)

2024-03-19 09:45 UTC, juanSTIC reviewed
En las condiciones, la opción _Es nulo/No es nulo_ evalua también si el valor del campo es vacío o si solamente contiene cadenas en blanco. El funcionamiento me parece correcto, pero creo que sería más adecuado usar una etiqueta del tipo _Es vacío o nulo_...

2024-03-19 10:47 UTC, jordiSTIC commented
> En las condiciones, la comparación de los valores es Case sensitive

Se han modificado las verificaciones de las condiciones en strings para que no sean "case sensitive"

> Al modificar el color de fondo de las etiquetas en vista de detalle y edición se aplica directamente sobre el contenedor del texto, y parece que no queda muy bien.

Corregido: A las etiquetas, antes de ser modificadas se les adapta el estilo css para que tengan el mismo tamaño que el editor.
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/126675190/ca8c0aa3-8c02-4994-9bd9-b43d400e185c)

2024-03-20 13:43 UTC, jalbaiges approved these changes
Cadenas revisadas. Dejo unos comentarios relativos a un conjunto de ficheros que parecen formar parte de un test y que posiblemente no deban desplegarse.

2024-03-20 16:53 UTC, jordiSTIC commented on custom/Extension/application/Ext/Language/ca_ES.CustomViewTest.php
Estos ficheros forman parte de un módulo para test: ya se han eliminado

2024-03-20 16:53 UTC, jordiSTIC commented on custom/Extension/modules/jblt_TestingCustomViews/Ext/Language/_override_es_ES.lang.php
Estos ficheros forman parte de un módulo para test: ya se han eliminado

2024-03-20 16:53 UTC, jordiSTIC commented on custom/Extension/modules/jblt_TestingCustomViews/Ext/Vardefs/_override_sugarfield_llistadesplegable.php
Estos ficheros forman parte de un módulo para test: ya se han eliminado

2024-03-20 16:53 UTC, jordiSTIC commented on modules/jblt_TestingCustomViews/Dashlets/jblt_TestingCustomViewsDashlet/jblt_TestingCustomViewsDashlet.meta.php
Estos ficheros forman parte de un módulo para test: ya se han eliminado

2024-03-20 17:41 UTC, jalbaiges commented
> Para responder mejor a la idea de acciones que se realizan sugiero usar un juego de términos algo más específicos y que recogen la acción a realizar:
> 
> ```
> Visible -> Alternar visibilidad
> Sólo lectura -> Alternar modo de edición
> Obligado -> Alternar obligatoriedad
> Valor fijo -> Cambiar el valor
> Texto fijo -> Cambiar la etiqueta
> Color del texto -> Cambiar el color del texto
> Color del fondo -> Cambiar el color de fondo
> Negrita -> Alternar negrita
> Cursiva -> Alternar cursiva
> Subrayado -> Alternar subrayado
> Aplicar estilo css -> Aplicar estilo CSS
> ```

Realmente lo que hacen las VP cuando ejecutan estas acciones es asegurarse de que el valor final de cualquiera de estos parámetros sea el indicado, lo cual puede suponer aplicar un cambio o no respecto de lo que se estaba viendo antes de su aplicación. En este sentido, no veo necesario incluir los términos "Alternar/Cambiar". Es más, en todas aquellas acciones en las que la personalización consiste en decir Sí o No creo que queda más claro el formato existente. Ejemplo: Visible - Sí/No. Lo mismo con los colores, creo que ya es suficientemente claro. Sí me queda la duda de las cadenas "valor fijo" y "texto fijo". Creo que "valor" y "etiqueta" serían más claros. Por cierto, por si aporta algo, la opción "valor fijo" no me aparece entre las opciones disponibles cuando quiero actuar sobre un campo.

2024-03-20 17:54 UTC, jordiSTIC commented
> Por cierto, por si aporta algo, la opción "valor fijo" no me aparece entre las opciones disponibles cuando quiero actuar sobre un campo.

La opción "valor fijo" no está disponible para la vista de detalle: indicando "valor fijo", se modifica el valor de un campo mediante javascript (no en Base de Datos), en la vista detalle "falsearía" los datos del registro. En las vistas de edición y creación rápida se podría usar para asignar valores por defecto o modificar valores de campo en función de otros, pero los cambios únicamente se guardarán al guardar el registro

2024-03-27 12:35 UTC, juanSTIC reviewed
Las comparaciones ahora son case insensitive, pero sí son sensibles a las tíldes, por lo que el comportamiento es diferente la de las búsquedas...

2024-03-27 13:09 UTC, juanSTIC reviewed
Después de varias sesiones creando Vistas personalizadas, las pantallas iniciales que al crear una nueva vista te permite seleccionar un módulo y la siguiente, que te permite seleccionar el tipo de vista, se convierten más en un lastre que en una ayuda. 
No se si se ha valorado, o si hay algún motivo técnico que no lo aconseje, pero sería más dinámico ir a una pantalla de edición clásica y mostrar un desplegable con la lista de módulos....
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/46187267/7587834e-54f9-4ef1-aa4c-c7c3f5a6bda4)

2024-04-02 16:48 UTC, jordiSTIC commented
> Las comparaciones ahora son case insensitive, pero sí son sensibles a las tíldes, por lo que el comportamiento es diferente la de las búsquedas...

Las comparaciones ya no tienen en cuenta las tildes ni las mayúsculas

2024-04-05 07:19 UTC, juanSTIC requested changes
Ver comentarios

2024-04-05 07:19 UTC, juanSTIC commented on modules/stic_Custom_Views/Utils.php
> +function getRelatedBeanObject($bean, $relationshipName)
Esta función ya se encuentra definida en SticInclude/Utils.php y si es idéntica debería reutilizarse

2024-04-05 07:19 UTC, juanSTIC commented on modules/stic_Custom_Views/Utils.php
> +function getRelatedBeanObjectArray($bean, $relationshipName)
Si esta función es genérica, debería ser movida a SticInclude/Utils.php

2024-04-05 07:19 UTC, juanSTIC commented on themes/SuiteP/include/DetailView/DetailView.tpl
Este fichero, debería estar en la misma ruta, pero en `custom`, para mantener todas las modificaciones sobre los tpls del tema SuiteP juntas,como se ha hecho hasta ahora.

2024-04-05 07:19 UTC, juanSTIC commented on themes/SuiteP/include/EditView/EditView.tpl
idem. Mover a custom

2024-04-05 07:19 UTC, juanSTIC commented on custom/themes/SuiteP/tpls/_headerModuleList.tpl
> +                                <li class="actionmenulinks" role="presentation">
Indicar en el comentario del core de la línea 992 que en este PR se modifia el código....

2024-04-05 11:28 UTC, jordiSTIC commented on modules/stic_Custom_Views/processor/LogicHooksCode.php
> +    private function compareCustomViewRestrictions($a, $b)
Hecho

2024-04-05 12:28 UTC, jordiSTIC commented on modules/stic_Custom_Views/processor/js/sticCV_View_Record_Edit.js
Se observa un comportamiento extraño de Vistas Personalizadas con este campo, al menos para las opciones de "requerido" y "solo lectura"

2024-04-08 11:02 UTC, juanSTIC commented on modules/stic_Custom_Views/Utils.php
> +function getRelatedBeanObjectArray($bean, $relationshipName)
ok

2024-04-08 11:03 UTC, juanSTIC commented on custom/themes/SuiteP/tpls/_headerModuleList.tpl
> +                                <li class="actionmenulinks" role="presentation">
visto

2024-04-08 11:04 UTC, juanSTIC commented on modules/stic_Custom_Views/Utils.php
> +function getRelatedBeanObject($bean, $relationshipName)
ok

2024-04-08 11:04 UTC, juanSTIC commented on modules/stic_Custom_Views/processor/LogicHooksCode.php
> +    private function compareCustomViewRestrictions($a, $b)
visto

2024-04-08 11:06 UTC, juanSTIC commented on modules/stic_Custom_Views/processor/LogicHooksCode.php
> +            $this->logger->error(__FILE__ . ':' . __LINE__ . ' ' . __METHOD__ . ' - ' . 'Invalid result with query: '.$sql);
ok

2024-04-08 11:17 UTC, juanSTIC commented on themes/SuiteP/include/DetailView/DetailView.tpl
visto

2024-04-08 11:17 UTC, juanSTIC commented on themes/SuiteP/include/EditView/EditView.tpl
visto

2024-04-08 16:05 UTC, juanSTIC requested changes
Ver comentarios

2024-04-09 09:49 UTC, jordiSTIC reviewed
Cambios realizados

2024-04-09 09:49 UTC, jordiSTIC commented on modules/stic_Custom_Views/processor/js/sticCV_View_Record_Edit.js
En la documentación se indica: Las personalizaciones pueden no funcionar correctamente en los campos complejos o especiales que necesitan javascript para ser representados. Por ejemplo, el campo "Artículos" del módulo "Facturas", o el campo "Duración" del módulo "Llamadas"

2024-04-09 09:49 UTC, jordiSTIC commented on modules/stic_Custom_Views/processor/js/sticCV_View_Record_Edit.js
En la documentación de la wiki se comenta: Las personalizaciones pueden no funcionar correctamente en los campos complejos o especiales que necesitan javascript para ser representados. Por ejemplo, el campo "Artículos" del módulo "Facturas", o el campo "Duración" del módulo "Llamadas"

2024-04-09 09:49 UTC, jordiSTIC commented on custom/include/generic/SugarWidgets/SugarWidgetSubPanelDuplicateButtonstic.php
> +        $parent_record_id = $_REQUEST['record'];
Eliminado

2024-04-09 09:49 UTC, jordiSTIC commented on modules/stic_Custom_View_Actions/stic_Custom_View_Actions.php
> +            LoggerManager::getLogger()->warn('Posted field is undefined: ' . $type);
Cambiadas las escrituras en log en stic_Custom_Views_Actions y stic_Custom_Views_Conditions

2024-04-09 09:49 UTC, jordiSTIC commented on modules/stic_Custom_View_Customizations/Menu.php
> +}
Eliminado

2024-04-10 14:39 UTC, jordiSTIC commented
Respondo a los puntos:
> 1. Si tengo una regla que en fucnión del valor de un campo me setea el valor de otro campo, cuando entro al registro veo un valor que el registro en realidad no tiene (ni tendrá si no grabo el registro).

Es así, se alerta tanto en el Webminar como en la documentación de la wiki (no pública aún):
https://wikisuite.sinergiacrm.org/index.php?title=Vistas_Personalizadas#Consideraciones_adicionales
" `Si una acción asigna un valor por defecto a un campo, éste puede ser distinto al que haya en la Base de Datos, y no se guardará hasta que el usuario apriete el botón de "Guardar" del registro que está editando`".

Para facilitar su comprensión, como se indicó en comentarios anteriores, se cambió el nombre de la acción de "`valor fijo`" a "`valor por defecto`"

> 2. Las condiciones en campo multi-selec equals y contains se comportan igual. En mi opinión la "contains" debería hacer un OR entre los valores seleccionados

El comportamiento es distinto. Para multi-select: 
- Equals a un conjunto de elementos => Que los valores seleccionados sean exactamente los mismos elementos
- Contains con un elemento => Que el conjunto de valores seleccionados contenga ese elemento
- Contains con múltiples elementos => Que el conjunto de valores seleccionados contenga los elementos  de la condición

Para crear condiciones con el operador OR, es necesario duplicar la personalización: Las personalizaciones aplican el operador AND en sus condiciones

> 3. Por defecto nome salen las reglas ordenadas por orden de aplicación. Una vez marco el descendente en el subpanel ya está pero si vuelvo al cabo del tiempo, vuelve a no estar ordenado.

Pendiente de solucionar

> 4. No aplica el orden de reglas. Engo una regla (1) que dice si status = Active pon color azul y una regla (2) que dice si status no es nulo pon verde. A pesar de ello, si pongo status activo me pone el azul. Quizás es porqué es más específica la condición.

Por programación se asignan en orden a los eventos de cambio de los campos involucrados. Pendiente de revisar

> 5. En los campos de tipo fecha la consición de si es nulo no me está funcionando.

Solucionado en f07b82fbd2b2a481d2cb4bc97d232ecff3e12a14

> 6. Los campos basados en lista dinámica no se pueden usar en condiciones. En la última prueba realizada sólo me aparecen algunos de los valores posibles

Pendiente de solucionar

2024-04-10 16:28 UTC, juanSTIC approved these changes
Visto y probado

2024-04-11 08:21 UTC, PaulaaSTIC approved these changes
(A)probado

2024-04-11 08:22 UTC, merged