Hotfix - General - Corrección del script que da de alta los schedulers en inglés
SinergiaTIC/SinergiaCRM pull request #9
Opened 2024-01-03 16:09 UTC by enricsinergia

## Description
Al hacer un alata de instancia en inglés (el idioma por defecto si no se indica en lainstalación del workit lo contrario), se ha detectado que había una sentencia SQL incorrecta.
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/57436616/d9c97304-b3fc-4ee6-8220-bafab526ad05)

## Pruebas
1. Instalar el Workkit desde 0 (borrando base de datos) y comprobar que se dan de alta correctamente los schedulers.
2. [Alternativa] Revisar el cambio de código (un ; por una ,)

2024-01-11 13:45 UTC, ainaraRT approved these changes
(A)Probado instalando desde cero el Workkit y borrando base de datos

2024-01-17 14:36 UTC, ManuSinergiaCRM requested changes
En el mismo fichero, ocurre lo mismo en la línea 68

Y en el mismo fichero del resto de idiomas también de dan los dos errores:
- SticInstall/sql/ca/Schedulers.sql
- SticInstall/sql/es/Schedulers.sql
- SticInstall/sql/gl/Schedulers.sql

Además, estoy comprobando que los registros de la línea 42 y 69  existen en las instancias. En unos minutos informo de los resultados

2024-01-17 18:30 UTC, ManuSinergiaCRM commented
Confirmo que las instancias de las entidades tienen los registros de las líneas 42 y 69. La única instancia que no los tiene es la de Jordi.

2024-01-17 18:31 UTC, ManuSinergiaCRM approved these changes
(A)probado

2024-01-18 09:15 UTC, AlbertoSTIC approved these changes
(A)probado.

2024-01-18 09:15 UTC, merged