Feature - General - Vista de "Edición rápida"
SinergiaTIC/SinergiaCRM pull request #93
Opened 2024-01-30 12:02 UTC by jordiSTIC

## Description

## Motivation and Context

## How To Test This

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2024-02-08 09:03 UTC, jordiSTIC commented
> Duda previa: ¿Cómo y por qué se han escogido los módulos escogidos?
> 
> Por ejemplo, ¿por qué relación persona sí, pero relación organización no? ¿O por qué se ha dejado fuera sesión, assitencia, oferta, locations, llamadas, notas, tareas? Hay módulos (encuestas, LPOs, ...) que queda claro que deben entrar en este juego, totalmente cierto. Y algunos como Personas, Organizaciones, Reservas o Recursos que supongo que es por ser los módulos que son que tampoco se han incluído.
> 

Se ha realizado una primera aproximación únicamente con parte de los subpaneles de Persona que tienen asociada la creación rápida . 
El listado de los módulos a los que aplicar esta mejora no se ha analizado en profundidad y está sujeto a propuestas

> Y otra duda: ¿Sería posible hacer que por defecto este fuera el comportamiento o el widget añadido? (o mejor que se puediera configurar en studio)

Debería analizarse, y no se había planteado. Podría ser una buena evolución a esta nueva funcionalidad

2024-02-08 10:17 UTC, enricsinergia commented
Entendido.

Propuesta:
- Incluir los siguientes módulos: relación con organizaciones, sesión, assitencia, oferta laboral, locations, llamadas, notas, tareas y reuniones
- Quitar: Valoraciones y Compromisos de Pago
- A valorar: En el apartado de Productos, Facturas, etc, siguiendo el criterio enunciado a continuación, sólo utilizaría el nuevo widget en Productos (en quotes, invoices y contracts creo que es bueno que se vaya a ver el registro con sus subpaneles).

Criterio usado (a valorar y discutir): Si alguien toca un CdP me interesa que vea los pagos que tiene asociados (quizás hay algún impagado o pago pendiente sobre el que hay que actuar y no lo veré si no voy a la pantalla de CdP). Algo parecido pasa con Valoraciones: normalmente la valoración cobra sentido con los objetivos asociados y por eso prefiero que vayan a la propia Valoración a tocar y no ponérselo fácil para tocar desde otra parte.

Por el resto, la pruebas hechas han ido bien. La única incidencia detectada (#109 ) no es causada por este PR.

2024-02-12 08:44 UTC, juanSTIC requested changes
En cuanto al funcionamiento no he visto ningún error, pero hago la siguiente apreciación previa a la aprobación:
Como usuario es imprevisible y me resulta  algo inquietante  :) que el comportamiento sea diferente en unos subpaneles que en otros.  Me gusta el cambio y creo que será el modo elegido para modificar datos en muchos casos. Creo que un buen punto de partida sería:
 - habilitar el modo edición en todos los subpaneles (excepto si hay alguna razón técnica para hacerlo)...
 o
 - añadir algún icono al botón o cambiar el texto a _Editar en linea_ (o similar) para que el usuario conozca lo que va suceder al pulsar el botón.

(creo que me inclino más por la segunda propuesta)

2024-02-12 10:39 UTC, AlbertoSTIC commented
> * Quitar: Valoraciones y Compromisos de Pago

> Criterio usado (a valorar y discutir): Si alguien toca un CdP me interesa que vea los pagos que tiene asociados (quizás hay algún impagado o pago pendiente sobre el que hay que actuar y no lo veré si no voy a la pantalla de CdP). Algo parecido pasa con Valoraciones: normalmente la valoración cobra sentido con los objetivos asociados y por eso prefiero que vayan a la propia Valoración a tocar y no ponérselo fácil para tocar desde otra parte.


Actualmente, si alguien hace click en "Editar" en un CdP del subpanel en Personas, se abrirá directamente la vista de Edición del CdP y no se verán los Pagos asociados a ese CdP. Por lo tanto, si aplicamos esta "Edición rápida" el resultado sería el mismo. 

Otro caso es que quitemos la opción de Editar desde el subpanel y obliguemos al Usuario a hacerlo desde su vista de detalle. Esto último de momento no lo haría de momento.

> En cuanto al funcionamiento no he visto ningún error, pero hago la siguiente apreciación previa a la aprobación: Como usuario es imprevisible y me resulta algo inquietante :) que el comportamiento sea diferente en unos subpaneles que en otros. Me gusta el cambio y creo que será el modo elegido para modificar datos en muchos casos. Creo que un buen punto de partida sería:
> 
> * habilitar el modo edición en todos los subpaneles (excepto si hay alguna razón técnica para hacerlo)...
>   o
> * añadir algún icono al botón o cambiar el texto a _Editar en linea_ (o similar) para que el usuario conozca lo que va suceder al pulsar el botón.
> 
> (creo que me inclino más por la segunda propuesta)

Desde la "Edición rápida" el usuario ya tiene una manera de ir al formulario completo:
![Selection_149](https://github.com/SinergiaTIC/SinergiaCRM/assets/46563429/8afa8774-2e8b-46cb-83f8-ac6894467251)
Por lo tanto yo diría de seguir con la opción 1: Habilitar la edición rápida por defecto en todos los módulos, excepto para aquellos casos que por razones técnicas, no se pueda.

Ahora las dudas serían:
- ¿Qué pasa con los módulos custom que ya tengan las entidades?
- ¿Qué pasa con los módulos custom nuevos del constructor?

2024-02-21 15:53 UTC, juanSTIC submitted a review, later dismissed
Hechas las pruebas indicadas, además se ha probado el funcionamiento en un nuevo módulo creado con el constructor y fucniona correctamente, lo único reseñable (no me parece suficiente  como para no aprobarlo es que no aparece la etiqueta con el nombre del widget en estudio:
![image](https://github.com/SinergiaTIC/SinergiaCRM/assets/46187267/aadcad42-da2b-4ab9-b962-1a9e0aa611b0)

2024-02-21 16:34 UTC, jordiSTIC commented
Se han añadido las etiquetas correspondientes en las plantillas de nuevos módulos para que aparezcan en el constructor

2024-02-21 16:36 UTC, AlbertoSTIC submitted a review, later dismissed
(A)Probado

2024-02-21 17:52 UTC, jalbaiges approved these changes

2024-02-22 08:29 UTC, enricsinergia approved these changes
(A)provado

2024-02-22 08:58 UTC, merged

2025-01-27 10:15 UTC, SinergiaCRM commented
PR en SuitecRM: https://github.com/salesagility/SuiteCRM/pull/10626