Hotfix - Formularios - Tratamiento de apóstrofes en el nombre de la Organización
SinergiaTIC/SinergiaCRM pull request #97
Opened 2024-01-31 08:00 UTC by enricsinergia

- Closes #96 

## Descripción
Cuando no se rellena el NIF de la organización, se hace una búsqueda por nombre de la organización.
El problema era que en la SQL para realizar la búsqueda se insertaba directamente el $name recuperado del formulario. Se ha modificado para utilizar préviamente la función _quote_ que realiza un escapado de carácteres especiales.

## Pruebas
1. Crear un formulario de inscripción a eventos que contenga campos de organización (no el NIF)
2. Introducir vía el formulario una organización cuyo nombre contenga un apóstrofe
3. Repetir el envío del formulario
4. Comprobar que la organización no se duplica

2024-02-07 16:55 UTC, ManuSinergiaCRM requested changes
Comprobado que la solución funciona. 

Además, he probado a ver si se podía evitar consultar el nombre a la base de datos sustituyendo `$sqlName = $db->quote($name); `por `$sqlName = html_entity_decode($name, ENT_QUOTES);` pero la primera devuelve` 'De l\'home'` y la segunda `'De l'home'`. 

Por otro lado, pido revisión de cambios por que pienso que podemos ampliar el alcance de este PR ya que al realizar las pruebas he visto que:
- Si una persona ya existe en el CRM, no se realiza la vinculación entre la persona y la organización. 
- Si la persona no existe, sí se vinculan

2024-02-07 16:56 UTC, ManuSinergiaCRM approved these changes

2024-02-07 16:57 UTC, ManuSinergiaCRM commented
(A)probado. Comprobado que la solución funciona.

Además, he probado convertir la cadena codificada a través de `html_entity_decode` para evitar consultar el nombre a la base de datos sustituyendo $sqlName = $db->quote($name); por $sqlName = html_entity_decode($name, ENT_QUOTES); pero la primera devuelve 'De l\'home' y la segunda 'De l'home'.

2024-02-21 12:38 UTC, jordiSTIC approved these changes
(A)Probado

2024-02-22 08:57 UTC, merged